### PR TITLE
[State-sync] Fix a bug in the request epoch calculation

### PR DESCRIPTION
**Pull request by dmitri-perelman**
Summary:
During the request processing a state-sync sends an optimistic request for the next chunk.
The epoch number of that request should be either current epoch, or the next epoch if the received chunk is the last one in its current epoch.
We had a bug, in which the condition of "last chunk in its epoch" was checked by inspecting the `next_validator_set` of the received ledger info.
Even if the received ledger info is the last one in its epoch, the received chunk might still be in the middle. As a result, we could erroneously ask for an epoch that we cannot verify, which broke the download pipeline, and state sync would become very slow.

The current change is checking for the "last chunk in its epoch" by both inspecting the `next_validator_set` and by comparing the future would-be version with the version of the ledger info.

Tests: unit tests

### CODE REVIEW

**Comment by zekun000** [comment]
how's this observed? pre-mainnet perf test?

**Comment by mgorven** [comment]
> how's this observed? pre-mainnet perf test?

Yes, one of the partner's full nodes first exhibited this. I had done some validator set changes.

**Comment by zekun000** [comment]
we probably should add some tests for this (smoke test?)

**Comment by dmitri-perelman** [comment]
You're absolutely right.
Adding an integration test for this condition is tricky (I don't see a way to do it) because the node does eventually catch up, just slowly: it's retrying once in a while and every time it retries it succeeds (only the optimistic requests fail).
And, obviously, adding some reconfigurations to the cluster test + fresh nodes joining would expose this because we'd see some super slow folks trying to catch up.

**Pull request closed without merging**
