### PR TITLE
[ci] Checking for dependency growth

### PR DESCRIPTION
**Pull request by mimoo**
**DO NOT ACCEPT THIS PR YET :D**

## Motivation

It would be great to check if a PR actually increases the number of (depth=0) dependencies.
This PR provides a script that will fail the `commit-workflow` of circle CI.

Effectively, this means that to merge a PR that increases the number of dependencies, one will have to consciously merge a PR that fails the circle CI.

Ideally I would like to provide a warning instead of a failure, but I'm not sure if this is possible.

It is called **dependency_hello** for obvious reasons

## Test Plan

I am testing this in this PR itself! 

Check https://circleci.com/gh/libra/libra/1192?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link 

Right now, it is part of the `commit-workflow`:

```
commit-workflow:
    jobs:
      - build
      - terraform
      - dependency_hello
```

What I need to understand is:

* does it affect the actual merge in our codebase? This would be bad as it is doing a `checkout master` at the ned.
* can it not block a pull request if it fails? This is only intended as a warning.

### CODE REVIEW

**Comment by mimoo** [comment]
@bschwab  can you add me to circleci for this? same nickname.

**Comment by mimoo** [comment]
That's a very good point! We shouldn't discourage growth of internal dependencies (as this probably mean smaller and more manageable crates at the moment).

Ideally I wanted this PR not to introduce another dependency so I went the script route. I just modified the script to check if the dependency has a "path", and if it has one, I ignore it. I think that should do the trick.

**Comment by bschwab** [comment]
Looks like a decent approach, @metajack can you take a look?

**Comment by metajack** [comment]
@mimoo and I spoke briefly about this. I think the best way would be to use a [probot](https://probot.github.io/) bot to comment on PRs that add to the dependency list.

Basically you'll want the bot to pull the base revision's Cargo.tomls and compare against the current revision's.

Leaving a comment puts the decision in the hands of the reviewer, instead of into CI.

I'm planning to build a simillar bot that flags changes or introductions of unsafe.

**Comment by mimoo** [comment]
I think that's a great way to tackle this btw :) I'll look into it.

**Comment by bmwill** [comment]
I'm going to close this since it appears like we've decided to go the probot way and potentially build some tooling around Cargo.lock to better track dependencies.

**Pull request closed without merging**
