### PR TITLE
[language/ir-to-bytecode] use Foo_ for unspanned, Foo for spanned

### PR DESCRIPTION
**Pull request by sunshowers**
This follows the convention in Ocaml and in the Move language source compiler.

In the previous scheme, there was an (unspanned) `Var::new_` method which would
produce a (spanned) `Var_`. Now that the situation is reversed, the naming scheme
stopped making sense (`Var_::new_` would produce `Var`) -- so the method has
been removed and its code inlined.

### CODE REVIEW

**Comment by bob-wilson** [comment]
@sunshowers Can you please update the parser code in syntax.rs so that the function names match this new convention? There are a number of functions with names like "parse_X" and "parse_X_" and those names are now backwards.

**Comment by tnowacki** [comment]
@bob-wilson @sunshowers Ah, I forgot about those, sorry. And I think there might be the same issue with compiler functions...

**Comment by sunshowers** [comment]
Ahh, thanks for catching those! Will tackle on Monday.

**Comment by sunshowers** [comment]
> @bob-wilson @sunshowers Ah, I forgot about those, sorry. And I think there might be the same issue with compiler functions...

I checked in ir-to-bytecode/src/compiler.rs and I didn't spot any methods that should be renamed.

**Pull request closed without merging**
