### PR TITLE
Cargo Audit Fixes

### PR DESCRIPTION
**Pull request by ankitkacn**
## Motivation

- Cargo Audit Fix

## Test Plan

- CI/CD tests are covered

### CODE REVIEW

**Comment by borsdiem** [comment]
:broken_heart: Test Failed - [ci-test](https://github.com/diem/diem/actions/runs/5174151190)

**Comment by borsdiem** [comment]
:broken_heart: Test Failed - [ci-test](https://github.com/diem/diem/actions/runs/5174230429)

**Comment by borsdiem** [comment]
:broken_heart: Test Failed - [ci-test](https://github.com/diem/diem/actions/runs/5174471097)

**Review by dhaneshacn — APPROVED** [review]

**Comment by ankitkacn** [comment]
Closing this PR due to technical issue, New PR - https://github.com/diem/diem/pull/10879

**Pull request closed without merging**
