### PR TITLE
[easy][language] rewrite complex match in module_cache

### PR DESCRIPTION
**Pull request by huitseeker**
Rewrite an instance of an and_then to simplify this complex nested match. YMMV

### CODE REVIEW

**Comment by dariorussi** [comment]
it's hard for me to see any value in those kind of changes, just fyi.
Others may feel otherwise of course and I'll leave it to them

**Comment by bmwill** [comment]
I'm with @tnowacki and @dariorussi, this makes it much more challenging to read. Sometimes it makes things shorter and easier to read when using these sorts of combinators, but when logic starts to get a bit longer and complex like these pieces it pays to be more verbose and explicit (in this case its actually more verbose with your change than as is).

**Comment by huitseeker** [comment]
@bmwill @dariorussi @tnowacki — cool, that's exactly the kind of feedback I was looking for! Thanks for giving this the once-over!

**Comment by mimoo** [comment]
Maybe we should add something in `contributing.md`

I find all these map, map_err, etc. to be good when kept short, but otherwise they reduce clarity to the code.

**Pull request closed without merging**
