### PR TITLE
Update dev_setup.sh to support Windows user (with subsystem linux)

### PR DESCRIPTION
**Pull request by srihamat**
I try on Windows subsystem linux and found out that it doesn't have updated protoc. Modify URL as this part will help.

## Motivation

I realized that many people is in Windows environment and they want to experience on Libra but they cannot because limitation in the system they have. I experiment to ensure that it's working. Ref:
[ENG] https://medium.com/@srihamat.a/facebook-libra-on-windows-10-399aee3227ec
[TH] https://medium.com/@srihamat.a/facebook-libra-on-windows-14446bacfb62

I hope I can share my result to another people as well.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes, I did.

## Test Plan

I executed it on my Windows subsystem linux, mac os and ubuntu and it's working.

## Related PRs

https://github.com/libra/website/pull/49

### CODE REVIEW

**Comment by srihamat** [comment]
@bmwill 
Hi Brandon,

As you added circleci build file and config to required to pass circleci build before merge.
I try build my branch on circleci then found out lint error on file not related to my changed.
1. lint: common/logger/src/http_local_slog_drain.rs
2. cmake: rmat.cc:264:1: fatal error: error writing to /tmp/cceR2BPG.s: Cannot allocate memory

Please help to suggest the next step to push my changed into main branch.
Or please let me know if I can help you on something need to make circleci build work.

**Comment by bmwill** [comment]
Hey @srihamat thanks for helping get the dev_setup.sh script to work for Windows users. We're still working on getting to a point where we can directly accept PRs on github, but I'll make sure this change gets picked up.

As for the errors you ran into (which you don't need to worry about addressing):
1. I'd probably need more detailed output from the linter to be able to understand what the issue is, though we were seeing a lint issue with the logger a couple of days ago, though that should have been fixed in a6fa752.
2. Our whole build process requires a significant amount of memory so there's a chance that if you tried to run CI on your own personal fork with the free version of CircleCi that the machines they give you just don't have enough memory to be able to successfully complete the build and would explain the "Cannot allocate memory" error.

**Comment by srihamat** [comment]
@bmwill 
Hi Brandon,

Many thanks for response. 
Clearly understand that it's not required my action on this PR at the moment. 

Please let me know if I can help on something.

**Comment by bmwill** [comment]
Merged as 43d52f113 ([dev-setup] fix protoc url to support linux subsystem for windows, 2019-07-21)

**Pull request closed without merging**
