### PR TITLE
[state sync] use synced_state as known version

### LINKED ISSUE #1720: [state sync][Bug] stuck when we have more than one chunk to retrieve
After https://github.com/libra/libra/pull/1627,  we differentiate the committed state and synced state but we didn't change the synchronizer API to reflect it and it's still using committed state as known version.

If we have more than one chunk to retrieve, synchornizer will keep asking the same chunk forever because storage will not advance the committed state until sync finishes.

### PR DESCRIPTION
**Pull request by zekun000**
## Motivation

Fix #1720 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Y

## Test Plan

Existing tests.

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by aching** [comment]
Would it be possible to write a unit test to verify it returns the expected version from the committed state rather than the highest ledger info version?

**Comment by zekun000** [comment]
@aching since we're rewriting the synchronizer, we can probably add tests for the new version.

**Comment by lightmark** [comment]
This should be caught by a simple sync unit test. Hoping you guys have a better test coverage for the new state_sync design. @dmitri-perelman

**Comment by dmitri-perelman** [comment]
Hey, just wanted to make it clear that there are currently no redesign plans for state synchronizer, at least no plans coming from the Consensus team.
There are specific issues we're trying to address with https://github.com/libra/libra/pull/1743 as a prerequisite for the cross-epoch verification in state synchronizer: like keeping a more elaborate state with explicit versioning for different pieces, active re-syncing with local storage, and some fixes to the peer manager logic. These changes will come with unit testing. Rather than that the state synchronizer design remains the same :).

**Comment by andll** [comment]
+1 for making some test for it
Probably some smoke test that would sync more than one chunk?
I have a feeling that currently we solved problem that caused outage without following up with proper CI test

**Comment by lightmark** [comment]
@andll Yup. If nobody is going to do that I will try to do this later this week.

**Comment by phoenix-antigravity** [comment]
@lightmark: test handled by https://github.com/libra/libra/pull/1763

**Pull request closed without merging**
