### PR TITLE
Revert "[genesis][breaking] Integrate config gen w/ genesis discovery set"

### PR DESCRIPTION
**Pull request by bothra90**
This reverts commit f014b4ffd2052bf1241d56a2646dffa27208831c that was merged as a part of #2760 . The commit caused issues in full nodes, where we observed that the  execution hash on full nodes does not match the one on validator.

### CODE REVIEW

**Comment by andll** [comment]
Looks like you need to re-generate genesis.blob
@bors-libra delegate+ 

Also, before merging this PR, could you check that full nodes are working on ct?

**Comment by bothra90** [comment]
Cluster test results:
```
====json-report-begin===
{
  "metrics": [
    {
      "experiment": "all up",
      "metric": "submitted_txn",
      "value": 175570.0
    },
    {
      "experiment": "all up",
      "metric": "expired_txn",
      "value": 0.0
    },
    {
      "experiment": "all up",
      "metric": "avg_txns_per_block",
      "value": 69.78261131786807
    },
    {
      "experiment": "all up",
      "metric": "avg_tps",
      "value": 735.9495185305674
    },
    {
      "experiment": "all up",
      "metric": "avg_latency",
      "value": 1210.7615466949783
    }
  ],
  "text": "all up : 736 TPS, 1210.8 ms latency, no expired txns"
}
====json-report-end===
INFO 2020-03-16 21:46:03 testsuite/cluster-test/src/main.rs:226 Experiment Result: all up : 736 TPS, 1210.8 ms latency, no expired txns
```

@andll : Is the 736 tps number expected for the 30 node cluster test setup?

**Comment by andll** [comment]
Yes, TPS can be lower on full nodes cluster for now
We can merge this, if there is perf regression on 100 nodes, land blocking will let us know

**Comment by andll** [comment]
@bors-libra r=10
Raising priority since this mitigates SEV

**Comment by andll** [comment]
@bors-libra p=10 r=andll
Raising priority since this mitigates SEV

**Comment by bothra90** [comment]
Merging after rebase

@bors-libra r=andll p=10

**Comment by bothra90** [comment]
upstream changes keep getting in the way, so praying to god!

@bors-libra r=andll p=100

**Pull request closed without merging**
