### PR TITLE
fix LibraDB::get_epoch_ending_ledger_info()

### PR DESCRIPTION
**Pull request by msmouse**
## Motivation

Logic went off during refactoring.. and there was no test coverage.. :(

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Y
## Test Plan
Unit test.
## Related PRs

#4511

### CODE REVIEW

**Comment by lightmark** [comment]
Nobody calls this function?

**Comment by zekun000** [comment]
state sync calls this function but obviously we don't have any real test coverage. I found this by writing a smoke test in https://github.com/libra/libra/pull/5366

**Pull request closed without merging**
