### PR TITLE
make clippy happy

### PR DESCRIPTION
**Pull request by kigawas**
fixed some minor clippy warns

### CODE REVIEW

**Comment by kigawas** [comment]
should've signed it at the first pr

**Comment by ericnakagawa** [comment]
@kigawas Thanks for the interest in this project. Can you sign the Individual CLA and mail to cla@libra.org? Thank you.

**Comment by kigawas** [comment]
Already sent via to.be.impressive@gmail.com around several months ago
Do I need to send again?

**Comment by ericnakagawa** [comment]
Your CLA has been recorded. Thanks for your contribution @kigawas.

**Pull request merged**
