### PR TITLE
[move-prover] Attempt to verify Vector::reverse.

### PR DESCRIPTION
**Pull request by kkmc**
Initial attempt / ramp up exercise to verify vector reverse's loop invariant.
Verified the reverse function when the argument is not a reference, but unable to verify the loop invariant when the argument has type &mut vector.

When references are used, I can prove the following at every loop iteration:

```
assert all(0..len, |k| old_v<Element>[k] == v[k])
```

Which means that the old array is always equal to the current array.
Also, placing the assertion that the elements are swapped
right after Vector::swap fails when v is a mutable reference (&mut):

```
assert old_v<Element>[front_index] == v[back_index];
```

## Motivation

First attempt at verifying `verify_reverse` / `Vector::reverse` using a loop invariant.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

Run the following to verify `verify_reverse` (and other functions in the file):
```
cargo run -- --verbose debug ../stdlib/modules/Vector.move tests/sources/functional/verify_vector.move
```

## Related PRs

None.

### CODE REVIEW

**Comment by kkmc** [comment]
@junkil-park @shazqadeer
Can someone change the reviewer for me? Thanks.

**Comment by shazqadeer** [comment]
Was @andll added to the list of reviewers for this PR by mistake?

**Comment by kkmc** [comment]
> Was @andll added to the list of reviewers for this PR by mistake?

I was unable to choose reviewers at the time of the PR, so the bot choose a random one for me.

@junkil-park I just updated the file to have both versions.

**Comment by junkil-park** [comment]
@kkmc, Shaz just submitted a PR (https://github.com/libra/libra/pull/4324) to fix the issue in the mutable parameters. Could you try verifying the original again once it's landed?

**Comment by junkil-park** [comment]
@kkmc, thank you for your work on this!! Since the loop invariants for `Vector::reverse` were landed via https://github.com/libra/libra/pull/4613. I will close this PR.

**Pull request closed without merging**
