### PR TITLE
[logging] add all log levels to structured logging

### PR DESCRIPTION
**Pull request by gregnazario**
Text logs are automatically converted to structured logs, and we didn't
log the levels.  This now logs the log levels for all logs, and adds the
ability to have more fine grained levels for structured logs in general.

### CODE REVIEW

**Comment by andll** [comment]
There is some inconsistency here in terms of naming - the field on log entry is called 'severity', but some other things are called level(like LogLevel enum and method to set level)
We should probably converge on single name

**Comment by gregnazario** [comment]
> There is some inconsistency here in terms of naming - the field on log entry is called 'severity', but some other things are called level(like LogLevel enum and method to set level)
> We should probably converge on single name

Yeah, I wanted to move it just to `level` as that's what's fairly common among logging.  Just need to talk to @sherry-x and make sure we don't have anything setup as a log scan on severity right now

**Comment by gregnazario** [comment]
> There is some inconsistency here in terms of naming - the field on log entry is called 'severity', but some other things are called level(like LogLevel enum and method to set level)
> We should probably converge on single name

Discussed with Sherry.  Will followup here https://github.com/libra/libra/issues/5484 after this has been deployed

**Pull request closed without merging**
