### PR TITLE
removing unused deps

### PR DESCRIPTION
**Pull request by mimoo**

### CODE REVIEW

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  R radix_trie 0.2.1 (direct third-party, crates.io)
    * (old features: [none])
  R endian-type 0.1.2 (transitive third-party, crates.io)
    * (old features: [none])
  R nibble_vec 0.1.0 (transitive third-party, crates.io)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  R radix_trie 0.2.1 (direct third-party, crates.io)
    * (old features: [none])
  R endian-type 0.1.2 (transitive third-party, crates.io)
    * (old features: [none])
  R nibble_vec 0.1.0 (transitive third-party, crates.io)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  R difference 2.0.0 (direct third-party, crates.io)
    * (old features: default)
  R radix_trie 0.2.1 (direct third-party, crates.io)
    * (old features: [none])
  R endian-type 0.1.2 (transitive third-party, crates.io)
    * (old features: [none])
  R nibble_vec 0.1.0 (transitive third-party, crates.io)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  R radix_trie 0.2.1 (direct third-party, crates.io)
    * (old features: [none])
  R endian-type 0.1.2 (transitive third-party, crates.io)
    * (old features: [none])
  R nibble_vec 0.1.0 (transitive third-party, crates.io)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  R difference 2.0.0 (direct third-party, crates.io)
    * (old features: default)
  R radix_trie 0.2.1 (direct third-party, crates.io)
    * (old features: [none])
  R endian-type 0.1.2 (transitive third-party, crates.io)
    * (old features: [none])
  R nibble_vec 0.1.0 (transitive third-party, crates.io)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  R radix_trie 0.2.1 (direct third-party, crates.io)
    * (old features: [none])
  R endian-type 0.1.2 (transitive third-party, crates.io)
    * (old features: [none])
  R nibble_vec 0.1.0 (transitive third-party, crates.io)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  R radix_trie 0.2.1 (direct third-party, crates.io)
    * (old features: [none])
  R endian-type 0.1.2 (transitive third-party, crates.io)
    * (old features: [none])
  R nibble_vec 0.1.0 (transitive third-party, crates.io)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  R difference 2.0.0 (direct third-party, crates.io)
    * (old features: default)
  R radix_trie 0.2.1 (direct third-party, crates.io)
    * (old features: [none])
  R endian-type 0.1.2 (transitive third-party, crates.io)
    * (old features: [none])
  R nibble_vec 0.1.0 (transitive third-party, crates.io)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  R radix_trie 0.2.1 (direct third-party, crates.io)
    * (old features: [none])
  R endian-type 0.1.2 (transitive third-party, crates.io)
    * (old features: [none])
  R nibble_vec 0.1.0 (transitive third-party, crates.io)
    * (old features: [none])
```

**Review by metajack — APPROVED** [review]
Excellent!

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  R radix_trie 0.2.1 (direct third-party, crates.io)
    * (old features: [none])
  R endian-type 0.1.2 (transitive third-party, crates.io)
    * (old features: [none])
  R nibble_vec 0.1.0 (transitive third-party, crates.io)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  R radix_trie 0.2.1 (direct third-party, crates.io)
    * (old features: [none])
  R endian-type 0.1.2 (transitive third-party, crates.io)
    * (old features: [none])
  R nibble_vec 0.1.0 (transitive third-party, crates.io)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  R radix_trie 0.2.1 (direct third-party, crates.io)
    * (old features: [none])
  R endian-type 0.1.2 (transitive third-party, crates.io)
    * (old features: [none])
  R nibble_vec 0.1.0 (transitive third-party, crates.io)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  R radix_trie 0.2.1 (direct third-party, crates.io)
    * (old features: [none])
  R endian-type 0.1.2 (transitive third-party, crates.io)
    * (old features: [none])
  R nibble_vec 0.1.0 (transitive third-party, crates.io)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  R radix_trie 0.2.1 (direct third-party, crates.io)
    * (old features: [none])
  R endian-type 0.1.2 (transitive third-party, crates.io)
    * (old features: [none])
  R nibble_vec 0.1.0 (transitive third-party, crates.io)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  R radix_trie 0.2.1 (direct third-party, crates.io)
    * (old features: [none])
  R endian-type 0.1.2 (transitive third-party, crates.io)
    * (old features: [none])
  R nibble_vec 0.1.0 (transitive third-party, crates.io)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  R radix_trie 0.2.1 (direct third-party, crates.io)
    * (old features: [none])
  R endian-type 0.1.2 (transitive third-party, crates.io)
    * (old features: [none])
  R nibble_vec 0.1.0 (transitive third-party, crates.io)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  R radix_trie 0.2.1 (direct third-party, crates.io)
    * (old features: [none])
  R endian-type 0.1.2 (transitive third-party, crates.io)
    * (old features: [none])
  R nibble_vec 0.1.0 (transitive third-party, crates.io)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  R radix_trie 0.2.1 (direct third-party, crates.io)
    * (old features: [none])
  R endian-type 0.1.2 (transitive third-party, crates.io)
    * (old features: [none])
  R nibble_vec 0.1.0 (transitive third-party, crates.io)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  R radix_trie 0.2.1 (direct third-party, crates.io)
    * (old features: [none])
  R endian-type 0.1.2 (transitive third-party, crates.io)
    * (old features: [none])
  R nibble_vec 0.1.0 (transitive third-party, crates.io)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  R radix_trie 0.2.1 (direct third-party, crates.io)
    * (old features: [none])
  R endian-type 0.1.2 (transitive third-party, crates.io)
    * (old features: [none])
  R nibble_vec 0.1.0 (transitive third-party, crates.io)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  R radix_trie 0.2.1 (direct third-party, crates.io)
    * (old features: [none])
  R endian-type 0.1.2 (transitive third-party, crates.io)
    * (old features: [none])
  R nibble_vec 0.1.0 (transitive third-party, crates.io)
    * (old features: [none])
```

**Pull request closed without merging**
