### PR TITLE
[stdlib] Fix typo from 'initalize_tc_account' to 'initialize_tc_account'

### PR DESCRIPTION
**Pull request by jolestar**
## Motivation

Fix typo from 'initalize_tc_account' to 'initialize_tc_account'

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Unit test

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by jolestar** [comment]
language/ir-testsuite/tests/block/block_prologue.mvir  execute fail, change EventKey([14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 85, 12, 24])  to EventKey([16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 85, 12, 24]) will work, but I do not know why.

**Comment by jolestar** [comment]
Wait for #4036 merge first.

**Comment by sblackshear** [comment]
Thank you for fixing this!

However, the function in question was removed by https://github.com/libra/libra/commit/e66e1fc5c9d61a5aace906ec01b60429beb6b485, so we may not need this anymore.

**Comment by jolestar** [comment]
@sblackshear ok, I close this.

**Pull request closed without merging**
