### PR TITLE
[libra_block] remove unused fields, add round to NewBlockEvent

### PR DESCRIPTION
**Pull request by zekun000**
## Motivation

Remove unused fields, add round to NewBlockEvent which'll be used for the leader reputation.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Y
## Test Plan

cargo run -p stdlib, cargo test -p testsuite

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by zekun000** [comment]
let me know if any of you feel those fields might be useful

**Comment by zekun000** [comment]
I was hoping some conversation in the pr like we actually need xx field.
>>> why we're removing these fields. 
unused
>>> Why round > height. 
we need round for leader reputation, but I didn't cover why round > height.
>>> Why remove proposer.
unused

**Comment by dmitri-perelman** [comment]
As far as I understand, the PR introduces the following changes:
1. Add a `round` field to the `BlockMetadata` core type struct.
2. Replace `height` with `round` for `NewBlockEvent`.
3. Remove the `id` and `proposer` fields from `BlockMetadata` resource.

@zekun000 Could you please remind the high-level flow with the structs above? (who is using `NewBlockEvent`? how is the `BlockMetadata` resource created and how is it used?)

**Comment by zekun000** [comment]
@dmitri-perelman thanks for summarizing the changes!

MetadataBackend would query the libradb api get_events_by_event_key for `NewBlockEvent`, on-chain `BlockMetadata` resource is only used to hold the EventHandle and height which is used for genesis initialization.

I don't see any use case of the on-chain BlockMetadata resource so I delete those fields, also delete height from `NewBlockEvent` because I believe the seq_num of event serves the same purpose.

**Comment by davidiw** [comment]
I think it might be good to add to the BlockMetadata the purpose of it. Right now the only obvious use of it to me is keeping track of time. But if you look at the libra-types versus the move-type they aren't even compatible with each other. We might as well call this libra-time-service and get rid of everything that doesn't have to do with time. Thoughts?

@runtian-zhou @sblackshear

**Comment by sblackshear** [comment]
Sorry to be late in replying to this. Time is definitely the main use-case.

> delete height from NewBlockEvent because I believe the seq_num of event serves the same purpose.

This is a good idea--we can reimplement `height()` to read from there

> original motivation behind these fields?

- `proposer` is used to sanity-check timestamps. They need to increase unless it's one of the special post-reconfiguration empty block (identified by proposer = `0x0`)
- Not sure about `id`, but Runtian may know
- Is consensus using `previous_block_votes` (Move code doesn't need that.

>  Right now the only obvious use of it to me is keeping track of time.

Time + emitting new block events are definitely the main use-cases.

> But if you look at the libra-types versus the move-type they aren't even compatible with each other. 

 :(. Man, we really need an automated way to check that libra-types and Move code are in sync. I will bring this up at our team meeting.

**Pull request closed without merging**
