### PR TITLE
[CI] add LBT trigger

### PR DESCRIPTION
**Pull request by sausagee**
## Motivation
Create a trigger condition for commits that involve only trivial or
unrelated changes to skip land-blocking test.

## Test Plan
Test standalone trigger
- Testcase 1 - random change in move-prover won't trigger LBT
```
[youngyl@youngyl-mbp:libra canary]$ git show HEAD
commit 81c25224f83498d2e9f048cb002a65ce9c044f0f (HEAD -> canary)
Author: Young Yang Liauw <youngyl@fb.com>
Date:   Tue Mar 17 13:10:50 2020 -0700

    test1

diff --git a/language/move-prover/src/main.rs b/language/move-prover/src/main.rs
index f8b4aa89..4e3b3946 100644
--- a/language/move-prover/src/main.rs
+++ b/language/move-prover/src/main.rs
@@ -1,6 +1,7 @@
 // Copyright (c) The Libra Core Contributors
 // SPDX-License-Identifier: Apache-2.0

+// blah
 #![forbid(unsafe_code)]

 use codespan_reporting::term::termcolor::{ColorChoice, StandardStream};
[youngyl@youngyl-mbp:libra canary]$ .circleci/should_run_lbt.sh
Will skip land-blocking test.
```
- Testcase 2 - random change in network should trigger LBT
```
[youngyl@youngyl-mbp:libra canary]$ git show HEAD
commit 0a8a0b5841bdb135ad08685d1da7bef75218e638 (HEAD -> canary)
Author: Young Yang Liauw <youngyl@fb.com>
Date:   Tue Mar 17 13:13:02 2020 -0700

    test2

diff --git a/network/src/lib.rs b/network/src/lib.rs
index 7b7a81ca..411dc23f 100644
--- a/network/src/lib.rs
+++ b/network/src/lib.rs
@@ -1,6 +1,8 @@
 // Copyright (c) The Libra Core Contributors
 // SPDX-License-Identifier: Apache-2.0

+// doh
+//
 // <Black magic>
 // Increase recursion limit to allow for use of select! macro.
 #![recursion_limit = "1024"]
[youngyl@youngyl-mbp:libra canary]$ .circleci/should_run_lbt.sh
Found at least one file not in ignore-list: network/src/lib.rs
Will run land-blocking test.
```
- Testcase 3 - combining 1 and 2 above will trigger LBT.
```
[youngyl@youngyl-mbp:libra canary]$ git show HEAD
commit 97ae9cbe66c9020eec03c9fb540fa2fb32406de2 (HEAD -> canary)
Author: Young Yang Liauw <youngyl@fb.com>
Date:   Tue Mar 17 13:10:50 2020 -0700

    test3

diff --git a/language/move-prover/src/main.rs b/language/move-prover/src/main.rs
index f8b4aa89..4e3b3946 100644
--- a/language/move-prover/src/main.rs
+++ b/language/move-prover/src/main.rs
@@ -1,6 +1,7 @@
 // Copyright (c) The Libra Core Contributors
 // SPDX-License-Identifier: Apache-2.0

+// blah
 #![forbid(unsafe_code)]

 use codespan_reporting::term::termcolor::{ColorChoice, StandardStream};
diff --git a/network/src/lib.rs b/network/src/lib.rs
index 7b7a81ca..dcabf2bf 100644
--- a/network/src/lib.rs
+++ b/network/src/lib.rs
@@ -1,6 +1,7 @@
 // Copyright (c) The Libra Core Contributors
 // SPDX-License-Identifier: Apache-2.0

+// blah
 // <Black magic>
 // Increase recursion limit to allow for use of select! macro.
 #![recursion_limit = "1024"]
[youngyl@youngyl-mbp:libra canary]$ .circleci/should_run_lbt.sh
Found at least one file not in ignore-list: network/src/lib.rs
Will run land-blocking test.
```

Test integration with LBT
- Testcase 1 - random change in move-prover on top of this PR
```
[youngyl@youngyl-mbp:libra canary]$ git log -1
commit 3037cd2eefadca63e7326b67be165d39cb84276e (HEAD -> canary, origin/canary)
Author: Young Yang Liauw <youngyl@fb.com>
Date:   Tue Mar 17 20:45:01 2020 -0700

    test1
[youngyl@youngyl-mbp:libra canary]$ git diff --name-only origin/master..HEAD
.circleci/ignore_paths.json
.circleci/should_run_lbt.sh
.github/workflows/land-blocking.yml
language/move-prover/src/lib.rs
[youngyl@youngyl-mbp:libra canary]$
```
Verify LBT is skipped.
image

- Testcase 2 - random change in network on top of Testcase 1 above
```
[youngyl@youngyl-mbp:libra canary]$ git log -1
commit 8fa0c482167e69e6ace81b557949191ce0f4ef45 (HEAD -> canary, origin/canary)
Author: Young Yang Liauw <youngyl@fb.com>
Date:   Wed Mar 18 14:50:13 2020 -0700

    test2
[youngyl@youngyl-mbp:libra canary]$ git diff --name-only origin/master..HEAD
.circleci/ignore_paths.json
.circleci/should_run_lbt.sh
.github/workflows/land-blocking.yml
language/move-prover/src/lib.rs
network/src/lib.rs
[youngyl@youngyl-mbp:libra canary]$
```
Verify LBT is triggered.
image

### CODE REVIEW

**Comment by sausagee** [comment]
The next step is to integrate this trigger check into GH Actions workflow and CircleCI if needed.

Would love to get feedback on this before integrating this further.

**Comment by ankushagarwal** [comment]
Bash script went over my head! 

LGTM

**Comment by sausagee** [comment]
> Bash script went over my head!
> 
> LGTM

Yeah, the bash script was planned as the single source truth when sharing between Circle and GHAR workflows.

**Comment by sausagee** [comment]
@bors-libra r-

Homu queue is backed up due to infra issue in cluster test.  There are 7 jobs stuck in the queue.  Among them is a PR we need for making testnet release.  I am going to land this PR at another time.

**Pull request closed without merging**
