### PR TITLE
[json-rpc] add get_network_status endpoint

### PR DESCRIPTION
**Pull request by christinacelee**
## Summary

Adding `get_network_status` that returns the number of peers the node is connected to, to gauge network health
Refactored some test code accordingly

## Test Plan

Existing/new tests

### CODE REVIEW

**Comment by thefallentree** [comment]
why not just do this in get_metadata API ? 

Also, on fullnode isn't there only going to be 1 ?

**Comment by christinacelee** [comment]
> why not just do this in get_metadata API ?
> 
> Also, on fullnode isn't there only going to be 1 ?

Get metadata now supports querying for past blocks, so we can't add network connectivity info there

**Comment by christinacelee** [comment]
Are there risks involved with exposing this info to the internet? Coinbase, for example, supports querying a node for network status to check network health

**Comment by thefallentree** [comment]
I don't think json-rpc is the right approach though, typically healcheck are handled differently, maybe by a /health handler directly, returning an json or just text, we should consider doing that.


or. just expose some prometheus metrics under /metrics, which are all more extensible than this.

**Comment by davidiw** [comment]
Interesting, not sure why this got re-opened.

We actually had the debug interface ported to json rpc but in its own service.

Closing PR, it seems good to me. It might be good in the future to reference partner services that we're replicating to better motivate these type of PRs.

Thanks for humoring us with answers to our questions :).

**Comment by thefallentree** [comment]
I'm not sure what you meant, but if you don't want to discuss anymore what can I say.

**Pull request closed without merging**
