### PR TITLE
[Language] Fix MIRAI warning for unnecessary parentheses

### PR DESCRIPTION
**Pull request by wqfish**
https://github.com/libra/libra/pull/2382#issuecomment-580530505

### CODE REVIEW

**Comment by mimoo** [comment]
actually, I would recommend against this change, as the parenthesis make the intention clearer. 

@hermanventer  is this really a MIRAI warning or was this a normal compiler warning?

**Comment by dariorussi** [comment]
this is looking a bit too much as a "taste change" or maybe I am not following the risks associated with that.
Also adding people that have worked in the file to make sure they are aware of this

**Comment by hermanventer** [comment]
The parenthesis warning comes from the current nightly rust compiler. It is certainly a matter of taste, but if this is what the Rust community as a whole wants to enforce, it seems a bit selfish to not go along with it.

**Pull request closed without merging**
