### PR TITLE
[Storage] Move state store backup code to BackupHandler

### PR DESCRIPTION
**Pull request by wqfish**
## Motivation

Since we have the backup handler, we put all the backup related code to the same place.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

No?

## Test Plan

Just move code.

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by zamsden** [comment]
build failing..

**Comment by wqfish** [comment]
> build failing..

It’s a flaky test.

**Pull request closed without merging**
