### PR TITLE
[resource-viewer] Fix resource viewer to use StructTag

### PR DESCRIPTION
**Pull request by runtian-zhou**
## Motivation

Resource viewer was once broken due to the refactor of FatType. This PR fixes the resource viewer.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes
## Test Plan

Tested both the genesis viewer via `cargo run -- -r` and cli with `q ar 0000000000000000000000000a550c18`.

### CODE REVIEW

**Comment by runtian-zhou** [comment]
1. mapping is indeed updated intensionally. Lots of information is removed due to the fact that StructTag is a lot light weight than FatStructType.
2. Sure! Lemme do that in a separate PR.

**Comment by vgao1996** [comment]
1. My bad. Misread and thought it was deleted.

Thanks for fixing this!

**Comment by dariorussi** [comment]
that's a pretty serious amount of red :)
thanks!

**Pull request closed without merging**
