### PR TITLE
[cluster-test] add gas price non zero test

### PR DESCRIPTION
**Pull request by snakech**
## Motivation

Add new test with non zero gas price to see performance difference with gas price = 0

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

./scripts/cti -W zihao --pr 6179 --run bench -- --gas-price 1

```
====json-report-begin===
{
  "metrics": [
    {
      "experiment": "all up, gas price 1",
      "metric": "avg_txns_per_block",
      "value": 920.3313186813187
    },
    {
      "experiment": "all up, gas price 1",
      "metric": "submitted_txn",
      "value": 150360.0
    },
    {
      "experiment": "all up, gas price 1",
      "metric": "expired_txn",
      "value": 0.0
    },
    {
      "experiment": "all up, gas price 1",
      "metric": "avg_tps",
      "value": 626.0
    },
    {
      "experiment": "all up, gas price 1",
      "metric": "avg_latency",
      "value": 7272.0
    },
    {
      "experiment": "all up, gas price 1",
      "metric": "p99_latency",
      "value": 8800.0
    }
  ],
  "text": "all up, gas price 1 : 626 TPS, 7272 ms latency, 8800 ms p99 latency, no expired txns"
}
====json-report-end===
2020-09-24T20:15:28.379671Z [main] INFO testsuite/cluster-test/src/main.rs:230 Experiment Result: all up, gas price 1 : 626 TPS, 7272 ms latency, 8800 ms p99 latency, no expired txns
```

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/libra/developers.libra.org, and link to your PR here.)

### CODE REVIEW

**Comment by snakech** [comment]
I will add it into nightly run by a separate pr

**Review by andll — APPROVED** [review]
Looks nice!

**Pull request closed without merging**
