### PR TITLE
[Storage] SchemaDB: remove use of set_db_log_dir

### PR DESCRIPTION
**Pull request by wqfish**
https://github.com/rust-rocksdb/rust-rocksdb currently does not support this right now. I don't feel it is strictly necessary, as having the `LOG` files would be okay, maybe even better for keeping track of what has happened.

### CODE REVIEW

**Comment by thefallentree** [comment]
Well that will overwrite the log file in the existing DB

Yucong Sun, Libra PE
________________________________

**Comment by wqfish** [comment]
> Well that will overwrite the log file in the existing DB

AFAICT the existing log file gets renamed, not overwritten.

**Pull request closed without merging**
