### PR TITLE
rust: update to 1.63.0

### PR DESCRIPTION
**Pull request by jsladerman**
Code changes are mostly lint-related, determined using `cargo x lint && cargo xfmt && cargo xclippy --all-targets`

One flaky unit test became flakier post-upgrade, so cherry-picked this #8870 which addressed and fixed the same issue

### CODE REVIEW

**Comment by jsladerman** [comment]
/canary (lint should pass now, still need to fix failing unit test)

**Comment by jsladerman** [comment]
/canary (did some squashing and rebasing for cleanup)

**Review by KoushikGavini — APPROVED** [review]

**Pull request merged**
