### PR TITLE
Fix LICENSE Link

### PR DESCRIPTION
**Pull request by aDotInTheVoid**
## Motivation

The previous link lead to a 404 page, because the license file is `LICENSE` not `LICENSE.md`

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes. I have not yet signed the CLA, but I will.

## Test Plan

N/A

## Related PRs

None

### CODE REVIEW

**Comment by huitseeker** [comment]
Thanks for the contribution! This looks like a good change.

However, due to some CI changes put in place this past week, to get CI to run we would need you to push against your branch again, or to close this PR and make a new one. Going forward this won't be an issue, but unfortunately, we do not have a nice way to force CI to run for older PRs.

**Comment by aDotInTheVoid** [comment]
Pushed new change

**Comment by huitseeker** [comment]
@aDotInTheVoid  You'll want to rebase on latest master, I'm afraid you have a weird base commit in the current state of things.

**Comment by bob-wilson** [comment]
This was replaced by https://github.com/libra/libra/pull/973
Closing.

**Pull request closed without merging**
