### PR TITLE
Remove num_enum

### PR DESCRIPTION
**Pull request by metajack**
num_enum was only used by vm_error::StatusCode and had outdated
dependencies. There didn't seem to be any good, modern alternatives, so this
just replaces it with hand written TryFrom and From impls.

### CODE REVIEW

**Comment by tnowacki** [comment]
This made the written code significantly worse and led to bugs where there were items missing from the `TryFrom` implementation. 

Please ping owners of the files when removing stuff like this :) 

cc @tzakian who will work on some sort of replacement

**Comment by metajack** [comment]
I'm sorry this caused problems, and I'll reach out next time.

For my own curiosity, can you give me more context on why this led to bugs? Was it just that people added statuses and then ran into them triggering the Err("invalid status code") because they forgot to fill out the match statement?

**Comment by tnowacki** [comment]
> Was it just that people added statuses and then ran into them triggering the Err("invalid status code") because they forgot to fill out the match statement?

Correct. by its design you can't check for exhaustiveness there, and many people didn't know they had to do it (myself included) because it was previously autogenerated. d

**Pull request closed without merging**
