### PR TITLE
[crypto] renaming NamespaceKeys -> namespace::Keys

### PR DESCRIPTION
**Pull request by mimoo**
This PR applies four changes all related to the same issue: naming in crypto.

1. Use namespaces to differentiate different algorithm keys (`ed25519::Ed25519PublicKey` becomes `ed25519::PublicKey` (see rational below).
2. Prefix specific crypto traits with `T` to avoid name collisions (because people like to import `traits::*` and we can't do `use traits::* as _` in rust yet.
3. Rename private/public key into signing/verifying key (this gives a good indication as to what type of keys we're handling).
4. Rename multi ed25519 signing/verifying "key" into signing/verifying "keys".

The biggest change is obviously the use of namespaces to indicate what types of keys we are using.
The rational is that:

* from the point of view of the ed25519 library, a key is just a key
* from the point of view of the caller, rust provides namespace just for this

### CODE REVIEW

**Comment by mimoo** [comment]
@matbd @thefallentree I don't think this is a breaking change, hence I didn't tag the PR with "breaking". Tell me if I'm wrong : o

**Comment by mimoo** [comment]
see https://github.com/libra/libra/pull/3441

**Comment by kchalkias** [comment]
> This PR applies four changes all related to the same issue: naming in crypto.
> 
> 
> 
> 1. Use namespaces to differentiate different algorithm keys (`ed25519::Ed25519PublicKey` becomes `ed25519::PublicKey` (see rational below).
> 
> 2. Prefix specific crypto traits with `T` to avoid name collisions (because people like to import `traits::*` and we can't do `use traits::* as _` in rust yet.
> 
> 3. Rename private/public key into signing/verifying key (this gives a good indication as to what type of keys we're handling).
> 
> 4. Rename multi ed25519 signing/verifying "key" into signing/verifying "keys".
> 
> 
> 
> The biggest change is obviously the use of namespaces to indicate what types of keys we are using.
> 
> The rational is that:
> 
> 
> 
> * from the point of view of the ed25519 library, a key is just a key
> 
> * from the point of view of the caller, rust provides namespace just for this

IMO we shouldn’t change to signing and verifying key. How does this help in practice at this stage?

**Comment by mimoo** [comment]
@kchalkias I don't have a strong preference towards signing/private verifying/public, I did this change to avoid name collisions in @matbd 's tool.

**Pull request closed without merging**
