### PR TITLE
[dkr] remove reference to the old libra_e2e image

### PR DESCRIPTION
**Pull request by sausagee**
## Motivation
Following up 22bfee56f, the old image name libra_e2e is replaced with libra/validator.

## Test Plan
Passed LBT canary and release-dockerhub-publish in CI

### CODE REVIEW

**Review by davidiw — APPROVED** [review]
nice

**Review by rexhoffman — COMMENTED** [review]
This is dangerous without first changing all the dockerfiles / build.sh scripts.   If they are built, the entire section from # BEGIN DEALING WITH INCONSISTENT NAMING to # END should be deleted.

**Comment by sausagee** [comment]
Agreed. I will fold #6075 into this one.

**Review by davidiw — APPROVED** [review]
this is a fun chicken/egg situation....

**Comment by sausagee** [comment]
/land
Rebased and removed the cutover temp variables used in canary. landing now

**Pull request closed without merging**
