### PR TITLE
[dependency update] Bitvec 0.17.2

### PR DESCRIPTION
**Pull request by rexhoffman**
## Motivation

Latest deps before locking down (though this is test only).
Learning rust.

### Have you read the [Contributing Guidelines on pull requests]\

Yes

## Test Plan

build, test, lint

## Related PRs

https://github.com/libra/libra/pull/2587
Bitvec-0.17.2 which this extends, and will be closed by dependabot once this lands.

### CODE REVIEW

**Comment by metajack** [comment]
Looks good, but please squash before having bors run it so that the one commit compiles (the first commit of this won't).

**Comment by rexhoffman** [comment]
bors doesn't squash commits on it's own, good to know.

**Comment by metajack** [comment]
Bors will do the same as git's rebase with autosquash. i.e. if there is a proper fixup commit, it will squash it. That means the commit message must start with `fixup!` followed by a space then a pattern of the commit message you want to fix. See `git commit --fixup`.

**Comment by metajack** [comment]
You'll need to rebase as these cargo.lock changes fight the other ones. I ran into this as well :(

**Comment by rexhoffman** [comment]
Wonder why mechanically updated files like Cargo.lock don't put an empty line between lines, to prevent this tomfoolery.

**Pull request closed without merging**
