### PR TITLE
[dependencies] cargo update

### PR DESCRIPTION
**Pull request by rexhoffman**
## Motivation

Dependabot has been falling behind on update-able crates.   Bumping safe to update crates and updating the total number of prs dependabot can open.

### Have you read the [Contributing Guidelines on pull requests] 

Yes

## Test Plan

Standard build/test

## Related PRs

none

### CODE REVIEW

**Comment by rexhoffman** [comment]
Notice that mime-guess doesn't get a duplicate, one already existed, but maybe could have converged?

mime_guess 2.0.3 (1.8.8)

mime_guess: 1.8.7 -> 1.8.8
mime_guess: 2.0.1 -> 1.8.8

**Comment by rexhoffman** [comment]
@sausagee @metajack r+ please.   Thinking of bumping dependabot total open prs to 15 now -- make sure we don't miss updates in the future?

**Comment by metajack** [comment]
Note you can just write `r? @metajack` to ask for a review, and review-assign-bot will assign that person.

**Comment by rexhoffman** [comment]
any objections to the 15 max on prs?

**Comment by metajack** [comment]
> any objections to the 15 max on prs?

None here.

**Pull request closed without merging**
