### PR TITLE
[config-builder] prepare for dynamic configs in testnets

### PR DESCRIPTION
**Pull request by davidiw**
- Rename the binary libra-config to config-builder for consistency
- Add a few flags to config-builder so that it can produce self-contained configs for testnets

### CODE REVIEW

**Comment by opsguy** [comment]
I'm assuming this fixes https://github.com/libra/libra/issues/1853 ? @bmwill

**Comment by bmwill** [comment]
@opsguy Yeah it would fix that issue

**Comment by opsguy** [comment]
no whammy no whammy no whammy no whammy no whammy

**Pull request closed without merging**
