### PR TITLE
[move-stdlib] Minor fix in the comments of the transaction scripts

### PR DESCRIPTION
**Pull request by junkil-park**
- The document generator expects `Script::...` to be the qualified names of the scripts.
- This PR corrects some typos in the comments of the scripts, replacing `Scripts::` with `Script::`.

## Motivation

To correct some typos in the comments of the scripts

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

yes

## Test Plan

cargo test

### CODE REVIEW

**Review by wrwg — APPROVED** [review]
Great to see this fixed!

**Review by tzakian — APPROVED** [review]

**Pull request merged**
