### PR TITLE
[gk] add code freeze gate keepers

### PR DESCRIPTION
**Pull request by sausagee**
This is it.  For tomorrow 10/8.

### CODE REVIEW

**Review by davidiw — APPROVED** [review]
Oh boy, oh boy, has it really come to this?

**Review by dariorussi — APPROVED** [review]
seriously what's your problem?

**Comment by mimoo** [comment]
where are the gifs here?

**Comment by gregnazario** [comment]
> where are the gifs here?

Do you mean these?
GIF

**Comment by mimoo** [comment]
what is this magic!!!

**Review by aching — APPROVED** [review]
Here we go!

**Pull request closed without merging**
