### PR TITLE
[cluster test] support network latency in bench

### PR DESCRIPTION
**Pull request by zekun000**
## Motivation

per @aching request, want to test scenarios with latencies.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Y

## Test Plan

not sure

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by ankushagarwal** [comment]
I'm not sure if this is useful. For example in the case of N validators and N fullnodes, this injects a latency L ms into every outgoing packet from each of the fullnodes (because `self.up_instances` is a list of fullnodes to which we send the txns).

Assuming the latency b/w 2 instances by default is 1ms, after this 
* latency b/w any given pair of validators will be 1ms
* latency b/w a validator and its corresponding fullnode will be L+1 ms
* latency b/w a fullnode and cluster-test host will be L+1 ms

And I don't think this is a useful scenario.

Maybe it'll help if you explain what is the overall network setup b/w fullnodes and validators you're trying to emulate.

Also, `NetworkDelay` will be deprecated soon because it refers to our old static setup on ECS.

**Comment by zekun000** [comment]
@ankushagarwal hmm, seems I misunderstand the setup, what I want to test is latency injected between all validators.

**Comment by ankushagarwal** [comment]
So we already have `performance_benchmark_three_region_simulation` which does latency injection - https://github.com/libra/libra/blob/master/testsuite/cluster-test/src/experiments/performance_benchmark_three_region_simulation.rs

It clusters validators into three sets(simulating 3 regions) and introduces (hardcoded) latency b/w pairs of sets. Eg: latency b/w any validator in set 1 and any validator in set 2 will be 80ms and latency b/w any two validators in set 1 is 1ms.

**Comment by davidiw** [comment]
Without looking at the code, I thought @aching's intent was to evaluate effective latency between two nodes inclusive of network setup, message sent, and message received. I'm not entirely certain that is possible without us extending the ping in networking to also print out or structurally log these times. Perhaps there are others?

**Comment by zekun000** [comment]
@ankushagarwal I'm aware of the 3 region simulation but it doesn't provide options to stop % of nodes.

**Comment by andll** [comment]
I think if @zekun000 and @aching thinks having this knob in experiment is needed we should have it :)
I have two comments
1) Can we rename delay to net_delay?
2) Can you add deactivation of those network effects to the end of experiment?

**Comment by ankushagarwal** [comment]
Right now the cluster-test codebase is going through a lot of churn where we are phasing in the Kubernetes setup and phasing out the old ECS setup. Everything in the `effects/` directory is being deprecated, so I would not generally recommend adding 

If we want to correctly add network delay to validators in this experiment, you would need logic similar to `performance_benchmark_three_region_simulation.rs` where for each of the validators you would need to add network delay to an explicit list of other validators(This is because we don't want network delay b/w a validator and its corresponding full node). Particularly take a look at the `add_network_delay_k8s` function which takes an Instance and a configuration which specifies the network delay to add to the Instance

**Comment by zekun000** [comment]
We can do it later after the migration settled down, I'll just close this one.

**Pull request closed without merging**
