### PR TITLE
Update to latest stable rust

### PR DESCRIPTION
**Pull request by thefallentree**

### CODE REVIEW

**Comment by bmwill** [comment]
Yeah we had decided to stick around 1.39 for a bit since we don't have any need to move to 1.40. Though I don't have any concerns for doing a bump, of course you'll have to fix the new lints that are introduced in 1.40 as Jack mentioned.

**Comment by thefallentree** [comment]
apparently clippy start to detect redundant clones and in our code base there are *a lot*, so what  do you guys think we should do?  should we globally disable this warning or should we just fix all of it?

```
    modified:   client/libra_wallet/src/io_utils.rs
        modified:   common/channel/src/test.rs
        modified:   config/generate-keypair/src/lib.rs
        modified:   crypto/crypto/src/ed25519.rs
        modified:   crypto/crypto/src/hash.rs
        modified:   language/vm/src/file_format.rs
        modified:   network/noise/src/socket.rs
        modified:   storage/scratchpad/src/sparse_merkle/sparse_merkle_test.rs
        modified:   types/src/account_address.rs
        modified:   types/src/account_state_blob/account_state_blob_test.rs
        modified:   types/src/ledger_info.rs
        modified:   types/src/proof/unit_tests/proof_test.rs
        modified:   types/src/proptest_types.rs
        modified:   types/src/validator_verifier.rs
```

**Comment by thefallentree** [comment]
r=metajack

**Pull request closed without merging**
