### PR TITLE
cluster-test: enable using async AC client

### PR DESCRIPTION
**Pull request by bmwill**
This is the longer fix for cluster test. It ended up not being *as* bad as it initially looked.

### CODE REVIEW

**Comment by ankushagarwal** [comment]
This seems to be stuck somewhere in `run_single_experiment` function

```
cluster-test  --run performance_benchmark_nodes_down -- --num-nodes-down 0
Dec 19 16:17:40.691 INFO Discovered 100 peers in kush5 workspace
Dec 19 16:17:41.036 INFO Log tail thread started in 344 ms
Dec 19 16:17:41.036 INFO Will use kush tag for deployment
Dec 19 16:17:41.361 INFO Starting experiment all up
...
<no progress>
```

**Comment by bmwill** [comment]
Do you have any info on where it’s stuck like a stack trace or something?

**Pull request closed without merging**
