### PR TITLE
[dep] update futures/future-util

### PR DESCRIPTION
**Pull request by rexhoffman**
## Motivation

Handle the update of futures/futures-util.

### Have you read the [Contributing Guidelines on pull requests]

Yes

## Test Plan

CI

## Related PRs

https://github.com/libra/libra/pull/6679

### CODE REVIEW

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M futures 0.3.8 (direct third-party, crates.io)
    * version upgraded from 0.3.7
    * (unchanged features: alloc, async-await, default, executor, futures-executor, std)
  M futures-channel 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.7
    * (unchanged features: alloc, default, futures-sink, sink, std)
  M futures-core 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.7
    * (unchanged features: alloc, default, std)
  M futures-executor 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.7
    * (unchanged features: std)
  M futures-io 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.7
    * (unchanged features: std)
  M futures-sink 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.7
    * (unchanged features: alloc, default, std)
  M futures-task 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.7
    * (unchanged features: alloc, once_cell, std)
  M futures-util 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.7
    * (unchanged features: alloc, async-await, async-await-macro, channel, futures-channel, futures-io, futures-macro, futures-sink, io, memchr, proc-macro-hack, proc-macro-nested, sink, slab, std)

host packages:
  M futures-macro 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.7
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M futures 0.3.8 (direct third-party, crates.io) (other versions: 0.1.30)
    * version upgraded from 0.3.7
    * (unchanged features: alloc, async-await, default, executor, futures-executor, std)
  M futures-util 0.3.8 (direct third-party, crates.io)
    * version upgraded from 0.3.7
    * (unchanged features: alloc, async-await, async-await-macro, channel, default, futures-channel, futures-io, futures-macro, futures-sink, io, memchr, proc-macro-hack, proc-macro-nested, sink, slab, std)
  M futures-channel 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.7
    * (unchanged features: alloc, default, futures-sink, sink, std)
  M futures-core 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.7
    * (unchanged features: alloc, default, std)
  M futures-executor 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.7
    * (unchanged features: std)
  M futures-io 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.7
    * (unchanged features: default, std)
  M futures-sink 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.7
    * (unchanged features: alloc, default, std)
  M futures-task 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.7
    * (unchanged features: alloc, once_cell, std)

host packages:
  M futures-macro 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.7
    * (unchanged features: [none])
```

**Comment by rexhoffman** [comment]
Didn't drill in to the unused variables, seems that if they mattered a test would fail?

**Review by metajack — APPROVED** [review]

**Pull request merged**
