### PR TITLE
CRITICAL security vuln fixed

### PR DESCRIPTION
**Pull request by gazhayes**
I've discovered an alarming vulnerability, but fortunately there's a really simple fix so I've sent a pull request to address it.

In the current implementation, trusted 'validator nodes' are core to the security model. This means that _hard power_ is centralised around these few entities. The protocol itself _depends_ on these entities to (as the name suggests) validate the protocol. This means the protocol is whatever _they_ decide it is. These entities can change the rules _whenever_ they want. This means they can freeze your coins, take your coins, issue new coins, or really whatever they want - the sky is the limit.

This problem can easily be solved by using a permissionless system where the _hard power_ is _decentralised_ across a very large number of participants in such a way that making changes to the protocol is impossible without _near unanimous agreement_ by everyone involved. 

This pull request contains a patch to the existing codebase to resolve this issue. 

Edit: related issue: https://github.com/binance-chain/node-binary/issues/36

### CODE REVIEW

**Comment by tzarebczan** [comment]
ACK.

**Comment by tamasblummer** [comment]
Concept ACK
utACK

**Comment by DESIGNfromWITHIN** [comment]
Hahahaha Epic SIR!

**Comment by SamSamskies** [comment]
lgtm

**Comment by Kukks** [comment]
This seems to address a number of issues acknowledged on the whitepaper, great work!

**Comment by OverSoft** [comment]
ACK
This commit fixed all issues.

**Comment by tiero** [comment]
tACK

**Comment by mjamin** [comment]
Certainly a concept ACK

**Comment by Kixunil** [comment]
tACK

**Comment by brunocvcunha** [comment]
LGTM

**Comment by mandelmonkey** [comment]
ACK

**Comment by Kixunil** [comment]
Fixes #57

**Comment by pretyflaco** [comment]
ACK

**Comment by amanusk** [comment]
Fixed it for me!

**Comment by lorenzodisidoro** [comment]
Now ready to be released 🚀

**Comment by Isan-Rivkin** [comment]
LGTM

**Comment by charona** [comment]
ACK

**Comment by pajasevi** [comment]
ACK

**Comment by araa47** [comment]
ACK, just tried this out, solves all the problems for me , thanks @gazhayes

**Comment by irshadpc** [comment]
ACK

**Comment by Chococoin** [comment]
Your path has introduced a very undesirable bad behavior: It consumes too much energy. If it's bad for the planet is bad for the people.

**Comment by gcomte** [comment]
Awesome fix, now I can even fully validate myself.

Please merge ASAP.

**Comment by RTiK** [comment]
opensource was a mistake

**Comment by karanpatel863** [comment]
I don't think libra should referred as blockchain. What a disgrace !

**Comment by h4v0kr** [comment]
ACK

**Comment by karanpatel863** [comment]
I don't think libra should be referred as blockchain. They are fooling noobs like they always have been with that magic "blockchain" word. I am glad, US regulators asked them to pause their libra project today. If you are tired of centralised power, then No one should support this shitcoin project Decentralisation shall prevail ! Last but not least, EFF you libra and zuck !

**Comment by karanpatel863** [comment]
I don't think libra should be referred as blockchain. They are fooling noobs like they always have been with that magic "blockchain" word. I am glad, US regulators asked them to pause their libra project today. If you are tired of centralised power, then No one should support this shitcoin project. Decentralisation shall prevail ! Last but not least, EFF you libra and zuck !

**Comment by jmaurice** [comment]
Maintainer: It seems we have consensus for this PR, can you go ahead and it merge it? Thanks.

**Comment by katomm** [comment]
Did some rigorous tests and I can confirm the fix.

**Comment by fluffypony** [comment]
Tested this PR and it seems to work just fine. ACK.

**Comment by raymonddurk** [comment]
We should increase the node count from 100 to unlimited and reduce the fee from $10 million to $0. This is a nonprofit after all.

**Comment by Hilobrain** [comment]
utACK.

Does the job I think. There seems to be a consensus, please merge this request @maintainer.

**Comment by bioharz** [comment]
Libra and BTC were two different projects. Neither they are direct rivals, nor the solve the try to solve the same issue.
As a developer and a crypto friendly person (especially BTC), I expect from other developers and crypto friends to separate the purposes of both projects.
Thanks :-)

**Comment by 100trillionUSD** [comment]
ACK

**Comment by Chococoin** [comment]
> > Your path has introduced a very undesirable bad behavior: It consumes too much energy. If it's bad for the planet is bad for the people.
> 
> This has been fixed in the green update, by using excess hydro and solar power that would've otherwise be wasted.

Lol, this path is something like the joke "Let's fight the planet warming! Everybody to turn on the air conditioner at home and then let's open the windows to cool down the atmosphere."

**Comment by Kukks** [comment]
@Chococoin Go home, you're drunk
https://coinshares.co.uk/wp-content/uploads/2019/06/MiningWhitepaperJun2019FinalForeword.pdf

**Comment by janus333** [comment]
ACK
best patch in crypto^^

**Comment by Chococoin** [comment]
> @Chococoin Go home, you're drunk
> https://coinshares.co.uk/wp-content/uploads/2019/06/MiningWhitepaperJun2019FinalForeword.pdf

Dear, I'm at home already. Where are you? Your document is proof of what I'm saying. Hail to use drugs.

**Comment by inaltoasinistra** [comment]
ACK

**Comment by Chococoin** [comment]
> Libra and BTC were two different projects. Neither they are direct rivals, nor the solve the try to solve the same issue.
> As a developer and a crypto friendly person (especially BTC), I expect from other developers and crypto friends to separate the purposes of both projects.
> Thanks :-)

The funny stuff here is the original purpose of Bitcoin was lost in the road, while people are using Bitcoin, not to boycott fiat but to earn more fiat. That's so ridicule. Let's don't say that, currently, Bitcoin is a decentralized Ponzi scheme. 

Instead, Libra is going to fight against our owners (governments and its banks). Was it not the original will of Satoshi Nakamoto? Yea I know... ten years is enough time to forget.

**Comment by barrystyle** [comment]
wheres the bug exactly? sure they want to retain control.. noone is forced to use it

**Comment by gcrimi** [comment]
Concept ACK
Technical ACK
Fucking ACK

**Comment by karanpatel863** [comment]
LoL what are you even talking about? Have you checked their source code
it's not even a blockchain from dev point of view. We dont need a
centralised project to fight the centralised power above. The cure to this
is only Bitcoin and other DECENTRALISED alts. I guess when this shit hits
the fan, you'll be still slaving away your life working under the very same
bitcoiners hoping for a day off.

**Comment by AnthonyAkentiev** [comment]
Great! Waiting for this to be merged soon.

**Comment by giosakti** [comment]
`This branch has no conflicts with the base branch`

Let's go and get this merged then :+1:

**Comment by Chococoin** [comment]
> LoL what are you even talking about? Have you checked their source code it's not even a blockchain from dev point of view. We dont need a centralised project to fight the centralised power above. The cure to this is only Bitcoin and other DECENTRALISED alts. I guess when this shit hits the fan, you'll be still slaving away your life working under the very same bitcoiners hoping for a day off.

@karanpatel863 As I said before, consensus is vote. Don't you like it? Just don't use it! And from my point of view, if to generate the hash of the newer block they use the hash of the previous block, we are talking about a blockchain. Can you demonstrate that they don't use it here? The only shit here is going out from your mouth.

**Comment by gcrimi** [comment]
> Instead, Libra is going to fight against our owners (governments and its banks). Was it not the original will of Satoshi Nakamoto? Yea I know... ten years is enough time to forget.

Fight by financing it? Really?

"A basket of bank deposits and short-term government securities will be held in the Libra Reserve for every Libra that is created"

**Comment by karanpatel863** [comment]
@chococoin 
“Thoughts on Libra ‘Blockchain’” by Jameson Lopp https://link.medium.com/Cj0a4dUACX 
After reading this article STFU !

**Comment by rdymac** [comment]
Guys, please ignore the **Chococoin** guy. There is nothing worse than a statist boot licking Venezuelan.

**Comment by iulianpascalau** [comment]
Just wandering how could anyone review a 600k+ lines of code PR in a couple of hours?

**Comment by Kukks** [comment]
@iulianpascalau Any good coder with 6 months of experience can go through 600k lines of code thoroughly.

**Comment by Chococoin** [comment]
> > Instead, Libra is going to fight against our owners (governments and its banks). Was it not the original will of Satoshi Nakamoto? Yea I know... ten years is enough time to forget.
> 
> Fight by financing it? Really?
> 
> "A basket of bank deposits and short-term government securities will be held in the Libra Reserve for every Libra that is created"

@gazhayes It will make libra more desirable that Dollar or Euro. It's an optimum start. But the nicest part is if you sell something using Libra, for sure you'll be enabled to choose into an ocean full of stuff to spend your money. WITHOUT PAYING TAXES!!! Here is the battlefield against governments. Bitcoin in 10 years didn't make a real impact in this field.

**Comment by quantumcheddar** [comment]
reddit.com must be down, all i see are hippies

**Comment by Chococoin** [comment]
> Guys, please ignore the **Chococoin** guy. There is nothing worse than a statist boot licking Venezuelan.

Oh, the socialists are here!!! Welcome to the jungle baby and show your arguments. I know you haven't, but it's nice to remark that fact.

**Comment by leodido** [comment]
Concept ACK
Technical ACK

Merge ASAP please.

**Comment by Chococoin** [comment]
> @Chococoin
> “Thoughts on Libra ‘Blockchain’” by Jameson Lopp https://link.medium.com/Cj0a4dUACX
> After reading this article STFU !

Thank you @karanpatel863 I'll do. Instead, I recommend you the tweetstorm of Erik Voorhees https://twitter.com/ErikVoorhees/status/1141062947055079426.

**Comment by pajasevi** [comment]
@Chococoin 
> And from my point of view, if to generate the hash of the newer block they use the hash of the previous block, we are talking about a blockchain.

Lol, no. It's called linked list. Blockchain means "chain of blocks" but Libra itself admits it doesn't use any blocks.

**Comment by TechniumUnlimited** [comment]
> > LoL what are you even talking about? Have you checked their source code it's not even a blockchain from dev point of view. We dont need a centralised project to fight the centralised power above. The cure to this is only Bitcoin and other DECENTRALISED alts. I guess when this shit hits the fan, you'll be still slaving away your life working under the very same bitcoiners hoping for a day off.
> 
> @karanpatel863 As I said before, consensus is vote. Don't you like it? Just don't use it! And from my point of view, if to generate the hash of the newer block they use the hash of the previous block, we are talking about a blockchain. Can you demonstrate that they don't use it here? The only shit here is going out from your mouth.

They don't use a block chain. They use a 2-block comparator. The only block that is needed is the one that was just produced and no validation or connection to any blocks prior does it have.

**Comment by Chococoin** [comment]
> @Chococoin
> 
> > And from my point of view, if to generate the hash of the newer block they use the hash of the previous block, we are talking about a blockchain.
> 
> Lol, no. It's called linked list. Blockchain means "chain of blocks" but Libra itself admits it doesn't use any blocks.

Instead of blocks, it uses versions of Merkle trees and every version has a hash. I think it cannot make use of consecutive blocks to not restrict the number of transactions/seg. But in any case, every version of Merkle tree is auditable and immutable. A good version of the blockchain concept for me.

**Comment by Seccour** [comment]
Concept ACK

**Comment by alexdovzhanyn** [comment]
LGTM ASAP

**Comment by tBKwtWS** [comment]
ACK

**Comment by nvk** [comment]
ACK

**Comment by CandleHater** [comment]
ACK, please merge ASAP!

**Comment by hrishikeshio** [comment]
ACK

**Comment by eumartinez20** [comment]
ACK

**Comment by bioharz** [comment]
Such a toxic environment...

**Comment by jeffrade** [comment]
ACK. Thoroughly tested by millions for over 10 years. Think we're good to go 👍

**Comment by sbourdeauducq** [comment]
> Such a toxic environment...

https://www.youtube.com/watch?v=p-6WnQLHgow

**Comment by lilszi** [comment]
ARRR

**Comment by graylan0** [comment]
This repo itself is exposes major concerns of centralization (central authority FB runs it) .. That is one thing that still harms bitcoin(centralized repo mgnt) to this day. Facebook should build a true decentralized system or use one already in existence to have democratic vote upon the code and repo mgnt if they care about well designed and engineered decentralized p2p systems. If not the coin is not a true cryptocurrency. Just well promoted , centralized , digital money. https://medium.com/@VitalikButerin/the-meaning-of-decentralization-a0c92b76a274

**Comment by MiguelMedeiros** [comment]
ACK.

**Comment by emsheets** [comment]
This seemed to solve most of the issues for me.  Thanks.

**Comment by verretor** [comment]
Concept ACK.

**Comment by lucayepa** [comment]
utACK

**Comment by michielmulders** [comment]
I was here - just a future reminder to the decentralized version of myself owned by Facebook, enjoy life!

**Comment by AbelLykens** [comment]
> Dumb fucks

**Comment by benthecarman** [comment]
ACK

**Comment by benthecarman** [comment]
> Would prefer Monero

The privacy features are nice, however this implementation is compatible with Bitcoin which is much more secure, scalable, and socially scalable.

**Comment by faketoshinakamoto** [comment]
I even approve this.

**Comment by lsilvs** [comment]
Concept ACK

**Comment by MaxSan** [comment]
Concept ACK

**Comment by i-rme** [comment]
Another ACK here

**Comment by xmranon** [comment]
C'mon SurveillanceCoin - merge this PR.

**Comment by nolim1t** [comment]
ACK

**Comment by likewhoa** [comment]
Looks good no need for unit test in this.

**Comment by karozagorus** [comment]
ACK

**Comment by rgsnedds** [comment]
Beam me up.

**Comment by CypherPoet** [comment]
Works well on my machine.

**Comment by MrHash** [comment]
tested ACK

**Comment by ion9** [comment]
Looks good to me.

**Comment by nijynot** [comment]
utACK, ship it! 🚀

**Comment by LNAPI** [comment]
Accepted & confirmed.

**Comment by 4tochka** [comment]
Great work!!!

**Comment by Sxela** [comment]
ACK!

**Comment by Micromoneyio** [comment]
ACK

**Comment by smelamud** [comment]
ACK!

**Comment by backmeupplz** [comment]
Looks good, please merge before release

**Comment by Tolsi** [comment]
This is the best you can do 🚀

**Comment by eskrano** [comment]
Accept please

**Comment by AlekseiSmirnov** [comment]
works great. Ack

**Comment by sweety007** [comment]
ACK!

**Comment by apswak** [comment]
LGTM 👍

**Comment by Hiyorimi** [comment]
ACK

**Comment by backmeupplz** [comment]
Screen Shot 2019-06-19 at 9 25 29 AM

**Comment by TheWorldNode** [comment]
ACK

**Comment by kanemil** [comment]
ACK

**Comment by ohld** [comment]
Perfect solution for decentralized future.

**Comment by eugenioclrc** [comment]
Great contribution! ACK!

**Comment by ddustin** [comment]
lgtm merge it in!

**Comment by JoaquinScript** [comment]
tACK

**Comment by dondreytaylor** [comment]
Wow, this pull request works perfectly on nimbleNODE (pocket size full node) too. Good stuff 
https://nimblenode.io

**Comment by agiUnderground** [comment]
utACK

**Comment by berezinviktor** [comment]
ACK

**Comment by awsom82** [comment]
Yeah, just merge this!!!

**Comment by nikandfor** [comment]
lgtm

**Comment by bonzofenix** [comment]
LGTM

**Comment by bitstein** [comment]
LGTM

**Comment by blockchainwalletorg** [comment]
image

**Comment by binaryFate** [comment]
This PR does not address privacy concerns though, it only tackles the decentralization aspects but suggest to use a dangerously transparent blockchain.

**Comment by ericnakagawa** [comment]
Libra initially uses a set of validators from Founding Members -- this helps to provide stability for the project in its early days. However, over the long run, validators will be selected only on their holdings of Libra, forming a permissionless system.

We believe that Libra can coexist with other currencies like Bitcoin -- Libra addresses a number of needs (like low-volatility) that other currencies do not address today.

**Pull request closed without merging**
