### PR TITLE
Update dev_setup.sh Add freebsd support

### PR DESCRIPTION
**Pull request by EvertonMelo**
# Part 1: PACKAGE_MANAGER

As requested and authorized:
#122 

## references
Support multiple shells
https://www.freebsd.org/doc/pt_BR.ISO8859-1/articles/linux-users/shells.html
PKG-info:
https://www.freebsd.org/doc/handbook/pkgng-intro.html
more information:
https://gist.github.com/britzl/267a70d2cf144d651285

## Motivation

to continue #122 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

y

## Test Plan

 1 - local test on *freebsd v13 amd64*
 2 - stand alone test with dev_setup.sh and other O.S

## Related PRs

not applicable,
only commercial operating system addition

### CODE REVIEW

**Comment by EvertonMelo** [comment]
freeErro

error after install all requeriments.

**Comment by fbandersnatch** [comment]
Can you push this again to force a CI runs. Right now it's in weird CI state that prevents any progress.
You'll also need to clear trailing spaces in the script (CI should complain).

**Comment by EvertonMelo** [comment]
We have to think of a solution that can suit everyone, solving manually is not a professional solution.

**Comment by davidiw** [comment]
Please re-base and re-request if still valid.

**Comment by EvertonMelo** [comment]
@davidiw thanks

**Pull request closed without merging**
