### PR TITLE
[cluster-test] LSR and Vault integration with cluster-test

### PR DESCRIPTION
**Pull request by ankushagarwal**
## Summary

LSR and Vault integration with cluster-test

* Update set_asg_size so that it can handle cluster-size of more than 100 by using `next_token` 
* Add LSR and Vault pod and service specs
* Update validator spec to take another boolean - `enable_lsr`
* Use single service account - clustertest for all pods
* Add VaultConfig and LSRConfig to InstanceConfig enum
* Take `enable_lsr` as a boolean flag in cluster test main.rs

### CODE REVIEW

**Comment by andll** [comment]
This PR is in 'draft' - not ready for review yet?

Also, I am super curious what TPS we get with vault+lsr?

**Comment by ankushagarwal** [comment]
Still testing this out, so its in draft.

Initial results don't seem to be good :( https://toroeng.slack.com/archives/CSZN5D27R/p1591402946160200

**Comment by ankushagarwal** [comment]
@andll : Marked this as ready for review.
Verified that with `enable_lsr` set to false, we get same TPS results.
With `enable_lsr` set, we seem to be seeing a lot of timeouts in consensus - this is something which will need to be debugged.

**Comment by andll** [comment]
Actually, I realized formula was correct.
What is our plan for actually turning on vault+lsr in cluster test?
Do you want to merge this diff to avoid merge conflict and look into problems after that? or..?

**Comment by ankushagarwal** [comment]
> What is our plan for actually turning on vault+lsr in cluster test?

Once we figure out the timeouts issue we can enable it in nightly. What we need to figure out at a later point is whether we want to run all our experiments with LSR+Vault enabled or run LSR+Vault experiments separately from our current benchmark numbers.

> Do you want to merge this diff to avoid merge conflict and look into problems after that? or..?

Yup, the timeouts issue with LSR+Vault can be investigated later on, we should not block this diff from landing as it does not affect the current experiments.

**Comment by andll** [comment]
But how do we know if this code actually works/it's not an issue with cluster test setup?

**Comment by ankushagarwal** [comment]
> But how do we know if this code actually works/it's not an issue with cluster test setup?

All the validators are successfully committing transactions with this setup.

**Comment by andll** [comment]
I see. Ok, let's land it @bors-libra r+

**Comment by ankushagarwal** [comment]
Updated `--build-all-cti` -> `--build-all` since now we need to build `libra_init` image as well

**Comment by andll** [comment]
Wait, so if build-cti is basically what we need for cti, if we need init image, we need to include it in build-cti, not switch to build-all.
Otherwise cti will stop working

@bors-libra r-

**Comment by andll** [comment]
The reason we did this split between build-all and build-cti is because some images(like faucet) are not needed by cluster test

**Comment by ankushagarwal** [comment]
ack. Updated `build-all-cti`

@bors-libra r=andll

**Pull request closed without merging**
