### PR TITLE
[Secure Storage] Use filesystem lock to protect concurrent accesses to on-disk storage from different processes.

### PR DESCRIPTION
**Pull request by JoshLind**
## Motivation

This PR updates the on-disk storage backend to use filesystem locks to allow concurrent accesses to the same on-disk storage backend file (from multiple different processes). It does this using the named-lock crate. Moreover, it updates the key manager smoke tests and adds a new smoke test to allow multiple consensus key rotations (which couldn't previously be done because in the old deployment model LSR and the key manager have different backend files!). 

This PR offers three commits to allow smoke tests to use a single secure storage file:
1. Update the on-disk storage to use lock files for concurrency (around read and write).
2. Clean up the key manager smoke test.
3. Refactor the config builder to use only a single secure storage file and create a smoke test to perform multiple consensus key rotations to ensure that the shared backend file works.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

All local tests pass, including smoke tests.

## Related PRs

None.

### CODE REVIEW

**Comment by JoshLind** [comment]
@davidiw, this is ready for review 😄

**Comment by davidiw** [comment]
I'm a little uncomfortable with this PR because it adds dependencies to the TCB for a test only purpose. It also doesn't seem to simplify any tests. Perhaps we could better motivate this? Add it as a wrapper type like we did with namespace but make it only accessible in testing or ... something else?

**Comment by JoshLind** [comment]
Thanks, David! I agree.. the benefits of this PR are more what's happening in the background:
1. It means we no longer have to have separate storage files for each component in smoke tests. This requirement caused a bunch of annoying problems when writing genesis related code and tests.. It also makes debugging smoke tests easier as we can view the state of storage at a failure.
2. It allows us to write smoke tests that cross components (e.g., the key manager can rotate the consensus key several times and LSR can continue to operate). With the current model, the key manager can't do this. It doesn't have safe access to the LSR backend.

Regarding adding dependencies, I agree that it's not great. Let me take a look tomorrow to see if there's any easy way I can improve this..

**Comment by JoshLind** [comment]
Thanks, @davidiw! 😄 As discussed offline, I'll close this out as it should hopefully not be required once we move to a better execution model for tests. Overall it's good to see that this works though!

**Pull request closed without merging**
