### PR TITLE
[backup] db-restore counters & make MetricsPusher flush upon dropping

### PR DESCRIPTION
**Pull request by msmouse**
## Motivation
Using push-metrics to send metrics to the push gateway when environment variable "PUSH_METRICS_ENDPOINT" is set.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Y
## Test Plan

in the "dbtools" test environment.

### CODE REVIEW

**Comment by mgorven** [comment]
Looks good. Do we need to do anything to make sure that the final counters are pushed before the CLI exits?

**Comment by msmouse** [comment]
@mgorven Good point 👍 , will add that.

**Comment by msmouse** [comment]
note: fix typo in commit message.

**Review by lightmark — APPROVED** [review]

**Pull request closed without merging**
