### PR TITLE
[fuzzer][vm_values] filter out invalid layouts

### PR DESCRIPTION
**Pull request by vgao1996**
## Summary
The fuzzer may alter the raw bytes and result in invalid data layouts that will not pass the bytecode verifier. This gets them filtered out or otherwise they will show up as false positives.

## Test Plan
cargo test

### CODE REVIEW

**Comment by mimoo** [comment]
that's a good way to prevent the fuzzer reporting these, but just make sure that then this is a true assumption in the code :)

**Comment by vgao1996** [comment]
@mimoo Yes, can confirm these are internal invariants guaranteed by the bytecode verifier. We'll review other assumptions in the VM sometime.

**Pull request closed without merging**
