### PR TITLE
[libra framework] Updating the access control property reference

### PR DESCRIPTION
**Pull request by junkil-park**
Touches many files, but mostly changes the tag numbers in the comments.

- Deleted the temporary `access-control.md`, and updated the reference template's base url with the offical LIP-2 document address.

- Adjusted the reference tags in order to reflect the recent update in the LIP-2 document (a new row entry has been added to the permission table).

- Moved the TODO in Libra about the "hot potato" to the github issue: #6461

## Motivation

To update the references for the access control specs

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

yes

## Test Plan

cargo test

### CODE REVIEW

**Review by wrwg — APPROVED** [review]
This PR, though changing .move files, does not change any bytecode (.mv) files, and therefore labelled is as "documentation" PR, and approved.

**Comment by wrwg** [comment]
> @junkil-park ❗ This PR is still missing approvals, unable to queue for landing

I think @dariorussi can approve this.

**Review by dariorussi — APPROVED** [review]
thanks!

**Pull request closed without merging**
