### PR TITLE
disable async

### PR DESCRIPTION
**Pull request by davidiw**
Just exploring if async actually benefits us....

### CODE REVIEW

**Comment by ankushagarwal** [comment]
Can we control this with an env variable so that by default we log to sync but when `RUST_ASYNC_LOG` is set to a non-empty value, we do async logging.

This can help us retry async logging in the future without looking up git history

```
use std::env;
let rust_log = match env::var("RUST_ASYNC_LOG") {
    Ok(_) => {},
    Err(_) => {},
};
```

**Comment by ankushagarwal** [comment]
Nevermind the previous comment, just re-read our conversation on Slack.

**Comment by davidiw** [comment]
My preference would be to just delete the code. It doesn't really provide us value in fixing any quirks and the other aspects that having it in place does. Though I am eager to hear opinions to the opposite. (I like to delete things that we don't plan on using)

**Comment by davidiw** [comment]
Spoke with @andll, while we might not need this now, this allows a clean way for overflowing logs and not halting the process in the case of exhausted buffers.

**Pull request closed without merging**
