### PR TITLE
[move-prover] make the no_opaque test ignore internal functions only - (27) 

### PR DESCRIPTION
**Pull request by ankitkacn**
### Motivation
To reduce CI time, Instead of ignoring  pragma opaque for all test functions , we are now ignoring only for internal functions  And also to align with intended below use cases

Prior to this commit, the ```no_opaque``` test ignores pragma opaque in almost every function. 
Although the prover does not time out in 40s, this is still a non-trivial amount of time spend in unit test. More importantly, this might not align with what we have envisioned for how the specs are supposed to be written: specs are expected to be written and complete for public-facing functions --- as a result, the public-facing functions can be opaque from a verification point of view, hence increasing compositionally of the specs. ```Inlining``` public functions destroy such compositionally.

A lot of the .exp file updates are due to the removal of the
// ```separate_baseline: no_opaque``` directive in certain files. The key
change will be highlighted below.

This PR also cleans up a few inv-v1_exp and inv_v2_exp files, as
we do not have the inv-v1 test anymore.

Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?
Yes

### Test Plan
CI

### CODE REVIEW

**Review by dhaneshacn — APPROVED** [review]

**Review by KoushikGavini — APPROVED** [review]

**Comment by ankitkacn** [comment]
Closing this PR due to technical error, raised new PR
New PR link : https://github.com/diem/diem/pull/10569

**Pull request closed without merging**
