### PR TITLE
Add missing metadata to Cargo.tomls

### PR DESCRIPTION
**Pull request by TristanDebrunner**
## Motivation

For packages to be published to [crates.io](https://crates.io), they need to have descriptions, repositories, homepages, and licenses listed.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

No functional changes, existing CI suffices.

### CODE REVIEW

**Comment by garious** [comment]
Hi @weilei0107, @bmwill, hoping this PR is uncontentious. Can you please review this so that we don't need to keep rebasing it?

**Comment by huitseeker** [comment]
@TristanDebrunner Thanks a bunch! please consider https://github.com/TristanDebrunner/libra/pull/1, which if you merge it will add to the present PR. I'll kick a merge on this side.
([Github pull request edits](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) is a feature that streamlines this sort of thing)

**Pull request closed without merging**
