### PR TITLE
[language] add Vector.contains

### PR DESCRIPTION
**Pull request by sblackshear**
Useful to check if a vector already has a value in it.

## Motivation

Working on code to add validator addresses, need this to ensure that validators aren't double-added.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

New E2E tests.

### CODE REVIEW

**Comment by dariorussi** [comment]
genesis everywhere not just the local one ;)

**Comment by runtian-zhou** [comment]
Probably need to execute `./scripts/circle_validate_configs.sh` locally.

**Pull request closed without merging**
