### PR TITLE
[config-builder] Update docker-run-dynamic.sh to allow for config overrides

### PR DESCRIPTION
**Pull request by ankushagarwal**
## Motivation

This allows us to control parameters from the docker run command or the kubernetes pod spec

## Test Plan

Ran locally

### CODE REVIEW

**Comment by davidiw** [comment]
Seems reasonable

@bors-libra r+

**Comment by mgorven** [comment]
You should be able to do this already by passing a base template in `CFG_BASE_CONFIG`.

**Comment by mgorven** [comment]
I also think the nicer mechanism here is to use an initContainer in k8s to run `config-builder`:
https://github.com/calibra/libra-ops/blob/master/helm/libra-validator/templates/validator.yaml#L162

**Comment by ankushagarwal** [comment]
The challenge with using an init container is that right now I don't want to duplicate code from `docker-run-dynamic.sh` into the helm chart for libra-testnet. That way changes to `docker-run-dynamic.sh` can break the libra-testnet helm chart

**Comment by ankushagarwal** [comment]
`CFG_BASE_CONFIG` doesn't work correctly (or maybe I am using it incorrectly). I tried to pass the following string in `CFG_BASE_CONFIG` and the script failed because it tried to expand this string inside the `if []` block and bash gets confused becuase of the additional `[]`

```
[consensus]
max_block_size = 300
```

**Comment by ankushagarwal** [comment]
I also tried writing the config directly to `/opt/libra/etc/base.config.toml`  and the node still didn't pick it up (it was still using max_block_size = 100)

```
[consensus]
max_block_size = 300
```

**Comment by ankushagarwal** [comment]
@mgorven Can we proceed with this change?

**Comment by mgorven** [comment]
Sorry, thought this was already landed. Yeah, fine for now. @bors-libra r+

**Pull request closed without merging**
