### PR TITLE
Warn PR authors when they change the JSON-RPC server about compatibility requirements

### PR DESCRIPTION
**Pull request by metajack**
This action leaves a comment with a checklist to notify PR authors what to do when their code modifies the JSON-RPC server.

### CODE REVIEW

**Comment by metajack** [comment]
When @thefallentree or @xli verify this is what they want, I'll remove the last commit before landing.

**Comment by libra-action** [comment]
**JSON-RPC server code potentially changed**

Please ensure you have done the following:

1. Update json-rpc/API-CHANGELOG.md for the API changes that
   affect clients
2. Update type/method documentation under json-rpc/docs

**Review by xli — APPROVED** [review]

**Comment by thefallentree** [comment]
I made some comments on the canned reply below.

> this PR seems to have modified JSON-RPC server code.
> 
> Breaking changes policy:
> 
> 1) Changing JSONRPC method signature or removing/changing field meaning in the response in /V1 will not be accepted.
> 2) adding a field is okay.
> 3) adding an new JSONRPC method is okay.
> 
> Please ensure you have also done the following to update the docs:
> 
> 1) Update json-rpc/API-CHANGELOG.md.
> 1) Add/Update type/method documentation under json-rpc/docs

**Comment by metajack** [comment]
I updated the comment to reflect @thefallentree's suggestion.

/land

**Review by thefallentree — APPROVED** [review]

**Pull request closed without merging**
