### PR TITLE
[network] HealthCheckerBuilder

### PR DESCRIPTION
**Pull request by agc-quadra**
The HealthCheckerBuilder consolidates the configuration/building/starting of the HealthChecker and modularizes it out of network_builder

## Motivation

Introduce the modular HealthCheckerBuilder.

This is an incremental step towards the modular refactoring of network_builder in sketched in #4626

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

yes
## Test Plan

don't break existing tests

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by agc-quadra** [comment]
@davidiw @gregnazario

**Comment by davidiw** [comment]
thanks for splitting up, let's move forward~~~

@bors-libra r+

**Comment by agc-quadra** [comment]
@davidiw 

Merge conflict resolution

**Pull request closed without merging**
