### PR TITLE
[JSON RPC] make CLI client independent of AC/gRPC

### PR DESCRIPTION
**Pull request by christinacelee**
## Summary

Last step in completely migrating CLI over from AC/gRPC to JSON RPC protocol!
- removed last gRPC endpoint in CLI client (replaced with `get_state_proof`)
- removed all AC dependencies in CLI client

## Test Plan

Locally ran CLI
Currently `start_cli_testnet.sh` breaks on failing to connect to JSON RPC port - this should be resolved once JSON RPC port is opened on testnet.

### CODE REVIEW

**Comment by ankushagarwal** [comment]
cluster test failure message

```
INFO 2020-03-12 17:45:27 testsuite/cluster-test/src/tx_emitter.rs:149 Will create 10 accounts_per_client with total 3000 accounts
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to run experiment: query_sequence_numbers on http://10.0.7.89:8080 for faucet account failed: [http://10.0.7.89:8080] get_accounts_state failed: error sending request for url (http://10.0.7.89:8080/): error trying to connect: tcp connect error: Connection timed out (os error 110)

Caused by:
    0: error trying to connect: tcp connect error: Connection timed out (os error 110)
    1: tcp connect error: Connection timed out (os error 110)
    2: Connection timed out (os error 110) ', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by andll** [comment]
Yeah, this is legitimate failure. @christinacelee can you add new port similarly to https://github.com/calibra/libra-ops/pull/427 first? (note that you need to add new rule, not change existing)
When PR for this change merges, I'll do tf apply and then this PR can be landed

**Pull request closed without merging**
