### PR TITLE
[rust] Update rust-toolchain to 1.45.2 for soundness fix

### PR DESCRIPTION
**Pull request by metajack**
More details on the soundness issue here: https://github.com/rust-lang/rust/issues/74739

We were not affected to our knowledge, but upgrading the toolchain seems prudent.

### CODE REVIEW

**Comment by metajack** [comment]
cc @tzakian who originally brought this to my attention

**Comment by metajack** [comment]
Should we hold off a day since they plan to release that tomorrow and avoid churn here?

**Comment by bmwill** [comment]
Yeah probably worth waiting till they do the next point release.

**Comment by sausagee** [comment]
Can we canary the code coverage workflow before landing?

**Comment by metajack** [comment]
This is now updated to 1.45.2.

**Comment by rexhoffman** [comment]
If the two code coverage jobs in this build pass, we should be good:

https://app.circleci.com/pipelines/github/novifinancial/libra-ops?branch=pull%2F660

**Comment by rexhoffman** [comment]
fuzzer coverage succeeded.
full unit coverage still on going, should be done in an hour or so.

**Comment by metajack** [comment]
GitHub was having issues, they claim they are resolved now.

/land

**Pull request closed without merging**
