### PR TITLE
[cluster-test] include twin node test into nightly run

### PR DESCRIPTION
**Pull request by snakech**
## Motivation

include twin node test into nightly run

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

(Share your test plan here. If you changed code, please provide us with clear instructions for verifying that your changes work.)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by andll** [comment]
We also moved three-region simulation up, is this intentional?

**Comment by snakech** [comment]
> We also moved three-region simulation up, is this intentional?

Just wanna make the tests order as before, which the 2 newly added tests just after the 3-region

**Comment by andll** [comment]
OK
@bors-libra delegate+

**Pull request closed without merging**
