### PR TITLE
[client] moving cli and libra-wallet to testsuite

### PR DESCRIPTION
**Pull request by mimoo**
We currently consider the CLI a testing tool,
and not something that should be used in production.
For this reason it is safer to move it to the testsuite folder,
that is until we have a better story for a reference client SDK.

### CODE REVIEW

**Comment by davidiw** [comment]
seems reasonable to me... will give another 12 hours before pushing.

**Comment by davidiw** [comment]
Maybe you could make a call for action across the team. I think the intent here is that content under testsuite isn't up for bug bounty, isn't intended for auditing, etc, etc?

@bors-libra delegate+

**Comment by mimoo** [comment]
> Maybe you could make a call for action across the team. I think the intent here is that content under testsuite isn't up for bug bounty, isn't intended for auditing, etc, etc?

I'm writing a post about this :)

**Pull request closed without merging**
