### PR TITLE
[cluster-test] exclude vault and lsr instances from validators and fu…

### PR DESCRIPTION
**Pull request by snakech**
…llnodes health check only

## Motivation

(Write your motivation for proposed changes here.)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

(Share your test plan here. If you changed code, please provide us with clear instructions for verifying that your changes work.)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by snakech** [comment]
> This looks reasonable! Can you confirm before merging that perf-suite pass with this change?

I confirmed, succeeded run with perf-suit

**Comment by andll** [comment]
@bors-libra r+ priority=1000
Boosting priority because nightly build keep failing without it, increasing chance of bad commit getting in the pending list

**Pull request closed without merging**
