### PR TITLE
[language] allow passing transaction metadata in peer-peer transactions

### PR DESCRIPTION
**Pull request by sblackshear**
- Add metadata payload to PaymentReceivedEvent
- Extend LibraAccount.deposit and LibraAccount.pay_from_sender to accept metadata payload + pass it into the event
- Add new transaction script for pay_from_sender_with_metadata
- Add script to whitelist

## Motivation

Adding the relevant Move support for the subaddressing proposal in https://github.com/libra/libra/issues/714. After this, all that should be needed is Libra client support for specifying the metadata.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

New E2E tests.

### CODE REVIEW

**Comment by phoenix-antigravity** [comment]
lgtm! will let @runtian-zhou to accept

**Comment by runtian-zhou** [comment]
Question about this memo field in general. Are we concerned if someone would use this field to publish some improper message/bytes on chain?

**Comment by sblackshear** [comment]
> Question about this memo field in general. Are we concerned if someone would use this field to publish some improper message/bytes on chain?

I don't think so, or at least this isn't more problematic than the existing `rotate_authentication_key` script (which also accepts an arbitrary bytearray).

**Pull request closed without merging**
