### PR TITLE
[dkr] add validator buildspec and rename e2e

### PR DESCRIPTION
**Pull request by sausagee**
## Motivation
Add support for Docker images clean up and transition.

## Test Plan
Canaried in LBT

### CODE REVIEW

**Comment by davidiw** [comment]
I suspect this won't work well until this is resolved in libra-ops:


The push refers to repository [docker.io/libra/validator]
--
1002 | eede1078b8d9: Preparing
1003 | 6b41d56fefeb: Preparing
1004 | 0c80f63f58d6: Preparing
1005 | c5a5d37d72fd: Preparing
1006 | e76d9b65ae2a: Preparing
1007 | 2bb493033dea: Preparing
1008 | d21ca9f06c5f: Preparing
1009 | e1f4094b194b: Preparing
1010 | c6bb894d9f70: Preparing
1011 | b6a2f0eee1d4: Preparing
1012 | 0ced13fcf944: Preparing
1013 | e1f4094b194b: Waiting
1014 | c6bb894d9f70: Waiting
1015 | 2bb493033dea: Waiting
1016 | d21ca9f06c5f: Waiting
1017 | b6a2f0eee1d4: Waiting
1018 | 0ced13fcf944: Waiting
1019 | denied: requested access to the resource is denied

**Comment by davidiw** [comment]
btw it might be easier to see what's going on by running  ./docker/build-aws.sh, I found /canary isn't powerful enough yet

**Comment by sausagee** [comment]
> I suspect this won't work well until this is resolved in libra-ops:
> ## The push refers to repository [docker.io/libra/validator]
 
Yep, I thought I could override the ECR repo path here, but it ended up trying to push to DockerHub. I just updated the codebuild spec in-place in libra-ops and added the libra/validator ECR repo path. Will see if it works.

**Comment by sausagee** [comment]
woohoo it works! Canary passed.

**Review by davidiw — APPROVED** [review]
Let's do it! This will probably allow my PR to pass without any more issues! I was concerned I was going to have to institute a bunch of silly copy / pastes. I might still have to... but *fingers crossed*

/land

**Pull request merged**
