### PR TITLE
[management] allow owner/operator support for adding new validator

### PR DESCRIPTION
**Pull request by davidiw**
I cannot directly write into release-0.21 so I need to do this... sigh.

We need this for Wednesday.

### CODE REVIEW

**Review by mgorven — APPROVED** [review]

**Comment by mgorven** [comment]
This will need an update to the wrapper script: https://github.com/libra/partners/blob/master/scripts/libra-operations.sh

**Comment by davidiw** [comment]
sigh... one time uses .... sigh...

**Comment by davidiw** [comment]
well crap.... I don't know what to do here now...

**Pull request merged**
