### PR TITLE
[network] memsocket should only appear in debug builds

### PR DESCRIPTION
**Pull request by benallamar**
## Motivation

The goal is to make network/memsocket crate test-only.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

yes

It fixes issue #3682

### CODE REVIEW

**Comment by benallamar** [comment]
@phlip9 @davidiw can you please have a look on this PR ?

**Comment by phlip9** [comment]
Awesome, looks great! Thanks again for the PR : )

@bors-libra r+

**Pull request closed without merging**
