### PR TITLE
[network] Add integration tests for gossip-based discovery

### PR DESCRIPTION
**Pull request by nikakis**
## Motivation

This PR concern the implementation of integration test for the communication between peers based on the discovery direct send protocol. This will help to avoid bugs which cannot be prevented from the unit tests.

Closes: #1771 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

(Share your test plan here. If you changed code, please provide us with clear instructions for verifying that your changes work.)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by davidiw** [comment]
Unfortunately I'm not familiar enough with the area to go beyond what support I have given. Perhaps one of the other folks I have tagged can help out.

**Comment by bothra90** [comment]
@nikakis : We've made some changes to the network module which require you to rebase your changes --  you can look at other protocol tests for pointers. I'll be happy to help you land this PR. Thanks for taking this up.

**Comment by nikakis** [comment]
Great, I will do this asap. Apologies for my late response.

**Comment by nikakis** [comment]
@bothra90 If am not wrong the integration test introduced with this PR has already covered from this commit `58dce3b065a1e6bbf06da47a3f8d009f1382ddca`, probably this PR can close.

**Comment by bothra90** [comment]
@nikakis : The commit you mentioned tests only the initialization part of the discovery module where it dials all the seed peers. It does not test the actual gossip protocol like your commit does. So it will still be valuable to land this.

**Comment by nikakis** [comment]
@bothra90 ok great, now i understand, i will do it asap. Thanks !!

**Comment by davidiw** [comment]
Feel free to reopen if you'd like to continue.

**Pull request closed without merging**
