### PR TITLE
Twins BFT safety

### PR DESCRIPTION
**Pull request by sheharbano**
The document (shared offline) describes the design of Twins, a new approach for systematically testing Byzantine Fault Tolerant (BFT) systems. We implemented Twins in Rust on top of LibraBFT, providing unit tests for the LibraBFT consensus protocol. The document describes implementation details, i.e. the modifications and extensions to the original LibraBFT code.

## Motivation

(Write your motivation for proposed changes here.)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

(Share your test plan here. If you changed code, please provide us with clear instructions for verifying that your changes work.)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by zekun000** [comment]
1. the rebase doesn't seem clean to me, a lot of unrelated files still appear(proto is deleted from the codebase)
2. also please delete those print used for debug
3. I think we can split the change into smaller pieces to make it more reviewable, like the round_proposer looks like pretty isolated change

**Comment by davidiw** [comment]
meta-question, this changes a lot of data types just to support "twins". It would be worth exploring means in which we can hide twins as much as possible otherwise we end up adding engineering overhead to maintaining test frameworks within our code base.

**Comment by davidiw** [comment]
What's the plan here? How could we help?

**Comment by lishuai87** [comment]
why not use failpoint?   e.g. https://github.com/etcd-io/gofail

**Comment by HAOYUatHZ** [comment]
I find this PR following [Twins: White-Glove Approach for BFT Testing](https://arxiv.org/pdf/2004.10617.pdf).

It might be a stupid question, but what are the advantages of Twins over TLA+? Would like to hear about what Twins can do but TLA+ can't, or what can be done more conveniently using Twins.

**Pull request closed without merging**
