### PR TITLE
[k8s][clustertest] Add k8s support for flamegraph experiment

### PR DESCRIPTION
**Pull request by ankushagarwal**
## Summary

Add k8s support for flamegraph experiment

## Test Plan

`./scripts/cti -E RUST_LOG=debug -W kush --k8s --cluster-test-tag dev_kush_c302f12b --tag master_0660fec --run generate_cpu_flamegraph --k8s-fullnodes-per-validator=0 --k8s-num-validators=100`

### CODE REVIEW

**Comment by andll** [comment]
High level question - do we want to build util image with other images and use `cluster-test-util:$CLUSTER_TEST_TAG` instead of `:latest`?
This way we could include scripts such as flamegraph generation inside this image.
Also, this would allow us not to worry about releasing latest image and then figuring out compatibility between versions

**Comment by ankushagarwal** [comment]
I don't think we get any additional value by setting up and maintaining a continuous build.

Having one off builds pushed by developer makes sense for cluster-test-util because we don't want tools like perf or the Flamegraph repo to get automatically updated and potentially have breaking changes.

> This way we could include scripts such as flamegraph generation inside this image.

We probably don't want to do that because we need to customize the script (eg setting the filename generated) from cluster-test itself.

**Comment by andll** [comment]
Problem with one off builds is that if someone needs new :latest image for some new functionality, they will need to make sure image is still compatible with current master version of cluster test(since people are still submitting PRs).
If they are not careful enough and push latest image that is not compatible with current mater, they will break builds for everyone

**Comment by andll** [comment]
We can still merge this diff, but I think we do need cont build for util image in a medium-long term
@bors-libra delegate+

**Pull request closed without merging**
