### PR TITLE
[Docker] update toolchain to stable

### PR DESCRIPTION
**Pull request by sausagee**
## Motivation
We udpated rust toolchain to stable and need to keep the docker build
in sync.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan
Tested validator build locally.  Will defer the rest docker builds to CircleCI to verify.

### CODE REVIEW

**Comment by andll** [comment]
Thanks for fixing that
Lets just finalize discussion on whether we want toolchain file at all on stable, before merging this

**Comment by sausagee** [comment]
> Thanks for fixing that
> Lets just finalize discussion on whether we want toolchain file at all on stable, before merging this

Will defer this to @bmwill

**Comment by andll** [comment]
It looks like current direction supported by majority is pinning stable version on CI, do you mint updated this PR @sausagee to pin version in docker container?

**Comment by andll** [comment]
Although, perhaps I got it wrong and we getting toolchain file back :/

**Comment by sausagee** [comment]
The toolchain file is added back. This is PR is no longer needed.

**Pull request closed without merging**
