### PR TITLE
[transaction builder generator] improve CLI

### PR DESCRIPTION
**Pull request by matbd**
## Motivation

Simplify user experience by removing the need for `cargo install serde-generate`. Instead, one just needs to pass an additional option `--with-libra-types path/to/libra.yaml`.

This also means the versioning of serde-generate is handled by libra.git alone.

## Test Plan

```
# DEST = some target path
cargo run -p transaction-builder-generator -- --language python3 --module-name stdlib --with-libra-types \
testsuite/generate-format/tests/staged/libra.yaml --serde-package-name pylibra --libra-package-name pylibra \
--target-source-dir "$DEST" language/stdlib/compiled/transaction_scripts/abi
```

### CODE REVIEW

**Comment by ankushagarwal** [comment]
@matbd Can we have a `README.md` for `transaction-builder-generator`. It will be really helpful for DDs to have a README which explains the flags, gives an example of how to use the cli for various languages (since not all flags seem to be relevant for all languages) and a maybe a short hello world example for each language similar to the C++ code that you illustrated here : https://github.com/libra/libra/pull/4703

**Comment by matbd** [comment]
@ankushagarwal Totally. Do you have any particular location in mind or should I just create `language/transaction-builder-generator/README.md`?

**Comment by ankushagarwal** [comment]
`language/transaction-builder-generator/README.md` makes perfect sense

**Comment by matbd** [comment]
> `language/transaction-builder-generator/README.md` makes perfect sense

@ankushagarwal Added a first README file to this PR. Feedback welcome

**Comment by ankushagarwal** [comment]
I probably won't get time till tomorrow to take a look. Feel free to land it in the meanwhile.

**Pull request closed without merging**
