### PR TITLE
[language] move toward eliminating get_gas_remaining opcode

### PR DESCRIPTION
**Pull request by sblackshear**
This opcode is only used in the transaction epilogue. We don't want it in the language because (a) it's not useful (see above) and (b) it entangles the gas world and concrete world by making the gas usage visible inside a concrete execution (e.g., can branch on the value of `get_gas_remaining)`.

This PR 
- replaces the epilogue usage with an explicit `gas_units_remaining` parameter
- removes get_gas_remaining from the AST/parser for the IR and source language
- makes the VM fail if it encounters the `get_gas_remaining` opcode. 

It does not yet delete the opcode from the file format--we are waiting to make all of the breaking changes to the format at once.

## Motivation

Continuing work on improving the bytecode language and separating the Move and Libra layers.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

No existing uses of the epilogue break; should be pure refactoring.

### CODE REVIEW

**Comment by vgao1996** [comment]
LGTM. @tnowacki do the changes to the move compiler look good to you?

**Comment by vgao1996** [comment]
@sblackshear also I think this is a breaking since the signature of the epilogue has changed?

**Comment by sblackshear** [comment]
Good catch; I forgot that tag. Added now.

**Pull request closed without merging**
