### PR TITLE
[libra-trace] Add counters for libra-trace and struct_log.

### PR DESCRIPTION
**Pull request by changyonghu**
Add counters for libra-trace and struct_log.

### CODE REVIEW

**Comment by metajack** [comment]
Why didn't this use libra-metrics? I tried to isolate the prometheus dependency there.

**Comment by andll** [comment]
@davidiw what is the solution you propose? How do we add counter that works for both other libra crates _and_ TCB?

@metajack it seems libra-metrics references prometheus crate, so using it is not going to help?

**Comment by davidiw** [comment]
Well this won't even be used by TCB, you create a counter that is a no-op in TCB land.

I suspect you probably want some sort of ability to register a counter to be used by logging and we'd need a common interface for that. That way the TCB can push the metric and prometheus + hyper can share it.

**Comment by andll** [comment]
We probably need to figure out this 'metrics done differently' in TCB.

There probably will be other components in libra shared between TCB and non-TCB. Currently if they would want to export counters, what would they do?

**Comment by davidiw** [comment]
sure, but this seems like a pretty special metric, do we imagine more cases where we'll want to log at a common layer?

**Pull request closed without merging**
