### PR TITLE
[config-builder] add option to specify number of nodes coded in genesis

### PR DESCRIPTION
**Pull request by zekun000**
## Motivation

Preparing work for demonstrating registering validator 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Y

## Test Plan
it compiles :) real test will follow

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by davidiw** [comment]
While I can read the code, it isn't clear to me why we want this? It doesn't fit into any of the workflows that I'm familiar with.

In my model, we would have folks submit their public keys, we then generate a genesis from those keys. I suppose this might be for testing and enabling folks to deterministically generate larger networks? But that doesn't need to be done on each individual host, it just needs to be done from a single point.

**Comment by zekun000** [comment]
@davidiw this is for testing purpose(the same as the whole config builder), it's mainly designed for pre-mainnet to replace the current workflow
which is
adding a new member == rebuild the network and start again.
to
adding a new member == config build -n n+1, -g n, dispatch the new config(including all validator common) to the new member and exercise reconfiguration for adding them to network without requiring every existing members to wipe the db and restart.

**Comment by davidiw** [comment]
I think the key goal is how can we extend the validator set from a given genesis to a new node. Humor me, how bad would it be to run generate twice... once with size = n and index = any and again as n + k and index n + k - 1 so that the peer can retrieve their deterministic keys?

**Comment by zekun000** [comment]
well, it works but I also want to test with devnet/testnet and probably don't want to do tf apply twice(have no idea how it works).
I'm hoping to generate 5 nodes with first 4 genesis in devnet and just submit txn to register the 5th and add it to the network(then claim dev  is live)

**Comment by davidiw** [comment]
Everything else adds complexity, let's not let complexity block the progress here....

@bors-libra r+

**Pull request closed without merging**
