### PR TITLE
[language] remove the remaining support for move_to_sender/get_txn_sender

### PR DESCRIPTION
**Pull request by bob-wilson**
This removes:

- the GET_TXN_SENDER and MOVE_TO_SENDER[_GENERIC] bytecodes (I reordered the NOP and MOVE_TO bytecodes to keep the consecutive bytecode values in the file format, along with matching changes in the code order in several other files)
- error codes that were specific to the removed bytecodes
- the "txn_sender" syntax in the Move IR specification language and other Prover support for the removed bytecodes
- the Transaction.move stdlib module with the "sender()" function declaration

In the process, I also found a few problems to fix:

- bytecode-verifier/src/signature.rs: added missing check for MoveToGeneric
- bytecode-verifier/src/unused_entries.rs: added missing check for MoveToGeneric
- disassembler/src/disassembler.rs: added support for MoveTo[Generic]
- test-generation: completed some partial support for MoveTo and added tests

## Motivation

Removing obsolete code!

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Updated tests (including filling some holes in testing for move_to) and ran them

### CODE REVIEW

**Comment by bob-wilson** [comment]
This changes some bytecode assignments, so I'm adding the "breaking" label.

**Comment by bob-wilson** [comment]
Hmm. The twins_test::drop_config_test failed with:
thread 'twins_test::drop_config_test' panicked at 'assertion failed: commit_seen', consensus/src/twins_test.rs:296:9

Bano just added that so maybe it's flaky. I'll retry

**Comment by bob-wilson** [comment]
It failed again the same way. @sheharbano Any ideas?

**Comment by tzakian** [comment]
Getting the same issues on my PRs today as well :'(

**Pull request closed without merging**
