### PR TITLE
[stdlib] Fix access control policy for block prologue

### PR DESCRIPTION
**Pull request by runtian-zhou**
## Motivation

Previously all the critical functions in LibraSystem are marked as public just for the sake of testing. This PR will enforce security rules such that they can only be called from inside the VM not via a regular script. 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Fix all existing test case and add negative cases to make sure such calls will no longer work in the system

### CODE REVIEW

**Comment by vgao1996** [comment]
Marked this as breaking as it changes the stdlib (genesis). Feel free to remove if I'm wrong.

**Comment by runtian-zhou** [comment]
> Marked this as breaking as it changes the stdlib (genesis). Feel free to remove if I'm wrong.

It is breaking in the sense that it changes the genesis but not breaking as the current testnet will not be affected.

**Pull request closed without merging**
