### PR TITLE
[cluster-test] add failpoints hashmap to the template

### PR DESCRIPTION
**Pull request by zekun000**
## Motivation

Leverage cluster test to enable the falipoint injection.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Y

## Test Plan

ENABLE_FAILPOINTS=1 ./scripts/cti --pr 5957 --run bench

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by zekun000** [comment]
Experiment Result: all up : 822 TPS, 5512 ms latency, 10500 ms p99 latency, no expired txns

**Comment by andll** [comment]
Curious - did you check in counter/logs that there are actual failures happening?
From the low TPS it does seem so, but wanted to double check

**Comment by zekun000** [comment]
@andll yes, I did search in the logs and saw expected error messages.

**Review by andll — APPROVED** [review]
Thats pretty cool :)

**Pull request closed without merging**
