### PR TITLE
cargo update

### PR DESCRIPTION
**Pull request by msmouse**
## Motivation

refresh cargo.lock

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

yes 

## Test Plan

Existing coverage

### CODE REVIEW

**Comment by bmwill** [comment]
The `ed25519-dalek: 1.0.0-pre.1 -> 1.0.0-pre.2` update is the only one that looks worrisome. If we have a guarantee that `pre.1` is compatible with `pre.2` then I think we should be ok to update things.

**Comment by msmouse** [comment]
@bmwill  I don't think I'm capable to tell if it's 100% compatible, especially considering it is 8 months since last release.. @huitseeker you? 

But anyway I think we definitely want to keep up with official releases as soon as possible?

**Comment by msmouse** [comment]
@metajack added.

**Comment by bmwill** [comment]
@msmouse I bring up my concern because the versions with have `Major.Minor.Patch-Something` aren't really semver compatible and breaking changes can occur when bumping to another `Something` version (e.g. look at the futures 0.3.0-alpha.XX crate and versions)

**Comment by metajack** [comment]
This will bitrot easily so I suggest using p=10 when you tell bors to land it.

**Comment by msmouse** [comment]
I messed it up by trying to manually exclude the "ed25519-dalek 1.0.0-pre.2" change. Abandoning.

**Pull request closed without merging**
