### PR TITLE
[librarian] command skeleton

### PR DESCRIPTION
**Pull request by lightmark**
## Motivation

A skeleton for the libra db data access tool for human inspection.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Y

## Test Plan

N/A

### CODE REVIEW

**Comment by msmouse** [comment]
I thought this is more about exposing more "debug" type of information like JellfyFish internal hashes.. or directly exposing get / set methods on the column falimies

Listing transactions, printing balances.. I think these are duplication of functionality from the JsonRpc / cli?

**Comment by lightmark** [comment]
@msmouse 
This should be a db-level tool that operates on online/offline libradb instance, having nothing to do with json-rpc service.
Now what's in my mind are:
0. committed_version/synced_version
1. txn get/scan
2. get account by address and seq, version, scan by seq range
3. get event by name and seq, scan by seq range

Optional:
1. legder_info by epoch
2. jellyfish merkle nodes exposure.

idk whether writes should be permitted. Let's discuss details in roadmap planning concerning how to proceed with demands.

**Review by msmouse — APPROVED** [review]
unblocking you.

**Comment by bmwill** [comment]
@lightmark huge props for the awesome tool name!

**Pull request closed without merging**
