### PR TITLE
[tf] add private IP override options for nodes

### PR DESCRIPTION
**Pull request by rustielin**
## Motivation

Since IPs are used in genesis, in recreating network state across Terraform workspaces, we need to be able to choose node IPs. This adds `override_faucet_ip`, `overide_fullnode_ips`, and `override_validator_ips` to terraform.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Spinning up network works as before. Show IPs in jumphost:

```
[rustielin:jumphost@ip-10-0-1-144 ~]$ list-instances
10.0.7.206
rustielin-validator-1
10.0.6.46
rustielin-fullnode-1
10.0.1.132
rustielin-haproxy0
10.0.3.188
rustielin-validator-0
10.0.1.49
rustielin-fullnode-0
10.0.3.98
rustielin-cluster-test-runner
10.0.3.6
rustielin-faucet
10.0.1.123
rustielin-validator-3
10.0.2.7
rustielin-monitoring
10.0.3.52
rustielin-vault
10.0.1.144
rustielin-jumphost
10.0.9.96
rustielin-validator-2
```

Spin up separate network but with pinned IPs in var-file:

```
override_validator_ips = ["10.0.3.188", "10.0.7.206", "10.0.9.96", "10.0.1.123"]
override_fullnode_ips = ["10.0.1.49", "10.0.6.46"]
override_faucet_ip = "10.0.3.6"
``` 

Show IPs in jumphost:

```
[rustielin:jumphost@ip-10-0-1-231 ~]$ list-instances
10.0.6.46
rustietest-fullnode-1
10.0.7.206
rustietest-validator-1
10.0.3.111
rustietest-monitoring
10.0.3.108
rustietest-vault
10.0.3.6
rustietest-faucet
10.0.1.134
rustietest-haproxy0
10.0.1.49
rustietest-fullnode-0
10.0.0.9
rustietest-cluster-test-runner
10.0.3.188
rustietest-validator-0
10.0.1.231
rustietest-jumphost
10.0.1.123
rustietest-validator-3
10.0.9.96
rustietest-validator-2
```

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by mgorven** [comment]
Is this confirmed to be the problem? I didn't think that genesis contained IPs; the way it's generated know I don't see how that's even possible.

**Comment by rustielin** [comment]
> Is this confirmed to be the problem? I didn't think that genesis contained IPs; the way it's generated now I don't see how that's even possible.

@mgorven not confirmed the problem, but we still need the configs to match up. Figured this would be a helpful var to have in the future too.

**Comment by mgorven** [comment]
This seems messy and unnecessary, I'd prefer to avoid this.

**Comment by rustielin** [comment]
@mgorven this will be an issue for record and replay when network switches to onchain discovery only instead of gossip discovery

**Pull request closed without merging**
