### PR TITLE
[move-prover] Cleanup of transformation pipeline.

### PR DESCRIPTION
**Pull request by wrwg**
This is a minor cleanup of the transformation pipeline post the memory refactoring PR:

- Renamed create `stackless-bytecode-generator` to `bytecode`. Since a while it is not longer just the bytecode generator, so this new name is more adequate.
- Removed the possibility to return an error Result from data flow analysis. This is not used any longer, and if it needs to be again, analyzer should instead use GlobalEnv::error to report an error and handle conditions internally, to avoid complexity for analyzer which never produce errors.
- Made the data-flow framework `execute` function to work on a mut state instead of in/out state. This is more adequate in most use cases.
- Collapsed BorrowState and BorrowInfo into one data structure as there is no significant difference any longer.
- Added missing test cases for new phase clean_and_optimize

## Motivation

Cleanup

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Existing tests

## Related PRs

PR #5971

### CODE REVIEW

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode 0.1.0 (workspace, path 'language/move-prover/bytecode')
    * features: [none]
  R stackless-bytecode-generator 0.1.0 (workspace, path 'language/move-prover/stackless-bytecode-generator')
    * (old features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode 0.1.0 (workspace, path 'language/move-prover/bytecode')
    * features: [none]
  R stackless-bytecode-generator 0.1.0 (workspace, path 'language/move-prover/stackless-bytecode-generator')
    * (old features: [none])
```

**Review by shazqadeer — APPROVED** [review]

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A bytecode 0.1.0 (workspace, path 'language/move-prover/bytecode')
    * features: [none]
  R stackless-bytecode-generator 0.1.0 (workspace, path 'language/move-prover/stackless-bytecode-generator')
    * (old features: [none])
```

**Pull request closed without merging**
