### PR TITLE
[cluster-test] standardize bin name and argument parsing

### PR DESCRIPTION
**Pull request by bmwill**
Continue #1119 and standardize cluster-test name and use StructOpt for argument parsing.

### CODE REVIEW

**Comment by bmwill** [comment]
I think I need to also change some docker files

**Comment by andll** [comment]
(1) Also need to change build/run shell scripts:
```
diff --git a/docker/cluster_test/build.sh b/docker/cluster_test/build.sh
index 368edce7..2d2c7881 100755
--- a/docker/cluster_test/build.sh
+++ b/docker/cluster_test/build.sh
@@ -21,13 +21,13 @@ else
   docker run --name libra_cluster_test_builder_container -d -i -t -v $DIR/../..:/libra libra_cluster_test_builder bash
 fi
 
-docker exec -i -t libra_cluster_test_builder_container bash -c 'source /root/.cargo/env; cargo build -p cluster_test --target-dir /target && /bin/cp /target/debug/cluster_test target/cluster_test_docker_builder/'
+docker exec -i -t libra_cluster_test_builder_container bash -c 'source /root/.cargo/env; cargo build -p cluster-test --target-dir /target && /bin/cp /target/debug/cluster-test target/cluster_test_docker_builder/'
 
 if [ "$1" = "--build-docker-image" ]; then
-  ln target/cluster_test_docker_builder/cluster_test cluster_test_docker_builder_cluster_test
+  ln target/cluster_test_docker_builder/cluster-test cluster_test_docker_builder_cluster_test
   docker build -f $DIR/cluster_test.Dockerfile $DIR/../.. --tag libra_cluster_test --build-arg GIT_REV="$(git rev-parse HEAD)" --build-arg GIT_UPSTREAM="$(git merge-base HEAD origin/master)" --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" $PROXY
   rm cluster_test_docker_builder_cluster_test
 else
   echo "Not building docker container, run with --build-docker-image to build docker image"
-  echo "Built binary is in target/cluster_test_docker_builder/cluster_test"
+  echo "Built binary is in target/cluster_test_docker_builder/cluster-test"
 fi
diff --git a/docker/cluster_test/run.sh b/docker/cluster_test/run.sh
index b9998a10..6643332c 100644
--- a/docker/cluster_test/run.sh
+++ b/docker/cluster_test/run.sh
@@ -3,7 +3,7 @@ export ALLOW_DEPLOY=yes
 unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
 
 mv run.out run.out.bak || echo 'run.out does not exist'
-if ! ./cluster_test --workplace cluster-test --run > run.out ; then
+if ! ./cluster-test --workplace cluster-test --run > run.out ; then
   REQUEST=\{\"text\":\"cluster_test\ terminated\"\}
   curl -X POST -H 'Content-type: application/json' --data "$REQUEST" "$SLACK_URL"
   exit 1
```

Ideally after this also verify that `docker/cluster_test/build.sh` builds.

(2) Also, do we want to rename this `docker/cluster_test/` dir as well?

**Comment by andll** [comment]
@bors-libra r+
Thanks, @bmwill !

**Pull request closed without merging**
