### PR TITLE
[rust] update to 1.47.0 and cargo to nightly-2020-10-09

### PR DESCRIPTION
**Pull request by rexhoffman**
## Motivation

Update the default rust toolchain (rustc/clippy/etc.) except for our cargo version.

### Have you read the [Contributing Guidelines on pull requests]

Yes

## Test Plan

CI

## Related PRs

None

### CODE REVIEW

**Comment by rexhoffman** [comment]
The cargo lock file changes are a no-op reordering.   Not sure why the ordering changed.

**Review by metajack — APPROVED** [review]

**Comment by bmwill** [comment]
Based on some local testing I think we're going to have to update the nightly version of cargo we're using in order to not run into this issue.

**Pull request closed without merging**
