### PR TITLE
[json-rpc] spec file

### PR DESCRIPTION
**Pull request by phoenix-antigravity**

### CODE REVIEW

**Comment by aching** [comment]
This renders beautifully.  @archjayas, you can see the MD preview from GitHub here -

https://github.com/phoenix-antigravity/libra/blob/json-rpc-spec/json-rpc/json-rpc-spec.md

**Comment by davidiw** [comment]
Very nice! Is there any reason to not include the proof methods?

**Comment by phoenix-antigravity** [comment]
> Very nice! Is there any reason to not include the proof methods

good question! second layer API (that returns proofs) is not fully finished yet. Only couple of endpoints are implemented and didn't go through review. We expect in closest future few more updates to spec file

**Pull request closed without merging**
