### PR TITLE
[scripts] Updates to the dependency-checking script

### PR DESCRIPTION
**Pull request by huitseeker**
- mentions removed deps in commit msg,
- test all features

## Test
script only

### CODE REVIEW

**Comment by metajack** [comment]
I had no idea this existed. You mention cargo-outdated, but that does not appear to be used. Can you put in a comment explaining what the awk regex is trying to do?

**Comment by huitseeker** [comment]
@metajack Sorry, I brain-farted on cargo-outdated, which is not used here (but in anothe neighboring script)
I added the comment as requested.

**Comment by metajack** [comment]
What is/was the `default-features` and `version` stuff doing? Why filter out those lines?

**Comment by huitseeker** [comment]
@metajack we used to have 'unrolled' dependency specifications, with a block for a single dependency in the `Cargo.toml`, which would lead us to `cargo-edit` the versioning of the "version" and "default-features" thought-to-be packages. 

Of course now that's not quite the format of our `Cargo.toml` files, so I've removed the `grep -v` portion referring to that.

**Pull request closed without merging**
