### PR TITLE
[language] Remove compiler support for move_to_sender/get_txn_sender

### PR DESCRIPTION
**Pull request by bob-wilson**
Transaction::sender was the last remaining "fake native" function, so the fake_natives code can also go away now.

## Motivation

Cleaning up obsolete features!

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Updated tests and confirmed that they pass

### CODE REVIEW

**Comment by bob-wilson** [comment]
This can't land until some of the prover tests get updated, so I'm marking it as a draft. I'm not aware of any changes needed in the code, though.

**Comment by tnowacki** [comment]
Didn't notice this is still in draft :p 

Nonetheless, its going to be a big red diff, if tests pass, land it

**Comment by bob-wilson** [comment]
This is now blocked on #4833

**Comment by bob-wilson** [comment]
This is unblocked now.

**Pull request closed without merging**
