### PR TITLE
Add Google verification file

### PR DESCRIPTION
**Pull request by JoelMarcey**
## Motivation

So we can verify the domain with Google tools

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

N/A

## Related PRs

N/A

### CODE REVIEW

**Review by ericnakagawa — APPROVED** [review]
LGTM

**Comment by JoelMarcey** [comment]
@bmwill Do you need to approve this for this to land?

**Comment by JoelMarcey** [comment]
@sausagee Could you please approve this? This is for the developers.libra.org site. Could we create a gatekeeper exception for changes made to the `developers.libra.org` directory?

**Review by sausagee — APPROVED** [review]

**Pull request closed without merging**
