### PR TITLE
[config] explicit getters for OnChainConfig

### PR DESCRIPTION
**Pull request by agc-quadra**
## Motivation

This is a small PR intended to make the usage of OnChainConfig more readable and explicit.

The change itself makes the parameterized get<T> function private and replaces it with explicit getters for the four config types currently contained in the OnChainConfig.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

(Share your test plan here. If you changed code, please provide us with clear instructions for verifying that your changes work.)

Cosmetic only change, ensure that existing tests continue to pass.

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by davidiw** [comment]
I don't have much skin in this game, passing off to @christinacelee, @phoenix-antigravity, @zekun000 ... the classical API is a little interesting :).

**Comment by zekun000** [comment]
personally I don't feel this makes it more readable, the generics is quite explicit about the types (it needs either let foo: Foo = config.get() or let foo = config.get::<Foo>()) and avoid boiler-plate for future types.

**Comment by agc-quadra** [comment]
> personally I don't feel this makes it more readable, the generics is quite explicit about the types (it needs either let foo: Foo = config.get() or let foo = config.get::<Foo>()) and avoid boiler-plate for future types.

Acknowledging that readability is heavily influenced by preference and that bikeshedding the topics is generally not a good use of time, I'll expand on why I believe generic methods (differentiated from generic types) are low on the readability scale.  A decisive :+1: or :-1: will dictate the future of this PR and won't be taken personally in either direction.

1.  [acknowledge] The proposal is a longer definition of the OnChainConfig type and does include additional boilerplate relative to the legacy implementation.  
1. the current interface relies allows for the following code snippet:
    `let config_piece_one = config.get();`
    `let config_piece_two = config.get();`
    `parse_configs(config_piece_one, config_piece_two);`
which type inference will correctly resolve and parse. The client author should use better variable names and `config.get::<VMConfig>()` and reviewers should squawk if that is not the case.  But that relies on human discipline moving forward, which is always dangerous.  (Note that for the author of client code, `config.vm_config()` has a marginally better code golf score.)
1.  The current `get<T>` implementation allows users of the OnChainConfig struct to invoke `get` for any type with a `CONFIG_ID`, even if that type is not a part of OnChainConfig.  This behavior can lead to maintenance pain as configs are added/removed over time as the resulting error is indistinguishable from a case where the requested type is stored but not available.  If unit tests are not sufficient, this error can very easily lead to production suffering.  The proposed interface does not eliminate this problem entirely as a field can be replaced without updating the explicit getter, but it dos mean that properly performed updates to OnChainConfig will result in compilation errors in any calling code.   This explicitly highlights a choice between consolidating the maintenance complexity of OnChainConfig to on_chain_config.rs or distributing that complexity amongst all calling locations.
1.  Generic types, i.e. `vector<T>`, also have function signatures akin to `T get<T>`.  The key difference between the generic type `get` of vector and the generic method `get` of OnChainConfig is that the former uses the generic to define the type for the collection while the latter uses the generic to select between different internal fields of the struct.  Generic type, are (per collection) straightforward and core knowledge for any Rust or C++ programmer at this point in time;  generic methods require expertise of level ~8 (out of 10) to understand and use well.  While there are occasional benefits to relying on expert language features from time to time, I've typically found it easier to (a) understand, (b) contribute to, and (c) maintain in production codebases which are restricted to language features at expertise level 6 or below.   

The underlying question of this PR is a calibration question to better understand the assumed language proficiency of people reading/contributing to/running the codebase.

**Comment by zekun000** [comment]
@agc-quadra thanks for your thoughtful comment, here's some additional thoughts

2) type erasure, if the compiler is able to erase the type, I think it's reasonable for readers too (with a good var name)
3) better errors, the generic on the getter is bound by the trait OnChainConfig which should be the source of truth. In order to use the type, the author has to impl the trait first, otherwise it's a compile error. I'd argue it's easier to maintain one source of truth instead of both the trait and the explicit getter. thus the value of the explicit getter would be much more if we don't have such trait bound.
4) it's a heterogeneous generic use case instead of homogeneous one like vector.

**Comment by agc-quadra** [comment]
@zekun000 Thanks for the additional thoughts.  The discussion certainly falls into a gray area with no clear right/wrong answer.   

Unless somebody speaks up in favor, I will close this PR in 24 hours.

**Comment by agc-quadra** [comment]
Closing PR per previous comment.

**Pull request closed without merging**
