### PR TITLE
upgrade to ureq 1.1 manually

### PR DESCRIPTION
**Pull request by davidiw**
This has some killer new features that are required for secure storage... will add the functionality in a bit :)

### CODE REVIEW

**Comment by davidiw** [comment]
@bors-libra r=bmwills

what a stubborn system....

**Comment by davidiw** [comment]
Clearly, I'm going to need to fix this smoke test -- my solution in another pr didn't quite do it :/

@bors-libra r=bmwills

**Comment by bmwill** [comment]
@davidiw idk who `bmwills` :P

**Pull request closed without merging**
