### PR TITLE
[benchmark] Make debug_address non-required argument.

### PR DESCRIPTION
**Pull request by littlepretty**
## Summary:
Currently debug interface is not used inside RuBen (#353 ). However, it still exist in CLI arguments.
As an intermediate step for totally removing `debug_address` from RuBen, this PR make it safe for `debug_address` to be
both present and absent.

The next step will be remove this argument from RuBen when Docker script is updated.

## Test Plan:
Tested with following RuBen commands for both present and absent:

### when running as local mode
```
./target/release/ruben -f faucet_for_ruben -s temp_config  -m localhost:45345
./target/release/ruben -f faucet_for_ruben -s temp_config  -m localhost:45345 -d facebook
```

### when running as remote mode
```
./target/release/ruben -f /tmp/yjq/keypair.Cfr6hzZridAH/temp_faucet_keys \
-a localhost:47715 localhost:48839 localhost:36203 localhost:46667 \
-m localhost:45345
./target/release/ruben -f /tmp/yjq/keypair.Cfr6hzZridAH/temp_faucet_keys \
-a localhost:47715 localhost:48839 localhost:36203 localhost:46667 \
-m localhost:45345 \
-d facebook
```

### CODE REVIEW

**Comment by littlepretty** [comment]
Address conflict and rebase

**Comment by fbandersnatch** [comment]
Can you sweep through the code and delete all mentions of debug client? 
It's still documented as something we use in benchmark

**Comment by 0-o-0** [comment]
I merged #355, please update bench_init.sh to remove the -debug client parameter as well

**Comment by littlepretty** [comment]
Remove `debug node interface` in `lib.rs`.

**Pull request merged**
