### PR TITLE
[decoupled-execution] Unhappy Path - Synchronization (5)

### PR DESCRIPTION
**Pull request by ankitkacn**
### **Motivation**
Add Round Synchronisation(faulty leader execution, timeout)  feature for the decoupled execution.

* Decouple block tree ```root_id``` into ```ordered_root_id``` and ```commit_root_id```
* Add a field ```highest_commit_decision_ledger_info``` to ```SyncInfo``` ```BlockStore::fast_forward_sync``` now fetches all the block starting from ```highest_commit_decision_ledger_info``` to ```highest_commit_cert.commit_info()``` + 2 (namely, the ```certified_block```).
*  Fix an issue that BlockStore::build does not try to commit blocks

### **Test Plan**

Safety testcases, liveness testcases are updated to test Round Synchronisation under  decoupled execution.

### CODE REVIEW

**Comment by KoushikGavini** [comment]
@ankitkacn  please update testplan, motivation, etc from standard template.

**Review by KoushikGavini — APPROVED** [review]

**Review by KoushikGavini — APPROVED** [review]

**Review by KoushikGavini — APPROVED** [review]

**Comment by joejenniges** [comment]
AB#6049

**Pull request closed without merging**
