### PR TITLE
[cluster-test] add failpoints into executor

### PR DESCRIPTION
**Pull request by lightmark**
## Motivation

follow https://github.com/libra/libra/pull/5957

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Y
## Test Plan

ENABLE_FAILPOINTS=1 ./scripts/cti --pr 6027 --run bench

### CODE REVIEW

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A fail 0.4.0 (direct third-party, crates.io)
    * features: [none]
  M log 0.4.11 (direct third-party, crates.io)
    * added features: std
    * (unchanged features: serde)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A fail 0.4.0 (direct third-party, crates.io)
    * features: [none]
  M log 0.4.11 (direct third-party, crates.io)
    * added features: std
    * (unchanged features: serde)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A fail 0.4.0 (direct third-party, crates.io)
    * features: [none]
  M log 0.4.11 (direct third-party, crates.io)
    * added features: std
    * (unchanged features: serde)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A fail 0.4.0 (direct third-party, crates.io)
    * features: [none]
  M log 0.4.11 (direct third-party, crates.io)
    * added features: std
    * (unchanged features: serde)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A fail 0.4.0 (direct third-party, crates.io)
    * features: [none]
  M log 0.4.11 (direct third-party, crates.io)
    * added features: std
    * (unchanged features: serde)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A fail 0.4.0 (direct third-party, crates.io)
    * features: [none]
  M log 0.4.11 (direct third-party, crates.io)
    * added features: std
    * (unchanged features: serde)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A fail 0.4.0 (direct third-party, crates.io)
    * features: [none]
  M log 0.4.11 (direct third-party, crates.io)
    * added features: std
    * (unchanged features: serde)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A fail 0.4.0 (direct third-party, crates.io)
    * features: [none]
  M log 0.4.11 (direct third-party, crates.io)
    * added features: std
    * (unchanged features: serde)
```

**Comment by lightmark** [comment]
Experiment Result: all up : 845 TPS, 5362 ms latency, 8200 ms p99 latency, no expired txns

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A fail 0.4.0 (direct third-party, crates.io)
    * features: [none]
  M log 0.4.11 (direct third-party, crates.io)
    * added features: std
    * (unchanged features: serde)
```

**Review by zekun000 — APPROVED** [review]

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A fail 0.4.0 (direct third-party, crates.io)
    * features: [none]
  M log 0.4.11 (direct third-party, crates.io)
    * added features: std
    * (unchanged features: serde)
```

**Pull request closed without merging**
