### PR TITLE
ci: use Swatinem/rust-cache for caching dependencies #9100

### PR DESCRIPTION
**Pull request by satyamacn**
### Motivation
<html>
<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Use<span> </span><a href="https://github.com/Swatinem/rust-cache" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">https://github.com/Swatinem/rust-cache</a><span> </span>instead of<span> </span><a href="https://github.com/actions/cache" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">https://github.com/actions/cache</a><span> </span>for caching of dependencies.</p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Here are some of the job performance wins</p>

Job | Original | New | Speed Up %
-- | -- | -- | --
lint | 5m 29s | 4m 47s | 18.2%
e2e-test-0 | 37m 12s | 28m 32s | 30.0%
e2e-test-1 | 35m 33s | 26m 51s | 32.4%
crypto-unit-test | 10m 35s | 4m 31s | 134.3%

</body>
</html>

### Test Plan 
CI/CD Tests were performed

--------------

### CODE REVIEW

**Review by dhaneshacn — APPROVED** [review]

**Comment by satyamacn** [comment]
Closing this PR due to technical issue.

**Pull request closed without merging**
