### PR TITLE
[Import Fix] Merge imports in the Libra codebase using the nightly cargo build.

### PR DESCRIPTION
**Pull request by JoshLind**
## Motivation

At present, 'cargo fmt' doesn't automatically merge imports for rust files. While this feature is available in the nightly build of cargo, the general consensus is that we shouldn't enforce this requirement until it is accepted in stable. Moreover, it seems that people are reluctant to include a lint rule that checks this property (although, consensus has yet to be achieved here)... Until then, I figure I may as well submit periodic PRs that clean up the imports.

Is this PR useful? Personally, I think so. Looking at the changes below, it's clear that imports can easily become messy, and this PR took me less than a minute to generate, write, and submit.

Note: this PR was generated by running: 'cargo +nightly fmt -- --config merge_imports=true'. This does not affect import lines in a file that are separated by several newlines (e.g., imports at the top of a file are not automatically merged with those declared later on).

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

All local tests pass.

## Related PRs

None.

### CODE REVIEW

**Comment by zekun000** [comment]
last time we got complains about people have to rebase all the current work on top of this

**Comment by thefallentree** [comment]
What’s the point? It does nothing to either performance or productivity, except to make merge conflict more often and painful to resolve.

What is the point?

Yucong Sun, Libra PE
________________________________

**Comment by bmwill** [comment]
#2926 Should address this

**Comment by davidiw** [comment]
Gonna close this out as we now have this as part of our workflow per @bmwill

**Pull request closed without merging**
