### PR TITLE
[CI] retry and flag flaky E2E tests

### PR DESCRIPTION
**Pull request by sausagee**
## Motivation
We had two flaky e2e tests last week `smoke_test_single_node_block_metadata` and `basic_state_synchronization`.  They were fixed, however, we have couple more this week, `test_basic_restartability` (https://circleci.com/gh/libra/libra/63762#tests/containers/4), `test_startup_sync_state_with_empty_consensus_db` (https://circleci.com/gh/libra/libra/63425#tests/containers/7), `test_basic_state_synchronization` (https://circleci.com/gh/libra/libra/63083#tests/containers/5). These tests seem to pass if they are run again.

CI can retry these tests locally to unblock the land and alleviate developer frustration. The flaky tests are then flagged to test owners so that they can look into the underlying issue.

Summary of changes:
- Add a retry loop to the run-e2e-test step
- Use a 6-minute timeout when each test is run.  This is to catch and kill stuck libra-swarm. For example, https://circleci.com/gh/libra/libra/62777
- Use a file to pass message payload between commands in yaml. yaml doesn't support arg passing at runtime, circumventing it via Circle's bash env var between container layers results loss in message formatting (no space, newline).  

## Test Plan
Canary with 3f0e30c in https://circleci.com/workflow-run/1e778b6b-ccf4-4d2a-9063-d0ae4ba73f2f. Jobs unrelated to e2e tests in the regular commit verify workflow are stripped.

Testcases
- Intentionally fail `smoke_test::test_basic_restartability`. Verify the retry logic works with known-fail tests in https://circleci.com/gh/libra/libra/63816#tests/containers/4
- Reduce test timeout to 180sec.  Verify some tests would pass in second try: https://circleci.com/gh/libra/libra/63816#tests/containers/4, https://circleci.com/gh/libra/libra/63816#tests/containers/5
- Verify the flaky tests are posted to #flaky-test
- Verify the embedded link in the message points to the specific container node in Circle where the flaky test ran. The test owner can examine the log and diagnosis the issue.

### CODE REVIEW

**Comment by rexhoffman** [comment]
There are a couple of output improvements I'd have like to seen in the e2e tests.   Think theirs a stray set -x, and one of the e2e tests seems to have run two different tests, was trying to understand that.

**Comment by rexhoffman** [comment]
Ahh seems we bucket e2e tests in to the 8 targets, so we'd probably want a line printed at the end of test run that states how many executions each test took to pass.

**Comment by sausagee** [comment]
> There are a couple of output improvements I'd have like to seen in the e2e tests. Think theirs a stray set -x, and one of the e2e tests seems to have run two different tests, was trying to understand that.

I supposed you meant `set -x +e`?   Both `-x` and `+e` are intentional.  

`-x` is to print the cmd used in the retry loop. If I have a magic wand, the retry function should be handle by `cargo test`. 

`+e` is to disable exit immediately in the retry loop. This is for the timeout.  Otherwise, circle will terminate the step immediately when timeout returns non-0.

**Comment by sausagee** [comment]
> Ahh seems we bucket e2e tests in to the 8 targets, so we'd probably want a line printed at the end of test run that states how many executions each test took to pass.

Yep, this is included. The message looks like this 
```
Found flaky tests
smoke_test::test_basic_state_synchronization passed after 2 tries
```
Its is included in two places:
- in the same test-running step (via stdout) in circle before container layer exists;
- in the message payload sent to #flaky-test (not disclosed here).  This message also includes link to the specific circle container (or runner) that the test ran.

**Pull request closed without merging**
