### PR TITLE
[backup] backup coordinator: new strategy for txn batching

### PR DESCRIPTION
**Pull request by msmouse**
## Motivation

With txn batch size at 100, now we produce txn batches (0, 99), (100, 199), ..., (900, 999), (1000, 1099), ...
Which is not ideal.
Consider this:  With state snapshot interval at 1000, we have state snapshots at 0, 1000, 2000, ...
Assume the chain is at version 1090, so the (1000, 1099) txn batch hasn't showed up yet. Now, let's restore to the latest possible versions supported by the backups -- surprisingly, the latest snapshot can't be used, because there's no txn at that version or on top of it.

This commit shifts the txn batches by 1 -- make the genesis txn into it's own backup -- and there is no longer such issue. I think the new strategy makes more sense.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?
Y

## Test Plan
existing coverage.  play locally.

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/libra/developers.libra.org, and link to your PR here.)

### CODE REVIEW

**Comment by lightmark** [comment]
lol, it is more like a bug imo.

**Review by lightmark — APPROVED** [review]

**Comment by msmouse** [comment]
> lol, it is more like a bug imo.

🏃‍♀️

**Pull request closed without merging**
