### PR TITLE
[move source language] Added constant folding

### PR DESCRIPTION
**Pull request by tnowacki**
- Updated optimization of functions to a loop
- Added constant folding optimization
- Only folds unary ops, binary ops, and casts

## Motivation

- Needed for constants

## Test Plan

- Utilizing existing tests in #4513
- Might add another short, but exhaustive (over operators), test

### CODE REVIEW

**Comment by tnowacki** [comment]
@wrwg @junkil-park Can you take a look at the changed tests for `stackless-bytecode-generator`? Let me know if the update is fine, or if you need the optimizations turned off for these tests

**Comment by wrwg** [comment]
I’m out. Shaz is the guy for this codr

________________________________

**Comment by tnowacki** [comment]
@shazqadeer Same question. Is this update safe, or should we turn off optimizations for these?

**Comment by shazqadeer** [comment]
The updates are fine (as long at the Boogie/Z3 tests for the Move prover are all working).

**Pull request closed without merging**
