### PR TITLE
[mempool] parallel validation

### PR DESCRIPTION
**Pull request by zekun000**
## Motivation

It doesn't improve the overall tps, but it reduces the vm_validation latency from ~10ms to ~3ms, the change seems simple enough to merge in.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Y

## Test Plan

canary.

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/libra/developers.libra.org, and link to your PR here.)

### CODE REVIEW

**Review by davidiw — APPROVED** [review]
I really hate our rayon dependency, but if we're gonna fix that, we have other places to fix that are more critical than this.

**Comment by zekun000** [comment]
I think I messed up the branch, closing_

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  A cfg-if 1.0.0 (transitive third-party, crates.io) (other versions: 0.1.10)
    * features: [none]
  A cipher 0.2.5 (transitive third-party, crates.io)
    * features: [none]
  A ctr 0.6.0 (transitive third-party, crates.io)
    * features: [none]
  A form_urlencoded 1.0.0 (transitive third-party, crates.io)
    * features: [none]
  A pin-project 0.4.27 (transitive third-party, crates.io)
    * features: [none]
  A pin-project 1.0.1 (transitive third-party, crates.io)
    * features: [none]
  A tracing-futures 0.2.4 (transitive third-party, crates.io)
    * features: pin-project, std-future
  M aes-gcm 0.8.0 (direct third-party, crates.io)
    * version upgraded from 0.7.0
    * (unchanged features: aes, alloc, default)
  M anyhow 1.0.34 (direct third-party, crates.io)
    * version upgraded from 1.0.33
    * (unchanged features: default, std)
  M futures 0.3.8 (direct third-party, crates.io)
    * version upgraded from 0.3.6
    * (unchanged features: alloc, async-await, default, executor, futures-executor, std)
  M hyper 0.13.9 (direct third-party, crates.io)
    * version upgraded from 0.13.8
    * (unchanged features: default, runtime, socket2, stream, tcp)
  M native-tls 0.2.5 (direct third-party, crates.io)
    * version upgraded from 0.2.4
    * (unchanged features: [none])
  M radix_trie 0.2.1 (direct third-party, crates.io)
    * version upgraded from 0.2.0
    * (unchanged features: [none])
  M rayon 1.5.0 (direct third-party, crates.io)
    * version upgraded from 1.4.1
    * (unchanged features: [none])
  M ref-cast 1.0.3 (direct third-party, crates.io)
    * version upgraded from 1.0.2
    * (unchanged features: [none])
  M serde 1.0.117 (direct third-party, crates.io)
    * version upgraded from 1.0.116
    * (unchanged features: default, derive, rc, serde_derive, std)
  M serde_json 1.0.59 (direct third-party, crates.io)
    * version upgraded from 1.0.58
    * (unchanged features: default, std)
  M serde_yaml 0.8.14 (direct third-party, crates.io)
    * version upgraded from 0.8.13
    * (unchanged features: [none])
  M sha2 0.9.2 (direct third-party, crates.io)
    * version upgraded from 0.9.1
    * (unchanged features: default, std)
  M structopt 0.3.20 (direct third-party, crates.io)
    * version upgraded from 0.3.18
    * (unchanged features: default)
  M thiserror 1.0.22 (direct third-party, crates.io)
    * version upgraded from 1.0.21
    * (unchanged features: [none])
  M ureq 1.5.2 (direct third-party, crates.io)
    * version upgraded from 1.5.1
    * (unchanged features: json, native-tls, serde, serde_json)
  M aes 0.6.0 (transitive third-party, crates.io)
    * version upgraded from 0.5.0
    * (unchanged features: [none])
  M aesni 0.10.0 (transitive third-party, crates.io)
    * version upgraded from 0.8.0
    * (unchanged features: [none])
  M aho-corasick 0.7.15 (transitive third-party, crates.io)
    * version upgraded from 0.7.13
    * (unchanged features: default, std)
  M chunked_transfer 1.3.0 (transitive third-party, crates.io)
    * version upgraded from 1.2.0
    * (unchanged features: [none])
  M crossbeam-channel 0.5.0 (transitive third-party, crates.io)
    * version upgraded from 0.4.4
    * added features: crossbeam-utils, default, std
    * (unchanged features: [none])
  M crossbeam-deque 0.8.0 (transitive third-party, crates.io)
    * version upgraded from 0.7.3
    * added features: crossbeam-epoch, crossbeam-utils, default, std
    * (unchanged features: [none])
  M crossbeam-epoch 0.9.0 (transitive third-party, crates.io)
    * version upgraded from 0.8.2
    * added features: alloc
    * removed features: default
    * (unchanged features: lazy_static, std)
  M crossbeam-utils 0.8.0 (transitive third-party, crates.io)
    * version upgraded from 0.7.2
    * (unchanged features: default, lazy_static, std)
  M ed25519 1.0.3 (transitive third-party, crates.io)
    * version upgraded from 1.0.1
    * (unchanged features: serde, std)
  M either 1.6.1 (transitive third-party, crates.io)
    * version upgraded from 1.6.0
    * (unchanged features: [none])
  M encoding_rs 0.8.26 (transitive third-party, crates.io)
    * version upgraded from 0.8.24
    * (unchanged features: [none])
  M futures-channel 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.6
    * (unchanged features: alloc, default, futures-sink, sink, std)
  M futures-core 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.6
    * (unchanged features: alloc, default, std)
  M futures-executor 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.6
    * (unchanged features: std)
  M futures-io 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.6
    * (unchanged features: std)
  M futures-sink 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.6
    * (unchanged features: alloc, default, std)
  M futures-task 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.6
    * (unchanged features: alloc, once_cell, std)
  M futures-util 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.6
    * (unchanged features: alloc, async-await, async-await-macro, channel, futures-channel, futures-io, futures-macro, futures-sink, io, memchr, proc-macro-hack, proc-macro-nested, sink, slab, std)
  M h2 0.2.7 (transitive third-party, crates.io)
    * version upgraded from 0.2.6
    * (unchanged features: [none])
  M hashbrown 0.9.1 (transitive third-party, crates.io)
    * version upgraded from 0.8.2
    * (unchanged features: raw)
  M indexmap 1.6.0 (transitive third-party, crates.io)
    * version upgraded from 1.5.1
    * (unchanged features: [none])
  M instant 0.1.8 (transitive third-party, crates.io)
    * version upgraded from 0.1.6
    * (unchanged features: [none])
  M libc 0.2.80 (transitive third-party, crates.io)
    * version upgraded from 0.2.79
    * (unchanged features: default, std)
  M memchr 2.3.4 (transitive third-party, crates.io)
    * version upgraded from 2.3.3
    * (unchanged features: default, std, use_std)
  M memoffset 0.5.6 (transitive third-party, crates.io)
    * version upgraded from 0.5.5
    * (unchanged features: default)
  M net2 0.2.35 (transitive third-party, crates.io)
    * version upgraded from 0.2.34
    * (unchanged features: default, duration)
  M num-integer 0.1.44 (transitive third-party, crates.io)
    * version upgraded from 0.1.43
    * (unchanged features: [none])
  M num-traits 0.2.14 (transitive third-party, crates.io)
    * version upgraded from 0.2.12
    * (unchanged features: [none])
  M pin-project-lite 0.1.11 (transitive third-party, crates.io)
    * version upgraded from 0.1.7
    * (unchanged features: [none])
  M polyval 0.4.1 (transitive third-party, crates.io)
    * version upgraded from 0.4.0
    * (unchanged features: [none])
  M ppv-lite86 0.2.10 (transitive third-party, crates.io)
    * version upgraded from 0.2.9
    * (unchanged features: simd, std)
  M rayon-core 1.9.0 (transitive third-party, crates.io)
    * version upgraded from 1.8.1
    * (unchanged features: [none])
  M regex 1.4.2 (transitive third-party, crates.io)
    * version upgraded from 1.3.9
    * (unchanged features: aho-corasick, default, memchr, perf, perf-cache, perf-dfa, perf-inline, perf-literal, std, thread_local, unicode, unicode-age, unicode-bool, unicode-case, unicode-gencat, unicode-perl, unicode-script, unicode-segment)
  M regex-syntax 0.6.21 (transitive third-party, crates.io)
    * version upgraded from 0.6.18
    * (unchanged features: default, unicode, unicode-age, unicode-bool, unicode-case, unicode-gencat, unicode-perl, unicode-script, unicode-segment)
  M signal-hook-registry 1.2.2 (transitive third-party, crates.io)
    * version upgraded from 1.2.1
    * (unchanged features: [none])
  M socket2 0.3.15 (transitive third-party, crates.io)
    * version upgraded from 0.3.12
    * (unchanged features: [none])
  M tracing 0.1.21 (transitive third-party, crates.io)
    * version upgraded from 0.1.19
    * (unchanged features: log, std)
  M tracing-core 0.1.17 (transitive third-party, crates.io)
    * version upgraded from 0.1.15
    * (unchanged features: lazy_static, std)
  M url 2.2.0 (transitive third-party, crates.io)
    * version upgraded from 2.1.1
    * (unchanged features: [none])
  M zeroize 1.1.1 (transitive third-party, crates.io)
    * version upgraded from 1.1.0
    * (unchanged features: alloc, zeroize_derive)
  R arc-swap 0.4.7 (transitive third-party, crates.io)
    * (old features: [none])
  R block-cipher 0.8.0 (transitive third-party, crates.io)
    * (old features: [none])
  R maybe-uninit 2.0.0 (transitive third-party, crates.io)
    * (old features: [none])
  R pin-project 0.4.26 (transitive third-party, crates.io)
    * (old features: [none])

host packages:
  A const_fn 0.4.3 (transitive third-party, crates.io)
    * features: [none]
  A pin-project-internal 0.4.27 (transitive third-party, crates.io)
    * features: [none]
  A pin-project-internal 1.0.1 (transitive third-party, crates.io)
    * features: [none]
  M enum_dispatch 0.3.4 (direct third-party, crates.io)
    * version upgraded from 0.3.3
    * (unchanged features: [none])
  M syn 1.0.48 (direct third-party, crates.io)
    * version upgraded from 1.0.42
    * (unchanged features: clone-impls, default, derive, extra-traits, full, parsing, printing, proc-macro, quote, visit, visit-mut)
  M cc 1.0.62 (transitive third-party, crates.io)
    * version upgraded from 1.0.60
    * (unchanged features: [none])
  M futures-macro 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.6
    * (unchanged features: [none])
  M pkg-config 0.3.19 (transitive third-party, crates.io)
    * version upgraded from 0.3.18
    * (unchanged features: [none])
  M proc-macro-hack 0.5.19 (transitive third-party, crates.io)
    * version upgraded from 0.5.18
    * (unchanged features: [none])
  M ref-cast-impl 1.0.3 (transitive third-party, crates.io)
    * version upgraded from 1.0.2
    * (unchanged features: [none])
  M serde_derive 1.0.117 (transitive third-party, crates.io)
    * version upgraded from 1.0.116
    * (unchanged features: default)
  M structopt-derive 0.4.13 (transitive third-party, crates.io)
    * version upgraded from 0.4.11
    * (unchanged features: [none])
  M thiserror-impl 1.0.22 (transitive third-party, crates.io)
    * version upgraded from 1.0.21
    * (unchanged features: [none])
  M zeroize_derive 1.0.1 (transitive third-party, crates.io)
    * version upgraded from 1.0.0
    * (unchanged features: [none])
  R pin-project-internal 0.4.26 (transitive third-party, crates.io)
    * (old features: [none])
```

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  A cfg-if 1.0.0 (transitive third-party, crates.io) (other versions: 0.1.10)
    * features: [none]
  A cipher 0.2.5 (transitive third-party, crates.io)
    * features: [none]
  A ctr 0.6.0 (transitive third-party, crates.io)
    * features: [none]
  A form_urlencoded 1.0.0 (transitive third-party, crates.io)
    * features: [none]
  M aes-gcm 0.8.0 (direct third-party, crates.io)
    * version upgraded from 0.7.0
    * (unchanged features: aes, alloc, default)
  M anyhow 1.0.34 (direct third-party, crates.io)
    * version upgraded from 1.0.33
    * (unchanged features: default, std)
  M backtrace 0.3.54 (direct third-party, crates.io)
    * version upgraded from 0.3.51
    * (unchanged features: addr2line, default, gimli-symbolize, miniz_oxide, object, std)
  M native-tls 0.2.5 (direct third-party, crates.io)
    * version upgraded from 0.2.4
    * (unchanged features: [none])
  M radix_trie 0.2.1 (direct third-party, crates.io)
    * version upgraded from 0.2.0
    * (unchanged features: [none])
  M ref-cast 1.0.3 (direct third-party, crates.io)
    * version upgraded from 1.0.2
    * (unchanged features: [none])
  M serde 1.0.117 (direct third-party, crates.io)
    * version upgraded from 1.0.116
    * (unchanged features: default, derive, rc, serde_derive, std)
  M serde_json 1.0.59 (direct third-party, crates.io)
    * version upgraded from 1.0.58
    * (unchanged features: default, std)
  M serde_yaml 0.8.14 (direct third-party, crates.io)
    * version upgraded from 0.8.13
    * (unchanged features: [none])
  M sha2 0.9.2 (direct third-party, crates.io)
    * version upgraded from 0.9.1
    * (unchanged features: default, std)
  M thiserror 1.0.22 (direct third-party, crates.io)
    * version upgraded from 1.0.21
    * (unchanged features: [none])
  M toml 0.5.7 (direct third-party, crates.io)
    * version upgraded from 0.5.6
    * (unchanged features: default)
  M ureq 1.5.2 (direct third-party, crates.io)
    * version upgraded from 1.5.1
    * (unchanged features: json, native-tls, serde, serde_json)
  M addr2line 0.14.0 (transitive third-party, crates.io)
    * version upgraded from 0.13.0
    * (unchanged features: [none])
  M aes 0.6.0 (transitive third-party, crates.io)
    * version upgraded from 0.5.0
    * (unchanged features: [none])
  M aesni 0.10.0 (transitive third-party, crates.io)
    * version upgraded from 0.8.0
    * (unchanged features: [none])
  M aho-corasick 0.7.15 (transitive third-party, crates.io)
    * version upgraded from 0.7.13
    * (unchanged features: default, std)
  M chunked_transfer 1.3.0 (transitive third-party, crates.io)
    * version upgraded from 1.2.0
    * (unchanged features: [none])
  M ed25519 1.0.3 (transitive third-party, crates.io)
    * version upgraded from 1.0.1
    * (unchanged features: serde, std)
  M either 1.6.1 (transitive third-party, crates.io)
    * version upgraded from 1.6.0
    * (unchanged features: [none])
  M gimli 0.23.0 (transitive third-party, crates.io)
    * version upgraded from 0.22.0
    * (unchanged features: read)
  M instant 0.1.8 (transitive third-party, crates.io)
    * version upgraded from 0.1.6
    * (unchanged features: [none])
  M libc 0.2.80 (transitive third-party, crates.io)
    * version upgraded from 0.2.79
    * (unchanged features: default, std)
  M memchr 2.3.4 (transitive third-party, crates.io)
    * version upgraded from 2.3.3
    * (unchanged features: default, std, use_std)
  M miniz_oxide 0.4.3 (transitive third-party, crates.io)
    * version upgraded from 0.4.1
    * (unchanged features: [none])
  M num-integer 0.1.44 (transitive third-party, crates.io)
    * version upgraded from 0.1.43
    * (unchanged features: [none])
  M num-traits 0.2.14 (transitive third-party, crates.io)
    * version upgraded from 0.2.12
    * (unchanged features: [none])
  M object 0.22.0 (transitive third-party, crates.io)
    * version upgraded from 0.20.0
    * added features: archive
    * (unchanged features: coff, elf, macho, pe, read_core, unaligned)
  M polyval 0.4.1 (transitive third-party, crates.io)
    * version upgraded from 0.4.0
    * (unchanged features: [none])
  M ppv-lite86 0.2.10 (transitive third-party, crates.io)
    * version upgraded from 0.2.9
    * (unchanged features: simd, std)
  M regex 1.4.2 (transitive third-party, crates.io)
    * version upgraded from 1.3.9
    * (unchanged features: aho-corasick, default, memchr, perf, perf-cache, perf-dfa, perf-inline, perf-literal, std, thread_local, unicode, unicode-age, unicode-bool, unicode-case, unicode-gencat, unicode-perl, unicode-script, unicode-segment)
  M regex-syntax 0.6.21 (transitive third-party, crates.io)
    * version upgraded from 0.6.18
    * (unchanged features: default, unicode, unicode-age, unicode-bool, unicode-case, unicode-gencat, unicode-perl, unicode-script, unicode-segment)
  M rustc-demangle 0.1.18 (transitive third-party, crates.io)
    * version upgraded from 0.1.16
    * (unchanged features: [none])
  M url 2.2.0 (transitive third-party, crates.io)
    * version upgraded from 2.1.1
    * (unchanged features: [none])
  M zeroize 1.1.1 (transitive third-party, crates.io)
    * version upgraded from 1.1.0
    * (unchanged features: alloc, zeroize_derive)
  R block-cipher 0.8.0 (transitive third-party, crates.io)
    * (old features: [none])

host packages:
  M enum_dispatch 0.3.4 (direct third-party, crates.io)
    * version upgraded from 0.3.3
    * (unchanged features: [none])
  M syn 1.0.48 (direct third-party, crates.io)
    * version upgraded from 1.0.42
    * (unchanged features: clone-impls, default, derive, extra-traits, full, parsing, printing, proc-macro, quote, visit)
  M cc 1.0.62 (transitive third-party, crates.io)
    * version upgraded from 1.0.60
    * (unchanged features: [none])
  M pkg-config 0.3.19 (transitive third-party, crates.io)
    * version upgraded from 0.3.18
    * (unchanged features: [none])
  M ref-cast-impl 1.0.3 (transitive third-party, crates.io)
    * version upgraded from 1.0.2
    * (unchanged features: [none])
  M serde_derive 1.0.117 (transitive third-party, crates.io)
    * version upgraded from 1.0.116
    * (unchanged features: default)
  M thiserror-impl 1.0.22 (transitive third-party, crates.io)
    * version upgraded from 1.0.21
    * (unchanged features: [none])
  M zeroize_derive 1.0.1 (transitive third-party, crates.io)
    * version upgraded from 1.0.0
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  A futures 0.3.8 (direct third-party, crates.io)
    * features: alloc, async-await, default, executor, futures-executor, std
  A pin-project 0.4.27 (direct third-party, crates.io)
    * features: [none]
  A cfg-if 1.0.0 (transitive third-party, crates.io) (other versions: 0.1.10)
    * features: [none]
  A cipher 0.2.5 (transitive third-party, crates.io)
    * features: [none]
  A crossbeam-utils 0.8.0 (transitive third-party, crates.io) (other versions: 0.7.2)
    * features: default, lazy_static, std
  A ctr 0.6.0 (transitive third-party, crates.io)
    * features: [none]
  A form_urlencoded 1.0.0 (transitive third-party, crates.io)
    * features: [none]
  A futures 0.1.30 (transitive third-party, crates.io)
    * features: default, use_std, with-deprecated
  A pin-project 1.0.1 (transitive third-party, crates.io)
    * features: [none]
  M aes-gcm 0.8.0 (direct third-party, crates.io)
    * version upgraded from 0.7.0
    * (unchanged features: aes, alloc, default)
  M anyhow 1.0.34 (direct third-party, crates.io)
    * version upgraded from 1.0.33
    * (unchanged features: default, std)
  M backtrace 0.3.54 (direct third-party, crates.io)
    * version upgraded from 0.3.51
    * (unchanged features: addr2line, default, gimli-symbolize, miniz_oxide, object, std)
  M futures-util 0.3.8 (direct third-party, crates.io)
    * version upgraded from 0.3.6
    * (unchanged features: alloc, async-await, async-await-macro, channel, default, futures-channel, futures-io, futures-macro, futures-sink, io, memchr, proc-macro-hack, proc-macro-nested, sink, slab, std)
  M handlebars 3.5.1 (direct third-party, crates.io)
    * version upgraded from 3.5.0
    * (unchanged features: default)
  M hyper 0.13.9 (direct third-party, crates.io)
    * version upgraded from 0.13.8
    * (unchanged features: default, runtime, socket2, stream, tcp)
  M native-tls 0.2.5 (direct third-party, crates.io)
    * version upgraded from 0.2.4
    * (unchanged features: [none])
  M num 0.3.1 (direct third-party, crates.io)
    * version upgraded from 0.3.0
    * (unchanged features: default, num-bigint, std)
  M num-traits 0.2.14 (direct third-party, crates.io)
    * version upgraded from 0.2.12
    * (unchanged features: default, i128, std)
  M radix_trie 0.2.1 (direct third-party, crates.io)
    * version upgraded from 0.2.0
    * (unchanged features: [none])
  M rayon 1.5.0 (direct third-party, crates.io)
    * version upgraded from 1.4.1
    * (unchanged features: [none])
  M ref-cast 1.0.3 (direct third-party, crates.io)
    * version upgraded from 1.0.2
    * (unchanged features: [none])
  M regex 1.4.2 (direct third-party, crates.io)
    * version upgraded from 1.3.9
    * (unchanged features: aho-corasick, default, memchr, perf, perf-cache, perf-dfa, perf-inline, perf-literal, std, thread_local, unicode, unicode-age, unicode-bool, unicode-case, unicode-gencat, unicode-perl, unicode-script, unicode-segment)
  M serde 1.0.117 (direct third-party, crates.io)
    * version upgraded from 1.0.116
    * (unchanged features: alloc, default, derive, rc, serde_derive, std)
  M serde-generate 0.15.2 (direct third-party, crates.io)
    * version upgraded from 0.15.1
    * (unchanged features: [none])
  M serde_json 1.0.59 (direct third-party, crates.io)
    * version upgraded from 1.0.58
    * (unchanged features: default, std)
  M serde_yaml 0.8.14 (direct third-party, crates.io)
    * version upgraded from 0.8.13
    * (unchanged features: [none])
  M sha2 0.9.2 (direct third-party, crates.io)
    * version upgraded from 0.9.1
    * (unchanged features: default, std)
  M structopt 0.3.20 (direct third-party, crates.io)
    * version upgraded from 0.3.18
    * (unchanged features: default)
  M thiserror 1.0.22 (direct third-party, crates.io)
    * version upgraded from 1.0.21
    * (unchanged features: [none])
  M toml 0.5.7 (direct third-party, crates.io)
    * version upgraded from 0.5.6
    * (unchanged features: default)
  M ureq 1.5.2 (direct third-party, crates.io)
    * version upgraded from 1.5.1
    * (unchanged features: json, native-tls, serde, serde_json)
  M addr2line 0.14.0 (transitive third-party, crates.io)
    * version upgraded from 0.13.0
    * (unchanged features: [none])
  M aes 0.6.0 (transitive third-party, crates.io)
    * version upgraded from 0.5.0
    * (unchanged features: [none])
  M aesni 0.10.0 (transitive third-party, crates.io)
    * version upgraded from 0.8.0
    * (unchanged features: [none])
  M aho-corasick 0.7.15 (transitive third-party, crates.io)
    * version upgraded from 0.7.13
    * (unchanged features: default, std)
  M arrayvec 0.5.2 (transitive third-party, crates.io)
    * version upgraded from 0.5.1
    * (unchanged features: default, std)
  M chunked_transfer 1.3.0 (transitive third-party, crates.io)
    * version upgraded from 1.2.0
    * (unchanged features: [none])
  M crossbeam-channel 0.5.0 (transitive third-party, crates.io)
    * version upgraded from 0.4.4
    * added features: crossbeam-utils, default, std
    * (unchanged features: [none])
  M crossbeam-deque 0.8.0 (transitive third-party, crates.io)
    * version upgraded from 0.7.3
    * added features: crossbeam-epoch, crossbeam-utils, default, std
    * (unchanged features: [none])
  M crossbeam-epoch 0.9.0 (transitive third-party, crates.io)
    * version upgraded from 0.8.2
    * added features: alloc
    * removed features: default
    * (unchanged features: lazy_static, std)
  M ed25519 1.0.3 (transitive third-party, crates.io)
    * version upgraded from 1.0.1
    * (unchanged features: serde, std)
  M either 1.6.1 (transitive third-party, crates.io)
    * version upgraded from 1.6.0
    * (unchanged features: [none])
  M encoding_rs 0.8.26 (transitive third-party, crates.io)
    * version upgraded from 0.8.24
    * (unchanged features: [none])
  M futures-channel 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.6
    * (unchanged features: alloc, default, futures-sink, sink, std)
  M futures-core 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.6
    * (unchanged features: alloc, default, std)
  M futures-executor 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.6
    * (unchanged features: std)
  M futures-io 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.6
    * (unchanged features: default, std)
  M futures-sink 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.6
    * (unchanged features: alloc, default, std)
  M futures-task 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.6
    * (unchanged features: alloc, once_cell, std)
  M gimli 0.23.0 (transitive third-party, crates.io)
    * version upgraded from 0.22.0
    * (unchanged features: read)
  M h2 0.2.7 (transitive third-party, crates.io)
    * version upgraded from 0.2.6
    * (unchanged features: [none])
  M hashbrown 0.9.1 (transitive third-party, crates.io)
    * version upgraded from 0.8.2
    * (unchanged features: raw)
  M indexmap 1.6.0 (transitive third-party, crates.io)
    * version upgraded from 1.5.1
    * (unchanged features: [none])
  M instant 0.1.8 (transitive third-party, crates.io)
    * version upgraded from 0.1.6
    * (unchanged features: [none])
  M libc 0.2.80 (transitive third-party, crates.io)
    * version upgraded from 0.2.79
    * (unchanged features: default, std)
  M memchr 2.3.4 (transitive third-party, crates.io)
    * version upgraded from 2.3.3
    * (unchanged features: default, std, use_std)
  M memoffset 0.5.6 (transitive third-party, crates.io)
    * version upgraded from 0.5.5
    * (unchanged features: default)
  M miniz_oxide 0.4.3 (transitive third-party, crates.io)
    * version upgraded from 0.4.1
    * (unchanged features: [none])
  M net2 0.2.35 (transitive third-party, crates.io)
    * version upgraded from 0.2.34
    * (unchanged features: default, duration)
  M num-bigint 0.3.1 (transitive third-party, crates.io)
    * version upgraded from 0.3.0
    * (unchanged features: std)
  M num-complex 0.3.1 (transitive third-party, crates.io)
    * version upgraded from 0.3.0
    * (unchanged features: std)
  M num-integer 0.1.44 (transitive third-party, crates.io)
    * version upgraded from 0.1.43
    * (unchanged features: i128, std)
  M num-iter 0.1.42 (transitive third-party, crates.io)
    * version upgraded from 0.1.41
    * (unchanged features: i128, std)
  M num-rational 0.3.2 (transitive third-party, crates.io)
    * version upgraded from 0.3.0
    * (unchanged features: num-bigint, num-bigint-std, std)
  M object 0.22.0 (transitive third-party, crates.io)
    * version upgraded from 0.20.0
    * added features: archive
    * (unchanged features: coff, elf, macho, pe, read_core, unaligned)
  M pin-project-lite 0.1.11 (transitive third-party, crates.io)
    * version upgraded from 0.1.7
    * (unchanged features: [none])
  M polyval 0.4.1 (transitive third-party, crates.io)
    * version upgraded from 0.4.0
    * (unchanged features: [none])
  M ppv-lite86 0.2.10 (transitive third-party, crates.io)
    * version upgraded from 0.2.9
    * (unchanged features: simd, std)
  M rayon-core 1.9.0 (transitive third-party, crates.io)
    * version upgraded from 1.8.1
    * (unchanged features: [none])
  M regex-syntax 0.6.21 (transitive third-party, crates.io)
    * version upgraded from 0.6.18
    * (unchanged features: default, unicode, unicode-age, unicode-bool, unicode-case, unicode-gencat, unicode-perl, unicode-script, unicode-segment)
  M rustc-demangle 0.1.18 (transitive third-party, crates.io)
    * version upgraded from 0.1.16
    * (unchanged features: [none])
  M sha-1 0.9.2 (transitive third-party, crates.io) (other versions: 0.8.2)
    * version upgraded from 0.9.1
    * (unchanged features: default, std)
  M signal-hook-registry 1.2.2 (transitive third-party, crates.io)
    * version upgraded from 1.2.1
    * (unchanged features: [none])
  M socket2 0.3.15 (transitive third-party, crates.io)
    * version upgraded from 0.3.12
    * (unchanged features: [none])
  M tracing 0.1.21 (transitive third-party, crates.io)
    * version upgraded from 0.1.19
    * (unchanged features: log, std)
  M tracing-core 0.1.17 (transitive third-party, crates.io)
    * version upgraded from 0.1.15
    * (unchanged features: lazy_static, std)
  M url 2.2.0 (transitive third-party, crates.io)
    * version upgraded from 2.1.1
    * (unchanged features: [none])
  M zeroize 1.1.1 (transitive third-party, crates.io)
    * version upgraded from 1.1.0
    * (unchanged features: alloc, zeroize_derive)
  R futures 0.3.6 (direct third-party, crates.io)
    * (old features: alloc, async-await, default, executor, futures-executor, std)
  R pin-project 0.4.26 (direct third-party, crates.io)
    * (old features: [none])
  R block-cipher 0.8.0 (transitive third-party, crates.io)
    * (old features: [none])
  R futures 0.1.29 (transitive third-party, crates.io)
    * (old features: default, use_std, with-deprecated)
  R maybe-uninit 2.0.0 (transitive third-party, crates.io)
    * (old features: [none])

host packages:
  A const_fn 0.4.3 (transitive third-party, crates.io)
    * features: [none]
  A pin-project-internal 0.4.27 (transitive third-party, crates.io)
    * features: [none]
  A pin-project-internal 1.0.1 (transitive third-party, crates.io)
    * features: [none]
  M enum_dispatch 0.3.4 (direct third-party, crates.io)
    * version upgraded from 0.3.3
    * (unchanged features: [none])
  M num-derive 0.3.3 (direct third-party, crates.io)
    * version upgraded from 0.3.2
    * (unchanged features: [none])
  M syn 1.0.48 (direct third-party, crates.io)
    * version upgraded from 1.0.42
    * (unchanged features: clone-impls, default, derive, extra-traits, full, parsing, printing, proc-macro, quote, visit, visit-mut)
  M aho-corasick 0.7.15 (transitive third-party, crates.io)
    * version upgraded from 0.7.13
    * (unchanged features: default, std)
  M anyhow 1.0.34 (transitive third-party, crates.io)
    * version upgraded from 1.0.33
    * (unchanged features: default, std)
  M cc 1.0.62 (transitive third-party, crates.io)
    * version upgraded from 1.0.60
    * (unchanged features: jobserver, parallel)
  M either 1.6.1 (transitive third-party, crates.io)
    * version upgraded from 1.6.0
    * (unchanged features: [none])
  M futures-macro 0.3.8 (transitive third-party, crates.io)
    * version upgraded from 0.3.6
    * (unchanged features: [none])
  M hashbrown 0.9.1 (transitive third-party, crates.io)
    * version upgraded from 0.8.2
    * (unchanged features: raw)
  M indexmap 1.6.0 (transitive third-party, crates.io)
    * version upgraded from 1.5.1
    * (unchanged features: [none])
  M libc 0.2.80 (transitive third-party, crates.io)
    * version upgraded from 0.2.79
    * (unchanged features: default, std)
  M memchr 2.3.4 (transitive third-party, crates.io)
    * version upgraded from 2.3.3
    * (unchanged features: default, std, use_std)
  M pkg-config 0.3.19 (transitive third-party, crates.io)
    * version upgraded from 0.3.18
    * (unchanged features: [none])
  M ppv-lite86 0.2.10 (transitive third-party, crates.io)
    * version upgraded from 0.2.9
    * (unchanged features: simd, std)
  M proc-macro-hack 0.5.19 (transitive third-party, crates.io)
    * version upgraded from 0.5.18
    * (unchanged features: [none])
  M ref-cast-impl 1.0.3 (transitive third-party, crates.io)
    * version upgraded from 1.0.2
    * (unchanged features: [none])
  M regex 1.4.2 (transitive third-party, crates.io)
    * version upgraded from 1.3.9
    * (unchanged features: aho-corasick, default, memchr, perf, perf-cache, perf-dfa, perf-inline, perf-literal, std, thread_local, unicode, unicode-age, unicode-bool, unicode-case, unicode-gencat, unicode-perl, unicode-script, unicode-segment)
  M regex-syntax 0.6.21 (transitive third-party, crates.io)
    * version upgraded from 0.6.18
    * (unchanged features: default, unicode, unicode-age, unicode-bool, unicode-case, unicode-gencat, unicode-perl, unicode-script, unicode-segment)
  M serde_derive 1.0.117 (transitive third-party, crates.io)
    * version upgraded from 1.0.116
    * (unchanged features: default)
  M structopt-derive 0.4.13 (transitive third-party, crates.io)
    * version upgraded from 0.4.11
    * (unchanged features: [none])
  M thiserror-impl 1.0.22 (transitive third-party, crates.io)
    * version upgraded from 1.0.21
    * (unchanged features: [none])
  M zeroize_derive 1.0.1 (transitive third-party, crates.io)
    * version upgraded from 1.0.0
    * (unchanged features: [none])
  R pin-project-internal 0.4.26 (transitive third-party, crates.io)
    * (old features: [none])
```

**Pull request closed without merging**
