### PR TITLE
ci: run unit tests using github actions

### PR DESCRIPTION
**Pull request by bmwill**

### CODE REVIEW

**Comment by JoelMarcey** [comment]
Might want to update https://github.com/libra/libra/blob/master/.github/workflows/README.md with this new workflow?

**Comment by bmwill** [comment]
@bors-libra r=JoelMarcey

Yeah I figured we'd get something working before we go and add docs about it

**Comment by bmwill** [comment]
@bors-libra r-

Wait it seems to have triggered

**Pull request closed without merging**
