### PR TITLE
BlockMetadata into_inner() function cannot fail; drop the Result

### PR DESCRIPTION
**Pull request by bob-wilson**
This simplifies the code a bit and also removes an unnecessary error check in the VM Adapter.

## Motivation

Removing unnecessary code

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Ran existing tests

### CODE REVIEW

**Comment by libra-action** [comment]
**This PR may have modified JSON-RPC server code.**

Breaking changes policy:

1. Chaning JSON-RPC method signatures or removing/modifying fields
   in the response in /V1 will not be accepted.
2. Adding fields is ok.
3. Adding a new JSON-RPC method is ok.

Please ensure you have also done the following to update the docs:

1. Update json-rpc/API-CHANGELOG.md.
2. Add/update type/method documentation under json-rpc/docs.

**Comment by bob-wilson** [comment]
It looks like the code was different prior to #3097 from @zekun000. It used deserialize the previous votes and that could fail.

**Review by zekun000 — APPROVED** [review]

**Comment by msmouse** [comment]
LGTM

**Pull request closed without merging**
