### PR TITLE
Dependabot/cargo/bech32 0.7.2

### PR DESCRIPTION
**Pull request by rexhoffman**
## Motivation

Trying to get this dep updated.   Want the compilation error visible to folks who know more than I about rust.

### Have you read the [Contributing Guidelines on pull requests]

yes

## Test Plan

Successful compilation and test.

## Related PRs

none.

### CODE REVIEW

**Comment by rexhoffman** [comment]
@metajack I decided to have conversion functions on the type for to/from bech32 Strings.

**Comment by metajack** [comment]
@bors-libra delegate=rexhoffman

This looks fine. Did you find out from the relevant module owners whether this code is needed?

**Comment by rexhoffman** [comment]
@metajack looking in to that now.   Wanted to be able to drive this to completion (lints/checks/type changes and all first).

@davidiw, @msmouse and @huitseeker have touched a bit of the account_number and may know the answer.   Any compelling reasons to not remove Bech32 support from account_number?  It's bitcoin like encoding we added in over 8 months ago that doesn't appear to be used outside of out tests.    The changes I made in this pr are the only usages.   The crate in question (Bech32) is here: https://docs.rs/crate/bech32/0.7.2

**Comment by rexhoffman** [comment]
Also in the client we use hex for account number representation.

**Comment by davidiw** [comment]
Kill it with fire. I see no point in having this unnecessary representation and library. I had wanted to explore it myself but in my unrelated journeys through the code have found no purpose to it.

**Comment by rexhoffman** [comment]
Closing in favor of Bech32's removal.   https://github.com/libra/libra/pull/2619
Still glad I worked through this.

**Pull request closed without merging**
