### PR TITLE
[terraform] Make Vault data persistence configurable

### PR DESCRIPTION
**Pull request by mgorven**
Make Vault data non-persistent if validator data is too.

### CODE REVIEW

**Comment by rustielin** [comment]
What happens when Vault restarts, causing the keys to change?

**Comment by mgorven** [comment]
> What happens when Vault restarts, causing the keys to change?

Dunno, hopefully it doesn't crash. But if the validators all start from scratch on a push we need Vault to do so too.

**Comment by mgorven** [comment]
> Looks good to me. Quick q though: would it be possible to restore vault data? e.g. If the vault container crashes and restarts, we still have its old volume until ECS decides to clean it up. Could we just point vault to its old volume?

Theoretically yes. Why do you think this is necessary though? If the testnet is running without persistence we're assumedly okay with it losing data and restart arbitrarily.

**Comment by rustielin** [comment]
> Theoretically yes. Why do you think this is necessary though? If the testnet is running without persistence we're assumedly okay with it losing data and restart arbitrarily.

Nonpersistent storage was added to improve devnet liveness, but if vault restarts and the validators themselves don't, then the network is stuck. Agreed we don't care about data loss and arbitrary restarts in general, but this will halt the entire network until at least 1 hr later until continuous push kicks in. Not too big of an issue overall though; just means we'll some manual work in the edge cases.

**Pull request closed without merging**
