### PR TITLE
github: subscribe diem-core engineers to PRs that change diem-core crates #9106 - (140) AB#8770

### PR DESCRIPTION
**Pull request by rutkaracn**
### Motivation
github: subscribe diem-core engineers to PRs that change diem-core crates #9106

### Test Plan
CI/CD testcases were covered.

---------------------
### Motivation
Continuous fuzzing discovered a panic in the json-rpc fuzzer where one of the fuzzers managed to discover ```get_accumulator_consistency_proof``` and called it. The fuzzer, however, uses a MockDB rather than a real DiemDB. The MockDB didn't have ```get_accumulator_consistency_proof``` implemented and so the fuzz test panicked with ```unimplemented!()```. This means the fuzz panic is a false positive, but something we should fix nonetheless so it can discover more useful stuff.

To fix the problem, this PR back-fills all of the missing DB methods called by the json-rpc service with dummy implementations so the fuzzer won't panic if it discovers other methods. We also add the rest of the json-rpc methods (except ```get_resources```) to the ```test_method_fuzzer``` test so we can surface these ```unimplemented!()``` panics sooner in CI.

**This PR may have modified JSON-RPC server code.**
Breaking changes policy:
-Changing JSON-RPC method signatures or removing/modifying fields
in the response in /V1 will not be accepted.
-Adding fields is ok.
-Adding a new JSON-RPC method is ok.

Please ensure you have also done the following to update the docs:
-Update json-rpc/API-CHANGELOG.md.
-Add/update type/method documentation under json-rpc/docs.

### Test Plan
-CI/CD testcases were covered.
-cargo test --package diem-json-rpc --lib -- fuzzing::test_method_fuzzer --exact --nocapture 

-------------------
### Motivation
There was recently a bug uncovered in some of our legacy code where state sync will panic if it's unable to fetch the value of a config on-chain (see here: #9121). This PR fixes the bug as described in the issue: essentially just log an error on a missing config and expect the reconfiguration subscribers to handle the missing configs. As such, the PR offers two commits:
-Add a new unit test to ensure that state sync doesn't panic when configs are missing on-chain (both at startup and during a reconfiguration event).
-Fix the original bug in the code.

Note: This code is all going to be cleaned-up, refactored and improved as part of state sync v2 (e.g., I already have an outstanding PR to move all of this code into a single component: #9117). As a result, I've focussed just on fixing the bug in this PR and not handling any of the tech-debt surrounding the issue. This tech-debt will be cleaned up in state sync v2 (including adding tests to the reconfiguration subscribers to ensure they appropriately handle missing on-chain configs).

### Test Plan
-CI/CD testcases were covered.
-cargo test --package state-sync-v1 --lib -- executor_proxy::tests::test_missing_on_chain_config --exact --nocapture 

------------------
### Motivation
[consensus] make the optionally compiled code more obvious #9135

### Test Plan
CI/CD testcases were covered.

------------------
### Motivation
Starting from this commit, new genesis would be initialized with two_chain = true that enables 2-chain consensus protocol by default.

### Test Plan
CI/CD testcases were covered.

-------------------
### Motivation
x: update nextest to fix performance regression #9145

### Test Plan
CI/CD testcases were covered.

### CODE REVIEW

**Review by dhaneshacn — APPROVED** [review]

**Comment by rutkaracn** [comment]
Closing this PR due to technical issue.
New PR -  https://github.com/diem/diem/pull/10721

**Pull request closed without merging**
