### PR TITLE
Follow convention of one space before and after the curly braces and …

### PR DESCRIPTION
**Pull request by sachinkm77**
…make consistent with other dependencies

## Motivation

Follow convention of one space before and after the curly braces and make consistent with other dependencies

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

NA
## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by safeforge** [comment]
@sachinkm77 seems to be a duplicate of GH-193

**Comment by sachinkm77** [comment]
@safeforge , its a different file. "crypto/secret_service/Cargo.toml". The ones you changed are different.

**Comment by sachinkm77** [comment]
@safeforge .. Seems like there were more :). So fixed those too as part of this pull request.

**Comment by safeforge** [comment]
@sachinkm77 I discovered other files needs to be fixed. if you want I can cherry-pick your changes on top of my branch and we can propose a single PR which fixes Cargo.toml format. let me know if you're agree with that. :)

**Comment by sachinkm77** [comment]
Didn't find any other instances... @wqfish can you please review

**Comment by aching** [comment]
Can you please try rebasing against master and resubmitting?  That should trigger CI - which will allow this PR to be reviewed.

**Comment by sachinkm77** [comment]
Thanks @aching. Tried that but not sure why the checks are failing after rebasing and resubmitting. Any suggestions? Haven't broken any tests for sure.

**Comment by wqfish** [comment]
Thanks for the contribution! Looks like this was already committed in https://github.com/libra/libra/commit/26271fd5934df4d5b757c609c201389d6f62f4f8.

**Pull request closed without merging**
