### PR TITLE
[network] ConnectionOrigin added to NewPeer events

### PR DESCRIPTION
**Pull request by gregnazario**
In order to differentiate between incoming new peers and outgoing new
peers, this has been added.  It helps distinguish between the types of
connections we need to have limits on.  It also helps us determine whether a peer is upstream or downstream for mempool.

Note: This doesn't adjust mempool / state-sync.  I spent some time trying to do it, and then decided to limit the scope down and follow up on the next PR.

Also, this doesn't address the limits from ConnectivityManager, and the limits would still be shared at this point which will also be followed up on.

### CODE REVIEW

**Comment by christinacelee** [comment]
lgtm from application layer consuming this new flag, will let networking side take a look

**Comment by phlip9** [comment]
cool, lgtm!

@bors-libra r+

**Pull request closed without merging**
