### PR TITLE
[types] fix serialization of Transaction

### PR DESCRIPTION
**Pull request by bmwill**
Fix the serialization of the Transaction type so that it adheres properly to the LCS spec.

Ref: #1307

### CODE REVIEW

**Comment by davidiw** [comment]
If I understand this correctly, this is a breaking change where we use the enum type (32-bit) for serialization instead of the existing code which uses an 8-bit specifier?  If that's correct, it might be better to write that in one the commit summary for that specific commit. Also as Lei has done, it would be good to get storage buy-in for this change.

I like it though.

**Comment by bmwill** [comment]
Sounds good, lets see what the storage folks think and then I'll go ahead and update the commit msg with the relevant info. @msmouse thoughts?

**Comment by msmouse** [comment]
LGTM @bors-libra delegate+

**Pull request closed without merging**
