### PR TITLE
[dep] aes-gcm

### PR DESCRIPTION
**Pull request by rexhoffman**
## Motivation

Update aes-gcm

### Have you read the [Contributing Guidelines on pull requests]

y

## Test Plan

ci

## Related PRs

Supersedes https://github.com/libra/libra/pull/4333

### CODE REVIEW

**Comment by bmwill** [comment]
@rexhoffman The land didn't fail, it was finishing compiling the release build. Restarting it means that it has to go through the whole pipe again

**Comment by rexhoffman** [comment]
@bmwill huh, could have swore I saw a failed run (bad pull from crates.io)

**Pull request closed without merging**
