### PR TITLE
Add `--pre` flag for installing Python SDK since it is a pre-release right now

### PR DESCRIPTION
**Pull request by JoelMarcey**
## Motivation

The Python SDK were not building and thus 404'ing because we need to add the `--pre` flag since the SDK is not an official release yet.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Local test

## Related PRs

N/A

### CODE REVIEW

**Comment by JoelMarcey** [comment]
Hmmm... this is not working either. I need to fix this still.

**Comment by JoelMarcey** [comment]
https://github.com/libra/libra/pull/6669/checks?check_run_id=1366004166#step:5:1491

**Comment by xli** [comment]
Confusing, why it is not released and need --pre?

**Comment by JoelMarcey** [comment]
@xli The `--pre` didn't work anyway. I thnk there is some difference in the way `pip install` is working with the `libra-client-sdk` on the Linux box that GitHub Actions uses and when we run this locally on the Mac.

@bmwill Any initial thoughts on why we might be getting this error as we try to run this on GitHub Actions?

```
-----------------------------------
Generating Python Client SDK Docs
-----------------------------------
Checking for Python
Installing Python 3......
Python 3 is already installed
Installing libra-client-sdk
Collecting pip
  Downloading https://files.pythonhosted.org/packages/cb/28/91f26bd088ce8e22169032100d4260614fc3da435025ff389ef1d396a433/pip-20.2.4-py2.py3-none-any.whl (1.5MB)
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-20.2.4
ERROR: Could not find a version that satisfies the requirement libra-client-sdk (from versions: none)
ERROR: No matching distribution found for libra-client-sdk
Create directory for docs
Generating doc from libra-client-sdk
./scripts/build_docs.sh: line 155: pdoc3: command not found
```

**Comment by bmwill** [comment]
@JoelMarcey Are you able to pip install the sdk on a mac with no issues? Other than that it seems like `pdoc3` needs to be installed?

**Comment by JoelMarcey** [comment]
@bmwill Yeah, the script as-is runs perfectly fine on a Mac with no issues -- at least on my mine. (I guess I am doing the infamous "It works on my machine" defense). Can you try running this script on your Mac to just verify that it works there, and then we can figure out why it won't work on Ubuntu?

**Comment by JoelMarcey** [comment]
@xli @bmwill I think we are good here now. It ended up being a Python versioning problem. The default Actions build only uses 2.7 :/ . So updated the workflow to use 3.8 (thanks @xli ).

https://github.com/libra/libra/pull/6669/checks?check_run_id=1382145177 built successfully. I think we can land this now.

**Review by bmwill — APPROVED** [review]
/land

**Pull request closed without merging**
