### PR TITLE
[RFC][consensus] multi proposer election with per-epoch seed

### PR DESCRIPTION
**Pull request by mimoo**
Since each epoch resets the round number to 0, we are going to generate the exact same round proposers through each epoch. This PR attempts to use a **per-epoch seed** to randomize the election for each epoch.

There are a lot of options, but I chose to simply use the **seed = genesis ledger info's consensus hash**. (That is, the real genesis, or the last ledger info before the epoch change.)

To make this change, I needed to address two cases:

**1. (re)starting a validator.**

Since storage is read during start up, I can obtain the last ledger info of the previous epoch (if the current epoch is not 0):

```rust
fn start(config: &NodeConfig) -> (Arc<Self>, RecoveryData<T>) {
    // ...
    let seed = match ledger_info.ledger_info().epoch() {
        0 => ledger_info.ledger_info().consensus_data_hash(),
        epoch => {
            let previous_epoch = epoch - 1;
            let genesis_ledger_info = read_client
                .get_latest_ledger_infos_per_epoch(previous_epoch)
                .expect("unable to read genesis ledger info from storage")
                .pop()
                .expect("storage does not contain genesis ledger info");
            genesis_ledger_info.ledger_info().consensus_data_hash()
        }
    };
```

**2. new epoch change.**

In this case, the last ledger info comes for free as part of the function call:

```
pub fn start_new_epoch(&mut self, ledger_info: LedgerInfoWithSignatures) -> EventProcessor<T> {
```

In both case, I simply add the seed to `initial_data: RecoveryData` which is always available when calling `create_proposer_election()`

### CODE REVIEW

**Comment by bmaurer** [comment]
> However, I'm not sure I understand the problem we're trying to solve with the per-epoch seed. Are you concerned with an attack, in which a certain proposer can be regularly chosen via constantly proposing a new epoch? I don't think it's possible with the current reconfiguration design, and to be honest if we're forced to switch epoch every other round then we'll have much bigger problems anyway :). Even if we do decide that different epochs should better have different orderings, a simpler approach would be to choose a leader deterministically based on the (epoch, round).

It's worth pointing out that even if we switch epochs every N rounds, if the sequence of proposers is always the same then there will be some proposers that propose slightly more often (because by luck of the draw they show up more in the first n rounds). 

That said, right now my impression is that we're not headed down a trajectory where being a proposer more or less often results in a financial reward. So at least in our configuration I'm not sure how critical this is.

**Comment by mimoo** [comment]
> a simpler approach would be to choose a leader deterministically based on the (epoch, round)

The problem with this approach is that you can compute at genesis who will be the leader at any epoch and round. 

If we care about thwarting attacks that target leaders in advance, this is an improvement compared to the current protocol.
I'm not sure how much we care about it though, and if we really care: is this change good enough? (others are using VRFs after all)

**Comment by bmaurer** [comment]
I don't think we're planning on changing epochs fast enough for something like this to really prevent an attacker from targeting a DDoS attack.

Something to consider is if there's a way we could have a secret that is only known to the current validator set. I think the biggest risk of a DDoS attack is from the outside world knowing who the current proposer is. A world where only validators know this is an improvement on one where the outside world knows

**Comment by aching** [comment]
I think it's a great idea to consider the issue of pre-computing the leader upon epoch change, however, the current proposal of the genesis ledger info's consensus hash also opens up the possibility that a dishonest leader can attempt to produce a hash that biases the next epoch's leader toward another dishonest leader.  A VRF based approach (assuming it also solves the initial seeding problem as well) where a leader embeds its VRF output cannot be attacked the same way.

**Comment by mimoo** [comment]
> A VRF based approach (assuming it also solves the initial seeding problem as well) where a leader embeds its VRF output cannot be attacked the same way.

The VRF still relies on a seed, which needs to be public data. 
There's always some degree of influence if we use a naive VRF scheme.

**Comment by aching** [comment]
Agreed (as per my comment) on the VRF seed issue, although a VRF seed seems like a more tractable issue, for instance, perhaps a based an account resource or the account address itself.

**Comment by dmitri-perelman** [comment]
I'd like to question the motivation for the per-epoch seed again :). I don't see how this approach is going to help: what's the attack that we're trying to tolerate better?

**Comment by mimoo** [comment]
@dmitri-perelman I think this summarizes it:

1. From what I understand, there's this idea in other cryptocurrencies of an attacker knowing in advance the leaders of round k, k+1, k+2, k+3, etc. and using this to target them in either a DDoS attack or an attack on consensus by attempting to corrupt them. (edited) 

2. There's also the idea of fairness, if you're the leader you can more or less control the ordering of transaction that will be included, and also collect the transaction fees. If we always produce the same series of leaders at every epoch then there's going to be a growing bias of leaders that will appear more often than others (pointed out by Ben I think in the PR) (edited)

**Comment by dmitri-perelman** [comment]
@mimoo thanks for the summary! Imho both these concerns are not valid, but I might be wrong. Do you want to meet and discuss it?

**Comment by mimoo** [comment]
proposing a simpler approach with the epoch as the seed: https://github.com/libra/libra/pull/1784

**Pull request closed without merging**
