### PR TITLE
[Secure JSON RPC] Added a missing README file for the lightweight JsonRpcClient.

### PR DESCRIPTION
**Pull request by JoshLind**
## Motivation

This PR adds the missing README file to the secure json-rpc directory. This file gives a brief overview of the secure json rpc client and should help readers better understand the role the client plays in our ecosystem.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

Viewed the file locally in markdown and everything appears to render correctly.

## Related PRs

None.

### CODE REVIEW

**Comment by JoshLind** [comment]
Thanks, David! 😄

**Comment by sausagee** [comment]
FYI - We hit DockerHub's rate limit in LBT. LBT is unplugged for now.  Please re-land when you are ready.

**Comment by JoshLind** [comment]
> FYI - We hit DockerHub's rate limit in LBT. LBT is unplugged for now. Please re-land when you are ready.

No worries! Thanks @sausagee!

**Pull request closed without merging**
