### PR TITLE
[terraform] Create fullnode for each validator node

### PR DESCRIPTION
**Pull request by sherry-x**
## Motivation

Currently we have one (or more) fullnode only connected to the first validator. 
This PR changes the behavior to allow customized number of fullnodes on each validator by setting a variable `fullnode_distribution`, it should be a list of numbers.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

- Applied changes on `sherryxiao` workspace. `terraform apply -var "num_fullnodes=4" -var "fullnode_distribution=[2, 2, 0, 0]"`
- Check each validator to make sure they have one fullnode connect to it:
```
[ec2-user:validator@ip-10-0-7-164 ~]$ curl localhost:9102/metrics
# HELP libra_network_peers Libra network peers counter
# TYPE libra_network_peers gauge
libra_network_peers{role_type="full_node",state="connected"} 2
libra_network_peers{role_type="validator",state="connected"} 3
```
- Check each fullnode to make sure they connected to one validator:
```
[ec2-user:validator@ip-10-0-6-247 ~]$ curl localhost:9102/metrics
# HELP libra_network_peers Libra network peers counter
# TYPE libra_network_peers gauge
libra_network_peers{role_type="full_node",state="connected"} 1
```

- Applied changes on `sherryx` workspace, with 2 fullnodes `terraform apply -var "num_fullnodes=3" -var "fullnode_distribution=[1, 2, 0, 0]"`
- Make sure the topology still works.

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by opsguy** [comment]
This is rad! Would be cool in the future if we could setup custom # per validator but this should be nice for now to test this a bit more. 

Delegating so you can land tomorrow morning just in case.

@bors-libra delegate+

**Comment by phoenix-antigravity** [comment]
well, this PR sends radness to all time high!
@bors-libra: r+

**Comment by sunmilee** [comment]
Yayy thanks sherry we can finally have multiple fullnodes :D

**Pull request closed without merging**
