### PR TITLE
Compat fix repro canary

### PR DESCRIPTION
**Pull request by rustielin**
## Motivation

Test https://github.com/libra/libra/pull/5440. Change here: ad4e1ff 

This ensures LBT fails at the end, so bors won't merge it in.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

Previously used same method to test https://github.com/libra/libra/pull/5353

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by rustielin** [comment]
hmm github actions doesn't like multiline-strings :/

**Comment by bmwill** [comment]
@metajack maybe you can help @rustielin with getting multi-line strings working? You seemed to solve that problem with the hyperjump stuff

**Comment by rustielin** [comment]
Maybe I should just write this to file.. 🤔

**Comment by andll** [comment]
You can probably also have it as a single line string
Hopefully most of long `-E`(like fn upgrade) will go away once we stabilize

**Pull request closed without merging**
