### PR TITLE
[libra_swarm] Fix path error when launch attempt fails

### PR DESCRIPTION
**Pull request by littlepretty**
### Motivation:
When user specifies a persistent config dir, `launch_swarm_attemp()` doesn't cleanup previously created dirs. The next attempt fails due to "File already exists".

### Summary:
Delete previous config directory created by failed `launch_swarm_attempt()`.

#### Normal startup:
```
./target/release/libra_swarm -n 4 -c temp_config -f faucet_for_ruben
```

#### Emulate launch failures with broken faucet keypair file:
```
./target/release/libra_swarm -n 4 -c temp_config -f faucet_for_ruben_err
Faucet account created in (loaded from) file "faucet_for_ruben_err"
Base directory containing logs and configs: Persistent("temp_config")
Base directory containing logs and configs: Persistent("temp_config")
Base directory containing logs and configs: Persistent("temp_config")
Base directory containing logs and configs: Persistent("temp_config")
Base directory containing logs and configs: Persistent("temp_config")
thread 'main' panicked at 'Max out 5 attempts to launch swarm', libra_swarm/src/swarm.rs:276:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

### CODE REVIEW

**Comment by fbandersnatch** [comment]
With this change, does it mean that logs will be deleted from the failed attempts and you won't be able to see the problem?

**Comment by littlepretty** [comment]
> With this change, does it mean that logs will be deleted from the failed attempts and you won't be able to see the problem?

The last attempt's config dir and logs will be kept. The intermediate attempts' logs will be lost.
Restarting libra_swarm with the same config dir will cleanup previous config dir (and logs).

**Comment by huitseeker** [comment]
@littlepretty what would it take to put config and log dirs in a `mktempdir` subdirectory?

**Comment by fbandersnatch** [comment]
They go to a tempdir unless otherwise specified, and in that case, it could be a problem.

**Comment by littlepretty** [comment]
> @littlepretty what would it take to put config and log dirs in a `mktempdir` subdirectory?

So the motivation is: every time user start libra swarm, the config files and logs will be in a temp dir. With the `-c` option in libra_swarm, user can specify where to put them. Of course it is user's responsibility to remove the directory after libra_swarm exit.

In that case, however if launch swarm fails once, following attempts will also fail because the dir already exist when we first attempt to launch. This PR fix this problem by first delete the dir, then create new one.

**Comment by huitseeker** [comment]
My point in suggesting a named *sub*directory is that it allows repeatedly sending files to a new location under the `-c` custom location with no name conflict issues. Similarly, you could envision writing logs to a *timestamped* subdirectory of the directory passed as an argument to `-c`, with the same results.

The reason I'm suggesting this is deleting logs is a destructive operation I'd expect you would want a user confirmation on, rather than rely on convention, especially if this is a non-default edge case. Who will remember calling with a custom `-c` argument twice overwrites logs in 6 months? in a year?

**Comment by littlepretty** [comment]
> My point in suggesting a named _sub_directory is that it allows repeatedly sending files to a new location under the `-c` custom location with no name conflict issues. Similarly, you could envision writing logs to a _timestamped_ subdirectory of the directory passed as an argument to `-c`, with the same results.
> 
> The reason I'm suggesting this is deleting logs is a destructive operation I'd expect you would want a user confirmation on, rather than rely on convention, especially if this is a non-default edge case. Who will remember calling with a custom `-c` argument twice overwrites logs in 6 months? in a year?

I think what you want (handling overwrites) is perhaps out of the scope of this PR.

The situation with this PR is pretty the same for both following cases,
* without `-c` you get a temp dir and it disappears when you exit `libra_swarm` normally;
* with `-c` you have a persisted dir and you can always see logs/configs during/after running `libra_swarm`.
* If something failed, user has the log to exam, with or without `-c`.

**Pull request merged**
