### PR TITLE
Typo fix, "choose" to "choice"

### PR DESCRIPTION
**Pull request by escottkey**
## Motivation

Typo fix

### Have you read the [Contributing Guidelines on pull requests](../CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

(Share your test plan here. If you changed code, please provide us with clear instrutions for verifying that your changes work.)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by ericnakagawa** [comment]
Thanks for the PR @escottkey. Our team is reviewing your PR and will reply back soon. We're still sorting out CLAs and will reply back with an update.

**Comment by etos** [comment]
image

**Comment by escottkey** [comment]
It's legit. 
[Proof that I'm a native English speaker: read rhymes with lead and lead rhymes with read]

**Comment by kphfb** [comment]
Thanks you escottkey!  Your change has been applied and will be landed soon

**Pull request closed without merging**
