### PR TITLE
[types] Proposed update to directory structure for account_config

### PR DESCRIPTION
**Pull request by tzakian**
This file was getting quite large and unwieldy, so this splits this out into a more structured format:
* There is a directory for defining resources (e.g. `account` `balance` etc.)
* One for defining events (e.g. `sent_payment`)
* One for defining constants relating to different modules (e.g. `LBR_MODULE_NAME`). 

The goal of this PR is purely structural; it doesn't change the content of the file, but splits it out to be more structured to make changes to it easier to comprehend. The way functions/constants/structs are imported from `account_config`is unaffected.

Interested in any thoughts/feedback on this.

### CODE REVIEW

**Comment by dariorussi** [comment]
what do you want to do with this?
I think you are in the best position to organize those files/APIs given they are all about interaction with the structure of the Move modules and resources.
But I am not sure what to say, and wonder if reviewers should more be external teams using this API? 
Thoughts anybody?

**Comment by tzakian** [comment]
The external API of this doesn't change at all (i.e. any places that import `account_config::...` don't change. The main thing I want to know is whether we are OK with this (internal) restructuring to it. If we are, then I'd like to land it.

**Comment by vgao1996** [comment]
This looks much cleaner to me.

**Comment by tzakian** [comment]
I would say accept :) I need to do a rebase, but otherwise I'd love to see this land. Usually the structs are handled separately when you're looking at implementing things. From an outside perspective though, you don't have to worry about these distinctions.

**Pull request closed without merging**
