### PR TITLE
[cluster-test] Shorter validator pod names

### PR DESCRIPTION
**Pull request by andll**
Renames `validator-xxx` -> `val-xxx` and `fullnode-x-y` -> `fn-x-y`.
Those names are part of UX, for example they will appear in trace, so it is good to have them short

### CODE REVIEW

**Comment by ankushagarwal** [comment]
@bors-libra delegate+

Can you test this once before landing (after tf apply)

**Comment by bmwill** [comment]
@ankushagarwal did this PR really need to jump the queue by setting a priority? There are other people in the queue who have been waiting and since this seems noncritical it seems like the priority feature is being taken advantage of here

**Comment by ankushagarwal** [comment]
We have made some changes to cluster test CI and this PR needs to be merged for the tests to pass. The other PRs would fail cluster test CI is they land before this.

**Pull request closed without merging**
