### PR TITLE
[move-prover] add functionality for computing loops in a graph

### PR DESCRIPTION
**Pull request by shazqadeer**
## Motivation

This PR adds code for computing loops in a graph.  This functionality will be used in a subsequent PR to instrument the translated Boogie code for a Move function with loop invariants.
 
### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

New unit tests.

### CODE REVIEW

**Comment by shazqadeer** [comment]
@wrwg :  Let me know if you prefer to merge the new crate introduced in this PR with stackless-bytecode-generator.  If you also want to rename stackless-bytecode-generator, I can do that in this PR as well.

**Comment by wrwg** [comment]
> @wrwg : Let me know if you prefer to merge the new crate introduced in this PR with stackless-bytecode-generator. If you also want to rename stackless-bytecode-generator, I can do that in this PR as well.

Feels more adequate to put this into the stackless crate. I wouldn't expect that we develop a library of generic graph algorithms which would belong in its own crate.

**Comment by shazqadeer** [comment]
I have removed the separate crate.

**Pull request closed without merging**
