### PR TITLE
Prepend libra to logger package

### PR DESCRIPTION
**Pull request by TristanDebrunner**
## Motivation

To publish to crates.io, all packages need to have unique names. Prepending libra to the names of all packages provides unique names for all packages. This PR prepends libra to the `logger` package.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Only cosmetic changes, existing tests should suffice.

## Related PRs

#1226
#1235
#1350

### CODE REVIEW

**Comment by TristanDebrunner** [comment]
CC @bmwill

**Comment by bmwill** [comment]
@TristanDebrunner looks like i didn't have much time to get to this (8 minutes to be exact :() would you mind rebasing?

**Comment by TristanDebrunner** [comment]
Alright @bmwill, I seem to have caught up for now.

**Comment by bmwill** [comment]
Sorry @TristanDebrunner looks like we have another conflict :(

**Comment by TristanDebrunner** [comment]
@bmwill, another round?

**Comment by bmwill** [comment]
Already approved and currently top of the queue to be tested/merged. Thanks for your patience :)

**Pull request closed without merging**
