### PR TITLE
[state-synchronizer] remove Option qualifier from coordinator.waypoint

### PR DESCRIPTION
**Pull request by agc-quadra**
SyncCoordinator previously had an Option<Waypoint> field in order to support integration_test.rs;  this necessitated the addition of code paths that were test only and introduced unnecessary Option check code in production code paths.

This change (a) removes the option qualifier and (b) updates the tests to use default "0" values for waypoints.

## Motivation

SyncCoordinator has a legacy `Option<Waypoint>` field;  this change removes the Option qualifier.

In production paths, there is always a valid Waypoint provided.  The `None` values for SyncCoordinator were used only in tests and necessitated error checking logic that would never be exercised in production (but was fundamental to tests passing).

Here we remove Option and update the tests to provide Waypoint::default() instead of None.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

yes

## Test Plan

Don't break existing tests, specifically state-synchronizer/src/tests/integration_test.rs

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by agc-quadra** [comment]
@davidiw  poking you for triage/redirection to domain expert.

**Comment by gregnazario** [comment]
> @davidiw @gregnazario poking you two for triage/redirection to domain experts.

David is out, and I'm unsure about waypoint (still kinda new), but I'll poke around and see.

As far as I can tell, it seems like what you're doing is a good idea, but I'm unsure if that will cause the configs to break / other side effects

**Comment by agc-quadra** [comment]
> > @davidiw @gregnazario poking you two for triage/redirection to domain experts.
> 
> David is out, and I'm unsure about waypoint (still kinda new), but I'll poke around and see.
> 
> As far as I can tell, it seems like what you're doing is a good idea, but I'm unsure if that will cause the configs to break / other side effects

Yeah.  I suspect folks more intimately involved in that part of the code base will have a clearer perspective on the traps I'm undoubtably stepping into.

**Comment by gregnazario** [comment]
@mgorven is there any situation that waypoint isn't set in our configs?  This change seems like it should clean up the mess around accessing an `Option<Waypoint>` arg, but it just matters whether we deliberately ever not provide a waypoint in configs.

**Comment by davidiw** [comment]
I think we should consider relabeling Waypoint::default to Waypoint::mock, since there is no "default" Waypoint.

@bors-libra r+

**Comment by mgorven** [comment]
> @mgorven is there any situation that waypoint isn't set in our configs? This change seems like it should clean up the mess around accessing an `Option<Waypoint>` arg, but it just matters whether we deliberately ever not provide a waypoint in configs.

We always set waypoints in pre-mainnet. As long as config-builder sets them there shouldn't be situations where they are not.

**Pull request closed without merging**
