### PR TITLE
Incremental build for validator docker image

### PR DESCRIPTION
**Pull request by andll**
This diff changes build time from 40 to few minutes for incremental change, which is incredibly valuable during triage

### CODE REVIEW

**Comment by andll** [comment]
@bors-libra r=kphfb
cc @sausagee I `think` this change should be safe for nightly build CI, but just in case letting you know its there

**Comment by mgorven** [comment]
@andll: This breaks CI, and is not the right way to do docker images (as was previously discussed a few months ago). Please revert this and we can discuss the options for this specific use case.

**Comment by andll** [comment]
@sausagee fixed CI build.
What is specific concern you currently have?

**Comment by mgorven** [comment]
CI is only fixed because it's using copies of the old docker files in libra-ops for now. It needs to be switched back and will break again at that point. My objections are the same as the last time this was discussed. Please revert and we can discuss how to approach this.

**Comment by andll** [comment]
I agree we need to reuse same docker files in ci - will need to find a way to achieve that

Having incremental build was crucial in last investigation, I am not comfortable reverting this diff on the grounds of “this is not proper way of doing things” without having concrete solution to incremental build problem


On Oct 14, 2019, at 12:16 PM, Michael Gorven <notifications@github.com> wrote:

﻿

CI is only fixed because it's using copies of the old docker files in libra-ops for now. It needs to be switched back and will break again at that point. My objections are the same as the last time this was discussed. Please revert and we can discuss how to approach this.

**Pull request closed without merging**
