### PR TITLE
[rust] update 1.44.1, code coverage tested as well -- adding in backtraces

### PR DESCRIPTION
**Pull request by rexhoffman**
## Motivation

Rust update with CI tests.

### Have you read the [Contributing Guidelines on pull requests]

y

## Test Plan

CI, plus temporary coverage report.

## Related PRs

none

### CODE REVIEW

**Comment by agc-quadra** [comment]
This PR appears to have broken rust on Mac:

> libra/ % cargo build
> error: process didn't exit successfully: `rustc -vV` (exit code: 1)
> --- stderr
> error: 'rustc' is not installed for the toolchain '1.44.1-x86_64-apple-darwin'
> To install, run `rustup component add rustc --toolchain 1.44.1-x86_64-apple-darwin`
>
> libra/ % rustup component add rustc --toolchain 1.44.1-x86_64-apple-darwin
> error: toolchain '1.44.1-x86_64-apple-darwin' does not support components
> libra/ % 


@rexhoffman

**Comment by metajack** [comment]
> This PR appears to have broken rust on Mac:

Your toolchain has become corrupted. This happens when your IDE triggers a toolchain update and another one starts at the same time.

To get back to a working setup, just uninstall and reinstall the toolchain.

```
rustup toolchain uninstall 144.1
rustup toolchain install 1.44.1
```

**Comment by agc-quadra** [comment]
Didn't work.  The only way I can get to a working setup (so far) is to go to a branch before this PR.

```
error: 'rustc' is not installed for the toolchain '1.44.0-x86_64-apple-darwin'
To install, run `rustup component add rustc --toolchain 1.44.0-x86_64-apple-darwin`

libra % rustup toolchain uninstall 1.44.1

info: uninstalling toolchain '1.44.1-x86_64-apple-darwin'
info: toolchain '1.44.1-x86_64-apple-darwin' uninstalled
libra % rustup toolchain install 1.44.1

info: syncing channel updates for '1.44.1-x86_64-apple-darwin'
471.9 KiB / 471.9 KiB (100 %) 415.0 KiB/s in  1s ETA:  0s
info: latest update on 2020-06-18, rust version 1.44.1 (c7087fe00 2020-06-17)
info: downloading component 'cargo'
  3.9 MiB /   3.9 MiB (100 %) 1023.3 KiB/s in  2s ETA:  0s
info: downloading component 'clippy'
info: downloading component 'rust-docs'
 12.2 MiB /  12.2 MiB (100 %)  10.3 MiB/s in  1s ETA:  0s
info: downloading component 'rust-std'
 16.6 MiB /  16.6 MiB (100 %)   9.2 MiB/s in  1s ETA:  0s
info: downloading component 'rustc'
 56.1 MiB /  56.1 MiB (100 %)  10.4 MiB/s in  5s ETA:  0s
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
 12.2 MiB /  12.2 MiB (100 %)   8.5 MiB/s in  1s ETA:  0s
info: installing component 'rust-std'
info: installing component 'rustc'
 56.1 MiB /  56.1 MiB (100 %)  17.6 MiB/s in  3s ETA:  0s
info: installing component 'rustfmt'

  1.44.1-x86_64-apple-darwin installed - rustc 1.44.1 (c7087fe00 2020-06-17)

info: checking for self-updates
 libra % cargo build
error: process didn't exit successfully: `rustc -vV` (exit code: 1)
--- stderr
error: 'rustc' is not installed for the toolchain '1.44.0-x86_64-apple-darwin'
To install, run `rustup component add rustc --toolchain 1.44.0-x86_64-apple-darwin`
```

I've attempted to completely uninstall rust with `rustup self uninstall` and then do a clean install, only to recreate the same effect.

**Comment by metajack** [comment]
The error messages you are posting are requesting 1.44.0 and you're installing 1.44.1. Do you have an override set? What does your rust-toolchain file say when you are on master?

**Comment by agc-quadra** [comment]
> The error messages you are posting are requesting 1.44.0 and you're installing 1.44.1. Do you have an override set? What does your rust-toolchain file say when you are on master?

Very good questions.   I came back and did a fetch / rebase on master.  And then `rustup self uninstall`;  at which point `rustup self install` no longer worked (?). So I used the `scripts/dev_setup.sh` and everything seems to be happy again.  Of course I tried repeating the uninstall/install suggestion before looking for the rust-toolchain file, so I can't tell you what state it was in.

Thanks a bunch for the patience.  I'm glad the solution can be explained by my local incompetence.

One thought on where everything went sideways --- I keep `cargo watch -x build` running in a terminal;  it's possible that that process interfered with the toolchain update on master and borked the world.

**Comment by metajack** [comment]
rustup does not lock it's installation during install, so if anything triggers an install and quits before continuing or another rustup also attemps to install and fails, it leaves the directory in a bad state. cargo watch would definitely be suspect here, as is most Rust IDE tooling that uses rust-analyzer or RLS, since those all invoke rustup under the hood to perform some operations.

It's a known limitation of the tooling in rustup: https://github.com/rust-lang/rustup/issues/988

**Pull request closed without merging**
