### PR TITLE
[storage] remove dead code

### PR DESCRIPTION
**Pull request by rexhoffman**
## Motivation

Allow coverage runs to complete successfully.

### Have you read the [Contributing Guidelines on pull requests] 

y

## Test Plan

CI

### CODE REVIEW

**Comment by wqfish** [comment]
LGTM but the rusty-fork bump probably should go to another PR?

**Comment by rexhoffman** [comment]
ugh, my bad :(

**Comment by msmouse** [comment]
@rexhoffman  Thanks man!

**Pull request closed without merging**
