### PR TITLE
[config] Make trusted_peers smaller

### PR DESCRIPTION
**Pull request by mgorven**
The size of this file is linear with the number of nodes, so let's make
it more compact. Shorten field names and flatten top level map. This
takes a 100 node file from 36K to 30K.

Test Plan: Ran tests

### CODE REVIEW

**Comment by mgorven** [comment]
@huitseeker: You mean you want to be able to `grep "k ="` in the codebase to find keys?

**Comment by huitseeker** [comment]
@mgorven I was thinking of 
```
 ag '\b\w+k =' -G '.*\.config\.toml'
```

**Comment by mgorven** [comment]
@huitseeker: Right. If trusted_peers is different anyway (in that it doesn't use "key") and you have to know to look for it specifically, how useful is that compared to say `find . -name trusted_peers.config.toml`?

**Comment by mgorven** [comment]
Update prod trusted_peers to keep client working against prod.

**Comment by 0-o-0** [comment]
are we able to run 100 nodes after this change?

**Comment by mgorven** [comment]
@0-o-0 Not yet

**Pull request merged**
