### PR TITLE
[cluster-test] Use async-trait to simplify code

### PR DESCRIPTION
**Pull request by ankushagarwal**
## Summary

Refactor cluster-test traits to use `async-trait` so that code can be simplified

### CODE REVIEW

**Comment by andll** [comment]
Does it work with Idea type suggestion? Can it understand types of async functions of trait with this macro?

**Comment by ankushagarwal** [comment]
> Does it work with Idea type suggestion? Can it understand types of async functions of trait with this macro?

Yes.

image

**Comment by andll** [comment]
But it does not seem to understand beyond that?

image

**Comment by andll** [comment]
image

**Comment by ankushagarwal** [comment]
Seems to be working for me. I am using `0.2.115.2157-193` version of the rust intellij plugin

image

**Comment by andll** [comment]
@bors-libra delegate+
Ok, if it works with idea I don't have objections, I'll figure out what was wrong with my setup later

**Pull request closed without merging**
