### PR TITLE
[cluster-test] Add recovery-time experiment to CI

### PR DESCRIPTION
**Pull request by ankushagarwal**
## Summary

Add this as the first experiment so that it starts with a clean slate

### CODE REVIEW

**Comment by ankushagarwal** [comment]
Updated to be the first experiment in the suite. For the other changes we discussed, I'll create a new PR

**Comment by andll** [comment]
@bors-libra delegate+
Could you run entire ci suite at least once in your workplace before merging the diff? So we can see how this experiment affects TPS and other

**Comment by ankushagarwal** [comment]
These are the numbers from my cluster

```
Recovery rate : 1470.6 txn/sec
all up : 504 TPS, 1491.8 ms latency
10% down : 334 TPS, 2154.0 ms latency
3 Region Simulation : 385 TPS, 2101.4 ms latency
```

@bors-libra r+

**Comment by andll** [comment]
> all up : 504
Huh (
200 txn/sec down just because we minted 100k accounts?

**Comment by ankushagarwal** [comment]
For my cluster, I typically get ~600tps at peak. But yeah, 100 tps drop from normal

**Pull request closed without merging**
