### PR TITLE
Standardization 4

### PR DESCRIPTION
**Pull request by huitseeker**
Follow-up to #1131 #1161 #1164 #1282 

Contributes to #1119

### CODE REVIEW

**Comment by huitseeker** [comment]
TODO after this:

```
crypto_derive
failure_macros
grpc_helpers
ir_to_bytecode
ir_to_bytecode_syntax
language_e2e_tests
libra_wallet
stackless_bytecode_generator
storage_proto
transaction_builder
vm_cache_map
vm_genesis
vm_runtime
vm_runtime_types
vm_validator
```

**Comment by metajack** [comment]
@bmwill Does that output look right to you? Seems like cargo lockfile diff is giving weird output.

**Comment by huitseeker** [comment]
@metajack Ack. looking at the weird socket-bench-server / socket 2 output

**Comment by bmwill** [comment]
@metajack Looks like its working as intended, since this diff removes crates with `_` in their name and adds crates with `-` in their name

**Pull request closed without merging**
