### PR TITLE
[tf][roar] override safetyrules tags separately

### PR DESCRIPTION
**Pull request by rustielin**
## Motivation

Bug fix. Recent change to override safety rules image tags (https://github.com/libra/libra/pull/4252) was not compatible with earlier change to use image digest over tags in ROAR (https://github.com/libra/libra/pull/4057). This is because while safetyrules and validators might share the same image tag, their digests are different. This PR adds a new TF variable `override_safety_rules_image_tags` to do the safetyrules override separately explicitly.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

yes

## Test Plan

ROAR on devnet and tf apply: http://prometheus.rustielin.aws.hlw3truzy4ls.com:9091/d/overview10/overview?orgId=1

ROAR'ed tfvars file:
```
# enable test runner instance so we can generate traffic on dev
cluster_test_runner = true
num_fullnode_networks = 2
enable_dashboard = true
enable_logstash  = true
logstash_image   = "853397791086.dkr.ecr.us-west-2.amazonaws.com/libra_logstash"
persist_libra_data = false
log_to_file = true

# Auto generated record and replay vars from file /Users/rustielin/libra-ops/terraform/testnet/facebook/dev.tfvars
restore_vol_ids = ["vol-0dc30ebdc129666d2","vol-0361de6609cfc0405","vol-03dc84d3215901813","vol-02653c0914eca0b1f"]
override_validator_ips = ["10.0.2.177","10.0.6.209","10.0.11.61","10.0.2.76"]
override_fullnode_ips = ["10.0.1.108","10.0.4.56"]
image_repo = "853397791086.dkr.ecr.us-west-2.amazonaws.com/libra_validator"
override_image_tags = ["sha256:920c0570e0af900520d859f570cea9f7d85290fce8db6aa23df79a3723f156c0","sha256:920c0570e0af900520d859f570cea9f7d85290fce8db6aa23df79a3723f156c0","sha256:920c0570e0af900520d859f570cea9f7d85290fce8db6aa23df79a3723f156c0","sha256:920c0570e0af900520d859f570cea9f7d85290fce8db6aa23df79a3723f156c0"]
logstash_version = "sha256:95343ef74362e1a4c06142ac99d036b4db1cc8255eaf697b1b19b64870a2e618"
safety_rules_image_repo = "853397791086.dkr.ecr.us-west-2.amazonaws.com/libra_safety_rules"
override_safety_rules_image_tags = ["sha256:2e7c7d2ccbb01173b541fd787f8fd01f327a7735e64b5656a301bfcd9dfdddde","sha256:2e7c7d2ccbb01173b541fd787f8fd01f327a7735e64b5656a301bfcd9dfdddde","sha256:2e7c7d2ccbb01173b541fd787f8fd01f327a7735e64b5656a301bfcd9dfdddde","sha256:2e7c7d2ccbb01173b541fd787f8fd01f327a7735e64b5656a301bfcd9dfdddde"]
```

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by sherry-x** [comment]
Will there be any case safety-rule needs to run on different image version than validator? should we just consolidate these two?

@bors-libra delegate+

**Comment by rustielin** [comment]
> Will there be any case safety-rule needs to run on different image version than validator? should we just consolidate these two?

Not that I know of, but now that we're using image digest to specify exactly which version of validator is running (as per https://github.com/libra/libra/pull/4057), we also need to be specific about safety rules too.

**Comment by rustielin** [comment]
FYI some cleanup, moving ecs task definition details fetching from terraform to aws cli. In the future, we'll probably want to remove the terraform dependency and use aws cli, esp since it's more portable. Still works:

```
$ pipenv run python3 -i devtools/compat/record_and_replay.py  --source dev --tf-dir ../terraform/testnet --var-file ../terraform/testnet/facebook/dev.tfvars --out-file replay.tfvars
...
$ cat replay.tfvars 
# enable test runner instance so we can generate traffic on dev
cluster_test_runner = true
num_fullnode_networks = 2
enable_dashboard = true
enable_logstash  = true
logstash_image   = "853397791086.dkr.ecr.us-west-2.amazonaws.com/libra_logstash"
persist_libra_data = false
log_to_file = true

# Auto generated record and replay vars from file /Users/rustielin/libra-ops/terraform/testnet/facebook/dev.tfvars
restore_vol_ids = ["vol-0dc30ebdc129666d2","vol-0361de6609cfc0405","vol-03dc84d3215901813","vol-02653c0914eca0b1f"]
override_validator_ips = ["10.0.2.177","10.0.6.209","10.0.11.61","10.0.2.76"]
override_fullnode_ips = ["10.0.1.108","10.0.4.56"]
image_repo = "853397791086.dkr.ecr.us-west-2.amazonaws.com/libra_validator"
override_image_tags = ["sha256:791d4683bc800d44e675bab7c3b2b05934b43d6de20f6b35bb7d6d4970e88492","sha256:791d4683bc800d44e675bab7c3b2b05934b43d6de20f6b35bb7d6d4970e88492","sha256:791d4683bc800d44e675bab7c3b2b05934b43d6de20f6b35bb7d6d4970e88492","sha256:791d4683bc800d44e675bab7c3b2b05934b43d6de20f6b35bb7d6d4970e88492"]
logstash_version = "sha256:95343ef74362e1a4c06142ac99d036b4db1cc8255eaf697b1b19b64870a2e618"
safety_rules_image_repo = "853397791086.dkr.ecr.us-west-2.amazonaws.com/libra_safety_rules"
override_safety_rules_image_tags = ["sha256:70a3d272c757f8d441b00ae18223cf28893fbe84398984c93bd0ac5a57d0cfc8","sha256:70a3d272c757f8d441b00ae18223cf28893fbe84398984c93bd0ac5a57d0cfc8","sha256:70a3d272c757f8d441b00ae18223cf28893fbe84398984c93bd0ac5a57d0cfc8","sha256:70a3d272c757f8d441b00ae18223cf28893fbe84398984c93bd0ac5a57d0cfc8"]

$ terraform plan
# passes
```

**Pull request closed without merging**
