### PR TITLE
Fixing Security Vulnerabilities 

### PR DESCRIPTION
**Pull request by ankitkacn**
## Motivation

- Fixing security and compliance vulnerabilities

## Test Plan

- CI/CD tests are covered

### CODE REVIEW

**Comment by borsdiem** [comment]
:boom: Tests timed-out

**Comment by borsdiem** [comment]
:boom: Tests timed-out

**Comment by borsdiem** [comment]
:sunny: Canary successful

**Review by dhaneshacn — APPROVED** [review]

**Pull request merged**
