### PR TITLE
[deps] update them all

### PR DESCRIPTION
**Pull request by rexhoffman**
## Motivation

Prepare libra repo for dependabot opening prs on detecting new versions of crates.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

yes

## Test Plan

a) ran local swam and created a few transactions.
b) cargo xtest

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by rexhoffman** [comment]
@metajack @sausagee  This should land before turning on dependabot.
Do we need to rope in the leads of various teams to vet the update?

Just want to point out where we are with this pr and check if it's where we want to be.

**Comment by metajack** [comment]
`autocfg 0.1.7 (1.0.0)` seems odd. We are adding a new dependency to an older version? Similarly for `rand_os` and `owning_ref` we seem to be deleting the newer version leaving the older one.

Other than that this looks ok. I assume this is the result of a blanket `cargo update`?

**Comment by rexhoffman** [comment]
@metajack this is the result of a blanket cargo update.    Just wanted to get us to the the point dependabot would be useful.

In the updated packages section there is this:

autocfg: 0.1.6 -> 1.0.0

I assume autocfg 0.1.7 is simply showing the dependencies referenced, not the dependencies used by some upgraded packages.   Seems we went from 0.1.6 to 1.0.0 but something (radix_trie and some rand_* crates) still depended on 0.1.7 transitively.   Least that's the way I'm currently interpreting this.

It looks like rand_os may be replaced by oorandom in some cases in our dep tree.

Now owning_ref is weird.

Here it is:

https://github.com/libra/libra/pull/2507/files#diff-d2ede298d9a75c849170d6ef285eda1eL2506

And inlined:

[[package]]
name = "lock_api"
version = "0.1.5"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 - "owning_ref 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "scopeguard 0.3.3 (registry+https://github.com/rust-lang/crates.io-index)",
]

I'm seeing it removed from a package that hasn't changed.    Does this have something to do with our cloning api/feature hackery?

**Comment by metajack** [comment]
It's possible `cargo guppy diff` is making a mistake. I'll review the lockfile changes directly to make sure.

**Comment by rexhoffman** [comment]
Ah, I suspect the new version of lock api (0.3.3) takes precedence so it may be the feature dependencies of the unused 0.1.5 are not calculated in the lock file via 'cargo update' as they are deemed irrelevant?

**Comment by rexhoffman** [comment]
@davidiw this is an attempt to set up a baseline to get dependabot turned on.   Dependabot will open new prs for each crate when they are made available in crates.io.   I also set my forked master of libra to have this set pr, and turned on dependabot against that branch, the example prs look like this (minus guppy and our internal checks).    I'd like to get us attempting to update crates regularly so we can get a feel for staying update to date, and how much effort it will be for us to begin to trust crates for both standard libra and the tcb.   Would love to discuss this further with you.   Example prs are here:   https://github.com/rexhoffman/libra/pulls.     Dependabot does a pretty good job of showing what changed in a crate (for any code on github).    No guarantees that the github code revision that you are given a diff of (previous version/new version) is what's in crates.io.

**Comment by huitseeker** [comment]
@rexhoffman Except your dependabot does not run CI.

How do I know? 

Well, the [bump of tiny-keccak](https://github.com/rexhoffman/libra/pull/3/files) is non-trivial — all variants of the `Cargo.toml` import require an explicit feature import. A real upgrade of tiny-keccak is [more involved](https://github.com/paritytech/parity-common/pull/260/files). My own PR against libra is in preparation. 

I'm not saying dependabot is not a benefit, but that making the workflow under dependabot productive may require a bit more work.

**Comment by metajack** [comment]
@huitseeker It will run CI when it's on the real repo. @rexhoffman's fork just doesn't have CircleCI set up.

I assume we can't do this automatically for everything, but it seems like it will be fine for most things.

**Comment by metajack** [comment]
@rexhoffman owning_ref was pulled in from parking_lot via lock_api. The new parking_lot pulls in a new lock_api and owning_ref is now an optional dependency that we don't use. However, we use owning_ref 0.3 in other dependency paths which is why it is still around.

**Comment by metajack** [comment]
@rexhoffman autocfg appears to be a minor bug in cargo guppy. Basically we added a new 1.0.0 but also changed the old 0.1.6 to 0.1.7. That appears to cause our diff algorithm to produce slightly confusing output for this case.

**Comment by metajack** [comment]
@rexhoffman And finally, rand moved from a normal dep to a dev-dep with criterion 0.3.1.

**Comment by rexhoffman** [comment]
@metajack thanks for looking at the delta.   I'll need to do another cargo update to get around the current conflicts, but just want @davidiw to weigh in first on the approach as my understand is he's the TSC member with the most skin in this game (vetting dependencies).   Glad we've noticed this guppy bug.   I'll make note of my pr before and after so that I can make a test for and clean up this in guppy as time/growing rust knowledge allows.

**Comment by metajack** [comment]
A minimal repro for guppy would be adding a new version and updating an existing version at the same time. I'm not sure whether it will always show the lowest version as the one that is added or if it shows the one with the lowest line number in Cargo.lock.

**Comment by rexhoffman** [comment]
Did a manual resolve to test myself.  May fail.  Also performing a cargo update. Which is good since my manual efforts appear to have failed.

**Comment by rexhoffman** [comment]
looks like smallvec has the same display bug in cargo-guppy

**Comment by rexhoffman** [comment]
Took 3 builds for the tests to pass.   Gotta look in to that soon.

**Comment by huitseeker** [comment]
@rexhoffman I've submitted a PR on your fork here:
https://github.com/rexhoffman/libra/pull/8
That pushes this a bit further, hopefully. Merging it there should update the PR here.

**Comment by metajack** [comment]
@hermanventer Is that a bug in MIRAI?

**Comment by metajack** [comment]
This latest failure might need investigation. I can't tell if that's a known flaky test or not.

**Comment by rexhoffman** [comment]
@metajack the test relys on startup synchronization (which is something I've seen error out before).  Would you mind clicking the rerun button on the test suite, as that's not something I have permission to do.  Or @sausagee if you see this first?

**Comment by metajack** [comment]
@bora-libra retry

**Comment by rexhoffman** [comment]
sorry should have seen that metajack set off the retry first.

**Pull request closed without merging**
