### PR TITLE
fix RUSTSEC vulnerabilities

### PR DESCRIPTION
**Pull request by jsladerman**
Upgraded the following: regex, zeroize, nix, thread_local, tokio

Compiled with no issues (on linux vm- can't compile on M1 mac until rocksdb is updated per https://github.com/diem/diem/pull/10295) and fixes their respective RUSTSEC vulnerabilities thrown by cargo audit

Left out time crate because it is only used as a sub-dependency of chrono, which is already updated to latest version and seems to have no plans to upgrade the crate. However, per https://github.com/chronotope/chrono/pull/578#issuecomment-1075907329, it seems chrono is unaffected by the vulnerability.

Also left out scratchpad because it is a custom diem crate which cargo audit confuses with a different crate with the same name

### CODE REVIEW

**Review by KoushikGavini — APPROVED** [review]

**Comment by jsladerman** [comment]
This should work now with the change from #10320

**Pull request closed without merging**
