### PR TITLE
[RFC] add a rust-toolchain file back in

### PR DESCRIPTION
**Pull request by sunshowers**
This has many advantages:

1. It pushes our builds towards hermeticity, which having worked on devtools for many years I've come to believe is *a priori* good.
2. It would be possible to make CI hermetic while making dev workflows not so much, but I believe that making dev builds as close to CI as possible is *a priori* good. This is also one of the big benefits of checking Cargo.lock in.
3. It completely obviates the need for manually requesting that developers upgrade Rust versions for new features -- that can simply be managed through tooling, as it should be.

### CODE REVIEW

**Comment by andll** [comment]
I will just summarize some points I heard form other people:

(1) we can pin toolchain in docker file to make sure image build is consistent (whether built on CI or locally)
(2) we can pin toolchain on CI to make sure CI verifies against same version that docker image is built
(3)  there are some use cases where pinning toolchain won't work, namely MIRAI and test coverage. Having this toolchain file adds more friction for people who are using those tools

Looks like (3) was main reason for removing this file, and (1) and (2) are reasonable work arounds to make sure our image in consistent

What do you think?

**Comment by metajack** [comment]
@sunshowers point 3 is a pretty good one. I think given the amount of negative feedback on removal, we'll land this and find other workarounds for dealing with the rust-toolchain file being there.

Perhaps we can revisit this when minimum supported rust version lands in Cargo, which will also address part of this issue.

**Comment by bmwill** [comment]
It seems like the few of us who don't want to have the toolchain file checked in are in the minority. As such I'm going to land this so that it gets added back into the repo and we can reevaluate whether we want to keep it in when we can specify minimum rust versions in Cargo.toml files.

@bors-libra r+

**Comment by mimoo** [comment]
What do you mean by hermeticity?

**Comment by sunshowers** [comment]
@andll 

>  (3) there are some use cases where pinning toolchain won't work, namely MIRAI and test coverage. Having this toolchain file adds more friction for people who are using those tools

Can those tools simply set RUSTUP_TOOLCHAIN? That overrides `rust-toolchain`.

@mimoo 

> What do you mean by hermeticity?

Basically reducing or eliminating the effect of the external environment (in this case, what version of Rust the dev happens to have) on the build product. Hermetic builds are how many large companies do builds. A perfectly hermetic build doesn't depend on the environment at all and so is completely reproducible -- this is good for security as well since anyone can build a binary from source and ensure that it is bit-identical to a release version.

https://landing.google.com/sre/sre-book/chapters/release-engineering/

**Comment by huitseeker** [comment]
> Can those tools simply set the RUSTUP_TOOLCHAIN env var? That overrides rust-toolchain.

Heads-up for @hermanventer

**Pull request closed without merging**
