### PR TITLE
[cleanup][common][crypto][storage][...] Remove 18 more untested, unused methods

### PR DESCRIPTION
**Pull request by huitseeker**
This PR removes 18 untested, unused methods from various crates (see below). The value of the PR may reside more in the signaling of the nature of those untested, unused methods rather than actual removal.

I do hope & expect that reviewers will come up with valid reasons why one or another of those methods should be part of our public API — I've hence separated commits per method so that those valid methods can be kept, by omitting the commit that removes them. Just say so in review, plz :slightly_smiling_face:

### CODE REVIEW

**Comment by andll** [comment]
I would prefer to keep methods in `common/logger/src/struct_log.rs` - I don't thin having them introduce any problems, and we might need them soon when/if people start more actively switching to structured logging

**Comment by huitseeker** [comment]
@andll OK! What about `common/metrics`?

**Comment by andll** [comment]
I don't have context on counter methods. We can ask @sherry-x too, but if it will turn out that no one knows as well it's probably safe to remove

**Comment by sherry-x** [comment]
I think it should be fine for `common/metrics` cause all the things removed here are some legacy metrics stuff.

**Pull request closed without merging**
