### PR TITLE
add Libra Core Requeriments

### PR DESCRIPTION
**Pull request by EvertonMelo**
add information tecnical for the running Libra Core.

## Motivation

minimize installation and execution errors

## Test Plan

Not applicated

## Related PRs

Not applicated

### CODE REVIEW

**Comment by EvertonMelo** [comment]
1) about the RUst ( stable ), It was just a suggestion that we could better diagnose the bugs since there is no whole pattern and qq. issue will have to enter the version of RUst, this is wordy and unnecessary. The idea is to simplify and suggest.

2 ) **Cmake**can change build according to the operating system, so we need to ensure the minimum viable, so that within which it is possible to build the build successfully without any changes to the script: dev_setup

3) **dev_setup** Doc: There are no clear requirements, such as viable versions and specifications for each operating system you have supported in the script.

I made a correction to the official website documentation, which has not yet been accepted (I don't know why).

notes: so in short we have to mitigate the issues, make the requirements explicit, to avoid ambiguity in internalizing issues and bugs.

This can help in making the bug bounty, defining the formal software life cycle, and also in using the prototype by the community.

**Comment by EvertonMelo** [comment]
ahhh 176 <= 270 ? 
if it's smaller you're right.

**Comment by davidiw** [comment]
Please re-base and re-request if still valid.

**Comment by EvertonMelo** [comment]
@davidiw @huitseeker 

the scope has not changed, nothing has been done, do as you wish, obscurity is your forte.

**Pull request closed without merging**
