### PR TITLE
aggressive prune_window in cluster-test

### PR DESCRIPTION
**Pull request by msmouse**
## Motivation

Setting to 50k versions, so that state pruning kicks in after about 1 min under full load.
 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

scripts/cti --pr 4814  --run bench

http://grafana.ct-2-k8s-testnet.aws.hlw3truzy4ls.com/d/2Q0p7AVWk/storage?orgId=1&from=1593454192129&to=1593454577844

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by andll** [comment]
Qq - what was TPS of the bench with this change?
Did it change or is it the same?

**Comment by msmouse** [comment]
@andll  I got "all up : 1288 TPS, 3502 ms latency, 4100 ms p99 latency, no expired txns" -- a little lower than 1294 I last saw in #changlog

**Comment by andll** [comment]
One more q - is it right that reduce prune window on all the validators? What is real prod scenario - are all validators going to have 'spike of pruning' at the same time? Or is it going to be balanced across validators? (In second case, should we only enable shorten pruning on one validator in this test?)

**Comment by msmouse** [comment]
They all prune continuously at the same time once the configured window is full.

**Comment by andll** [comment]
Ok, lets merge it as-is then
@bors-libra r+

In general I think good practice is to stagger those things so that maintenance operations don't happen synchronously, but this is probably not relevant to this change

**Comment by msmouse** [comment]
Right, this is supposed to happen continuously to NOT create peaks in the first place. What you said applies to the coming state snapshot backup better. Thanks!

**Pull request closed without merging**
