### PR TITLE
[crypto] Update x25519-dalek fork to remove duplicate version

### PR DESCRIPTION
**Pull request by metajack**
Found this dupe dependency looking at this weeks dep changes. I fixed this upstream in the x25519-dalek fork https://github.com/novifinancial/x25519-dalek/pull/7 and this updates our Cargo.lock to pick up that change.

### CODE REVIEW

**Review by huitseeker — APPROVED** [review]
LGTM!

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M x25519-dalek 1.1.0 (direct third-party, external 'git+https://github.com/novifinancial/x25519-dalek.git?branch=fiat4#4d6e37cee0a2ae0d3df522b3c6286fab6ce607b6')
    * source changed from external 'git+https://github.com/novifinancial/x25519-dalek.git?branch=fiat4#dc82145d8d25529d8aecab93d3ddf7062a74c719'
    * (unchanged features: fiat_u64_backend, std)
  R curve25519-dalek 3.0.0 (transitive third-party, external 'git+https://github.com/calibra/curve25519-dalek.git?branch=fiat3#2940429efd0e6482af1531cff079e6605cbc9cf2') (other versions: 3.0.0)
    * (old features: alloc, fiat-crypto, fiat_u64_backend, std)
```

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M x25519-dalek 1.1.0 (direct third-party, external 'git+https://github.com/novifinancial/x25519-dalek.git?branch=fiat4#4d6e37cee0a2ae0d3df522b3c6286fab6ce607b6')
    * source changed from external 'git+https://github.com/novifinancial/x25519-dalek.git?branch=fiat4#dc82145d8d25529d8aecab93d3ddf7062a74c719'
    * (unchanged features: fiat_u64_backend, std)
  R curve25519-dalek 3.0.0 (transitive third-party, external 'git+https://github.com/calibra/curve25519-dalek.git?branch=fiat3#2940429efd0e6482af1531cff079e6605cbc9cf2') (other versions: 3.0.0)
    * (old features: alloc, fiat-crypto, fiat_u64_backend, std)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M x25519-dalek 1.1.0 (direct third-party, external 'git+https://github.com/novifinancial/x25519-dalek.git?branch=fiat4#4d6e37cee0a2ae0d3df522b3c6286fab6ce607b6')
    * source changed from external 'git+https://github.com/novifinancial/x25519-dalek.git?branch=fiat4#dc82145d8d25529d8aecab93d3ddf7062a74c719'
    * (unchanged features: fiat_u64_backend, std)
  R curve25519-dalek 3.0.0 (transitive third-party, external 'git+https://github.com/calibra/curve25519-dalek.git?branch=fiat3#2940429efd0e6482af1531cff079e6605cbc9cf2') (other versions: 3.0.0)
    * (old features: alloc, fiat-crypto, fiat_u64_backend, std)
```

**Review by sunshowers — APPROVED** [review]

**Comment by metajack** [comment]
@davidiw @mimoo any chance you can look at this?

**Review by mimoo — APPROVED** [review]
thx !!

**Comment by mimoo** [comment]
looks like it is still blocking, I think this needs both my and @davidiw approval?

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M x25519-dalek 1.1.0 (direct third-party, external 'git+https://github.com/novifinancial/x25519-dalek.git?branch=fiat4#4d6e37cee0a2ae0d3df522b3c6286fab6ce607b6')
    * source changed from external 'git+https://github.com/novifinancial/x25519-dalek.git?branch=fiat4#dc82145d8d25529d8aecab93d3ddf7062a74c719'
    * (unchanged features: fiat_u64_backend, std)
  R curve25519-dalek 3.0.0 (transitive third-party, external 'git+https://github.com/calibra/curve25519-dalek.git?branch=fiat3#2940429efd0e6482af1531cff079e6605cbc9cf2') (other versions: 3.0.0)
    * (old features: alloc, fiat-crypto, fiat_u64_backend, std)
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M x25519-dalek 1.1.0 (direct third-party, external 'git+https://github.com/novifinancial/x25519-dalek.git?branch=fiat4#4d6e37cee0a2ae0d3df522b3c6286fab6ce607b6')
    * source changed from external 'git+https://github.com/novifinancial/x25519-dalek.git?branch=fiat4#dc82145d8d25529d8aecab93d3ddf7062a74c719'
    * (unchanged features: fiat_u64_backend, std)
  R curve25519-dalek 3.0.0 (transitive third-party, external 'git+https://github.com/calibra/curve25519-dalek.git?branch=fiat3#2940429efd0e6482af1531cff079e6605cbc9cf2') (other versions: 3.0.0)
    * (old features: alloc, fiat-crypto, fiat_u64_backend, std)
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M x25519-dalek 1.1.0 (direct third-party, external 'git+https://github.com/novifinancial/x25519-dalek.git?branch=fiat4#4d6e37cee0a2ae0d3df522b3c6286fab6ce607b6')
    * source changed from external 'git+https://github.com/novifinancial/x25519-dalek.git?branch=fiat4#dc82145d8d25529d8aecab93d3ddf7062a74c719'
    * (unchanged features: fiat_u64_backend, std)
  R curve25519-dalek 3.0.0 (transitive third-party, external 'git+https://github.com/calibra/curve25519-dalek.git?branch=fiat3#2940429efd0e6482af1531cff079e6605cbc9cf2') (other versions: 3.0.0)
    * (old features: alloc, fiat-crypto, fiat_u64_backend, std)
```

**Pull request closed without merging**
