### PR TITLE
[setup] Support pacman on Arch Linux

### PR DESCRIPTION
**Pull request by adsharma**
## Motivation

Ran dev_setup.sh on arch linux and it failed

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Ran scripts/dev_setup.sh

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by flacks** [comment]
@adsharma Syncing with the repos for installation of dependencies is _not_ a good idea, since a user's system will then be out of sync with upstream. A repo sync should only be done when doing a system upgrade. Please use `-S`.

**Comment by ericnakagawa** [comment]
Thanks for the PR @adsharma. Our team is reviewing your PR and will reply back soon. We're still sorting out CLAs and will reply back with an update.

**Comment by adsharma** [comment]
@flacks: updated the commit to use `pacman -S`

**Comment by flacks** [comment]
@adsharma Thank you!

**Comment by ericnakagawa** [comment]
Hi @adsharma, our contribution process wasn't in place in time to accept and attribute your commit. Future commits will allow you to get GH attribution. I'm also working with the team to improve this process.

**Pull request closed without merging**
