### PR TITLE
Prepend `libra_` to all package names

### PR DESCRIPTION
**Pull request by TristanDebrunner**
## Motivation

This PR is scary big, but it is only cosmetic changes, no functional changes included! To publish to [crates.io](https://crates.io), all packages need to have unique names. Prepending `libra_` to the names of all packages provides unique names for all packages. `libradb` is also renamed to `libra_db` for naming consistency.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Only cosmetic changes, existing tests should suffice.

### CODE REVIEW

**Comment by bmwill** [comment]
I'm slowly going through the process of standardizing our naming of a few different things per #1119 so I think that this should probably change the crate names to be prepended with `libra-` instead of `libra_` (plus change `_` to `-` for names with existing underscores).

**Comment by TristanDebrunner** [comment]
@bmwill I got the `_` to `-` changes done before I noticed #1131 and #1161. My current local state includes both of those. Should I try to rebase on just #1131, wait for #1161, or can we revert #1131 (would make my rebase way easier)?

**Comment by bmwill** [comment]
#1161 should be landing soon so you could wait to rebase on top of that. Though I wonder if your life might be a little bit easier if this was broken up into a number of small commits, and multiple PRs. As it stands there's a very high likely hood that you'll conflict with something somewhere when you touch most of the files in the repo.

**Comment by TristanDebrunner** [comment]
Closing in favor of PRs with smaller pieces. First is #1226

**Pull request closed without merging**
