### PR TITLE
Adding linked list for the buffer manager(138)

### PR DESCRIPTION
**Pull request by rohitaccn**
### Motivation
This PR is built on top of https://github.com/diem/diem/pull/9081, the starting commit for this PR is the 5th commit
https://github.com/diem/diem/commit/69f299c1dc69ebfe696595a5cc64836301643ae4 [diem-framework] update specs for the new invariant processing pipeline
This is also the core commit of this PR, all other commits in this PR are caused by this commit.

The best way to review this PR will be reviewing the DF spec changes and then go over the subsequent PRs one by one.

- fixup! [diem-framework] update specs for the new invariant processing pipeline:This commit updates the auto-generated doc in diem-framework, which is not very interesting
- [move-prover] re-enable the verification of diem-framework
This commit re-enables the verification of diem-framework spec, which is disabled in https://github.com/diem/diem/pull/9081

- [diem-framework][df-cli] add/use a testing version of set_time_has_started.
This commit added a new public function set_time_has_started_for_testing because set_time_has_started
is now public(friend) in order to delegate invariant checking to its caller (which is Genesis::initialize()).
Unfortunately, the customized genesis module in df-cli relies on that and same for the unit-test
DiemTimestampTests.move. Therefore, we created a public version as a temporary solution. We need
a better way to solve this dependency issue in a separate PR.

- fixup! [diem-framework][df-cli] add/use a testing version of set_time_has_started
This commit updates the auto-generated doc in diem-framework, which is not very interesting

- [language-e2e-tests] update the gas cost due to changes in df
This commit updates the golden files in the language-e2e-tests, and the reason for this change is the
addition of DiemTimestamp::assert_operating(); in create_designated_dealer and create_child_vasp_account
changes the gas consumption.

### Test Plan 
* All changes are covered by the existing tests in the CI/CD .

--------------------------------------------------------------------------------------------------
### Motivation

This PR provides some small cleanups for the mempool and consensus notification interfaces used by state sync. The PR offers the following commits:

1.First, we make the notification receiver in MempoolNotificationListener private so that users of the listener don't need to 
   know how the listener is implemented (e.g., using channels). This reduces dependencies and improves the interface 
   abstraction. Similarly, we make the constructors for MempoolNotifier and MempoolNotificationListener private so that the 
   pair can only ever be created and managed together (highlighting their relationship).
2.Second, we do as above, but for the ConsensusNotifier and ConsensusNotificationListener interfaces. Moreover, we clean up 
   some of the constants in the test code.
3.Finally, we remove the requirement for consensus to depend on the mempool-notifications crate (this was only required to 
   access the CommittedTransaction struct). We achieve this by renaming TransactionExclusion to TransactionSummary and 
   using TransactionSummary in place of the CommittedTransaction struct (as both structs are identical!). This also removes the 
   unnecessary duplication and dependencies.

### Test Plan
* All changes are covered by the existing tests in the CI/CD .

--------------------------------------------------------------------------------------------------

### Motivation
Add linked list for buffer manager

### Test Plan
* All changes are covered by the existing tests in the CI/CD .

------------------------------------------------------------------------
### Motivation
Buffer manager outline

### Test Plan
* All changes are covered by the existing tests in the CI/CD .

------------------------------------------------------------------------
### Motivation
Bridge the move resource with corresponding on-chain config Rust struct, so it can be used in consensus.

This PR adds the DiemConsensusConfig::initialize in genesis and add the config id in REGISTRY, so existing chain has to initialize the config before deploying this change otherwise the code would panic with failing to access the on chain config.

### Added Tests
* cargo test --package state-sync-v1 --lib -- executor_proxy::tests::test_pub_sub_consensus_config --exact --nocapture

------------------------------------------------------------------------
### Motivation
Process incoming ordered blocks and sync requests

### Test Plan
* All changes are covered by the existing tests in the CI/CD .

--------------------------------------------------------------------------
### Motivation
decouple waypoint update and epoch changes

### Test Plan
* All changes are covered by the existing tests in the CI/CD .

### CODE REVIEW

**Review by dhaneshacn — APPROVED** [review]

**Comment by ankitkacn** [comment]
Closing this PR due to technical issue, raised new PR https://github.com/diem/diem/pull/10693

**Pull request closed without merging**
