### PR TITLE
[crypto] x25519::PrivateKey -> x25519::X25519PrivateKey

### PR DESCRIPTION
**Pull request by mimoo**
Currently other types of keys in crypto/ are fully named.
For example ed25519::Ed25519PrivateKey.

Let's keep it consistent.

### CODE REVIEW

**Comment by matbd** [comment]
Nice, thanks!

If anyone pushes back, as far as the YAML file is concerned, note that `#[serde(rename="X25519PrivateKey")]` would do it too.

**Comment by davidiw** [comment]
> Nice, thanks!
> 
> If anyone pushes back, as far as the YAML file is concerned, note that `#[serde(rename="X25519PrivateKey")]` would do it too.

@mimoo, can we not do this to the ed25519 keys instead? and go back in the other direction <3

**Comment by mimoo** [comment]
@matbd I'm familiar with a field rename, but you're talking about a type rename by having this annotation before a type definition?

**Comment by matbd** [comment]
> The approach in #3441 seemed to be simpler. It was deemed "blocked by Mathieu's tool" (what of it?), but I understood this to be just a delay. Why the change of tack?

What did not work technically for me in #3441 is trying to infer Rust namespaces automatically. I can work with explicitly qualified public names (e.g. `#[serde(rename = "qualified::Name")]`) but people did not seem to be very enthusiastic about it when I brought up the idea. (Partly because you end up adding ``#[serde(rename = ".."` to every serializable object)

**Comment by davidiw** [comment]
What's the plan here @mimoo?

**Pull request closed without merging**
