### PR TITLE
[move prover] add transformation in reaching definition analysis

### PR DESCRIPTION
**Pull request by emmazzz**
## Motivation

This PR uses reaching definition analysis to remove the redundant assignments(Move/Store/CopyLocs) from stackless bytecode.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

cargo test

### CODE REVIEW

**Comment by emmazzz** [comment]
@shazqadeer @wrwg 
I modified borrow analysis so that StoreLoc and MoveLoc are treated the same way as CopyLoc. This could be incorrect though.

**Comment by wrwg** [comment]
> [move-prover] Move Prover test (`language/move-prover/cargo test`) on commit [ccd1758](https://github.com/libra/libra/commit/ccd1758117f18e87d432aa91c8c2957621bc1f40) did **fail**. See [details](https://github.com/mimoo/mirai-bot/runs/743468950?check_suite_focus=true#step:7:1).

I believe you need to sync to get rid of the crash in libra_account.move (I turned verification off for this module with a pragma because of the crash 1-2 days ago).

Regards the baseline diffs, some are expected, but there seems to be a new error in invalid_branch baseline. This might actually mean that you are fixing this. IIRC there was an issue with Shaz memory model and maybe it is this one. In any case, a test function named invalid or incorrect is expected to fail.

**Comment by emmazzz** [comment]
> > [move-prover] Move Prover test (`language/move-prover/cargo test`) on commit [ccd1758](https://github.com/libra/libra/commit/ccd1758117f18e87d432aa91c8c2957621bc1f40) did **fail**. See [details](https://github.com/mimoo/mirai-bot/runs/743468950?check_suite_focus=true#step:7:1).
> 
> I believe you need to sync to get rid of the crash in libra_account.move (I turned verification off for this module with a pragma because of the crash 1-2 days ago).
> 
> Regards the baseline diffs, some are expected, but there seems to be a new error in invalid_branch baseline. This might actually mean that you are fixing this. IIRC there was an issue with Shaz memory model and maybe it is this one. In any case, a test function named invalid or incorrect is expected to fail.

I fixed some of the baseline diffs, where the only differences are some line/column numbers. However, some tests related to loop invariants seem to be failing, such as `loops.move` and `specs_in_fun_ref.move`. Any idea what might have happened here? @wrwg @shazqadeer

**Pull request closed without merging**
