### PR TITLE
[rust] rollback to 1.43.1 to support fuzzing and coverage -- rocksdb-sys compile fails on 1.44.0

### PR DESCRIPTION
**Pull request by rexhoffman**
## Motivation

Code coverage and fuzzing

### Have you read the [Contributing Guidelines on pull requests]

yes

## Test Plan

ci

### CODE REVIEW

**Comment by metajack** [comment]
Looks like you'll need to unfix one of the lints.

**Comment by davidiw** [comment]
Why not 

@bors-libra r=metajack
?

**Comment by rexhoffman** [comment]
@metajack @davidiw had to rebase with more linting changes - please take a look.

**Comment by rexhoffman** [comment]
And I need good refactoring tools..... vscode isn't cutting it.

**Comment by rexhoffman** [comment]
@metajack I'm a little surprise by all the changes that were required to rollback, I'm not sure if the linter isn't missing some true-positive cases in 1.44.0

**Comment by davidiw** [comment]
> @metajack I'm a little surprise by all the changes that were required to rollback, I'm not sure if the linter isn't missing some true-positive cases in 1.44.0

everyone should use VIM!

**Comment by rexhoffman** [comment]
@davidiw yep, I was open to looking for ways to make this less invasive/potentially damaging.

**Comment by metajack** [comment]
Seems fine but needs squashing before landing.

**Pull request closed without merging**
