### PR TITLE
[fuzzing] adding artifact on client-side crash

### PR DESCRIPTION
**Pull request by mimoo**
This adds a regression test for a client-side crash that the fuzzer found in proof verifications.

### CODE REVIEW

**Comment by bmwill** [comment]
@mimoo You're going to have to fix the issue the fuzzer found before landing this change

**Comment by mimoo** [comment]
oh damn, I need to rebase indeed :)

**Comment by wqfish** [comment]
I think the problem is that the linter isn't happy with this file. Is it a binary? The linter probably doesn't need to check these files.

**Comment by mimoo** [comment]
@metajack do you have an idea?

**Comment by bmwill** [comment]
Probably just need to add in a list of exclusions so that lints skip over a particular set of files.

**Comment by mimoo** [comment]
oh damn, needs a re-approval @wqfish or @bmwill pls :D

**Pull request closed without merging**
