### PR TITLE
[cluster-test] Dont wait for completion on scale down during cluster teardown

### PR DESCRIPTION
**Pull request by ankushagarwal**
## Summary

* During teardown, set wait_to_completion = false for scale down
* During cluster-test init, try to scale down again, but with wait_to_completion = true
* This allows the ASG to scale down in the background when cluster-test is not running and hence reduce overall cluster test run duration

### CODE REVIEW

**Comment by snakech** [comment]
May I ask the reason we wanna scale down as well during cluster-test init?

**Comment by ankushagarwal** [comment]
@snakech The previous scale down might not have completed since we set `wait_for_completion=false`. Hence we are calling  it during init with `wait_for_completion=true` to ensure that it completes successfully before calling scale_up.

**Comment by snakech** [comment]
> @snakech The previous scale down might not have completed since we set `wait_for_completion=false`. Hence we are calling it during init with `wait_for_completion=true` to ensure that it completes successfully before calling scale_up.

Make sense, thx for explanation @ankushagarwal

**Pull request closed without merging**
