### PR TITLE
[execution][logger] Change one log from info! to debug!.

### PR DESCRIPTION
**Pull request by changyonghu**
This log prints out a lot in cluster test running.

### CODE REVIEW

**Comment by andll** [comment]
Is this really printed freaquently in cluster test?
I would imagine genesis only created once?

**Comment by changyonghu** [comment]
> Is this really printed freaquently in cluster test?
> I would imagine genesis only created once?

I see. Let me check which function calls this.

**Comment by changyonghu** [comment]
> > Is this really printed freaquently in cluster test?
> > I would imagine genesis only created once?
> 
> I see. Let me check which function calls this.

Ok. create-and-insert-waypoint will call generate_waypoint, which in turn calls calculate_genesis. I think this info! actually means waypoint calculated.

**Comment by andll** [comment]
Is `create-and-insert-waypoint` something we have to call per-validator/node?

**Comment by changyonghu** [comment]
> Is `create-and-insert-waypoint` something we have to call per-validator/node?

https://github.com/libra/partners/blob/master/testnet/testnet/templates/genesis.yaml#L88
In testnet, yes.

**Comment by changyonghu** [comment]
> > Is `create-and-insert-waypoint` something we have to call per-validator/node?
> 
> https://github.com/libra/partners/blob/master/testnet/testnet/templates/genesis.yaml#L88
> In testnet, yes.

Yes, this is a bit confusing. Maybe we only need to call once. We don't need the waypoint.txt file?

**Comment by andll** [comment]
Waypoint is same across all validators(its just description of the state of blockchain)

We might want to have `waypoint.txt` at some point on cluster test, but I am not sure why we need to create it more then once

**Comment by changyonghu** [comment]
> Waypoint is same across all validators(its just description of the state of blockchain)
> 
> We might want to have `waypoint.txt` at some point on cluster test, but I am not sure why we need to create it more then once

Let me check with @mgorven

**Pull request closed without merging**
