### PR TITLE
[Proof] Re-implement custom serialization for AccumulatorProof

### PR DESCRIPTION
**Pull request by wqfish**
## Motivation

(Write your motivation for proposed changes here.)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

(Share your test plan here. If you changed code, please provide us with clear instructions for verifying that your changes work.)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by davidiw** [comment]
Curious what we gain by doing this?

**Comment by lightmark** [comment]
@davidiw smaller-size proofs

**Comment by davidiw** [comment]
> @davidiw smaller-size proofs

Haha, of course, but what does that mean in terms of proof size? Is it a few hundred bytes or maybe KB? Or could it stretch to even larger for things like LEC?

**Comment by davidiw** [comment]
If you want this in, best to get this in ASAP as this is a client-side breaking change.

**Comment by davidiw** [comment]
code freeze, feel free to re-open if required, etc etc

**Pull request closed without merging**
