### PR TITLE
[config] remove chain_id from config

### PR DESCRIPTION
**Pull request by davidiw**
We can rely on test chain_id in many cases, so ... let's do that. For
the rest of the cases, chain_id is only on the chain, this makes it
clear what we're doing with chain id... or at least less confusing.

### CODE REVIEW

**Comment by davidiw** [comment]
> so config builder always build with ChainId::test()? I remember before the prod testnet didn't use that one

No, config-builder works as expected? genesis config builder is only used for smoke tests now.

**Comment by zekun000** [comment]
> No, config-builder works as expected? genesis config builder is only used for smoke tests now.

you remove the template there which is how the different chain id being populated iirc.

**Comment by davidiw** [comment]
> > No, config-builder works as expected? genesis config builder is only used for smoke tests now.
> 
> you remove the template there which is how the different chain id being populated iirc.

No, config-builder needs it from the CLI. Passing it via the template won't work even in the current code. The template was only used by the genesis config builder and that's not safe anyway -- so if we want it for that code base, we need to deal with it later.

**Pull request closed without merging**
