### PR TITLE
Remove a horrible regex from nextgen_crypto

### PR DESCRIPTION
**Pull request by vainiovano**
## Motivation

Using a regex for checking numbers is not very optimal

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

I added some tests for `is_valid_path`

### CODE REVIEW

**Comment by kchalkias** [comment]
@vainiovano thanks for your contribution in Libra's codebase. Some comments regarding your PR:
a) I would recommend adding a unit test and try to cover as many edge cases as possible.
b) Also, you will need an extra check that the path does not start or ends with "/", for instance "/m/3" is considered invalid.
c) There is an unused import in slip0010.rs, please remove `use regex::Regex;`
c) Please rebase and merge any potential conflicts
c) Note that you will need to sign our CLA if you want to be credited for this work. Please check our [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests) carefully to ensure you meet all of the requirements.

**Comment by vainiovano** [comment]
I don't want to sign a document for just one pull request. I don't need to be credited for this work.

**Comment by bmwill** [comment]
Thanks for working on this! A few quick notes about our workflow:

* In order to maintain a linear history we would prefer it if you could rebase your changes on top of master instead of merging it into your branch.
* We also prefer [atomic commits](https://en.wikipedia.org/wiki/Atomic_commit#Atomic_commit_convention) so instead of responding to reviewer comments by adding additional commits on top of your branch its preferable to amend your existing commits.

**Comment by vainiovano** [comment]
I don't actually need an extra check for starting or ending with "/". If a path starts with "/" the first element of the iterator is empty and not equal to "m". If the path ends with "/" the last element of the iterator is empty and not a number.

**Comment by kchalkias** [comment]
@vainiovano nice, thanks for testing it and amending your commits.

**Comment by kchalkias** [comment]
Closing this PR as we've now included the recommended solution to our codebase. 
Thank you @vainiovano once again.

**Pull request closed without merging**
