### PR TITLE
[crypto, language, mempool, types] Even more combinator refactorings

### PR DESCRIPTION
**Pull request by huitseeker**
```
result match {
  case Err(x) => Err(f(x))
  case Ok(x) => Ok(x)
}
``` 
is `result.map_err(f)`

```
result match {
  case Err(x) => foo(x)
  case Ok(x) => Ok(x)
}
``` 
is `result.or_else(|x| foo(x))` (unless it fits in the previous case)

```
if let Some(x) = outerpattern {
  if let Some(y) = innerpattern(x) {
 ...
  }
}
``` 
is often (though [not always](https://github.com/libra/libra/pull/982/files#r325742507)) 
```
if let Some(y) = outerpattern.and_then(|x| innerpattern(x)) {
 ...
}
```

```
result match {
  Ok(_) => true
  None => false
}
```
is `result.is_ok()`

### CODE REVIEW

**Comment by metajack** [comment]
Is this ready to r+ or are you still working?

**Comment by bmwill** [comment]
Were these found via some set of clippy lints which we don't have turned on?

**Comment by huitseeker** [comment]
@metajack added one commit, will squash in the next few mins if that's ok w/ everybody?
@bmwill unfortunately no :(

**Comment by metajack** [comment]
I would prefer you not squash these. They are very nicely organized.

**Comment by huitseeker** [comment]
@metajack I'm happy with that as well, in which case: where's my r+ at?

**Pull request closed without merging**
