### PR TITLE
[aws][code-build] Enable ad-hoc code build for all images

### PR DESCRIPTION
**Pull request by rustielin**
## Motivation

Add CodeBuild support for init, mint, and safety-rules so we can build those images ad-hoc instead of waiting for continuous push.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

When configs have been added on AWS side:

```
./docker/build-aws.sh --build-all --version pull/4135
```

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by sherry-x** [comment]
Seems missing some permission
```
An error occurred (AccessDeniedException) when calling the StartBuild operation: User: arn:aws:sts::853397791086:assumed-role/github-actions/3c7f4343dce84058bd526b435c757dae is not authorized to perform: codebuild:StartBuild on resource: arn:aws:codebuild:us-west-2:853397791086:project/libra-init
```

**Comment by rustielin** [comment]
fixing

**Comment by rustielin** [comment]
https://github.com/novifinancial/libra-ops/pull/576 @sherry-x

**Comment by andll** [comment]
This diff introduced quite a few images that are now built when we are running cti and cluster test, and some of those images(init and mint) are not used by cluster test.
Few question:
1) What use case do we have for aws-build.sh that needs mint or init image? Currently only two use case of this script I see is basically cti and land_blocking.yml, do we plan some future use case for init/mint?
2) Can we make building of init and mint optional, hidden under some flag like `--build-mint` and `--build-init`? It does not feel right to burn resources on building them when we don't need them in majority of use cases

**Comment by rustielin** [comment]
@andll 

> 1. What use case do we have for aws-build.sh that needs mint or init image? Currently only two use case of this script I see is basically cti and land_blocking.yml, do we plan some future use case for init/mint?

Agreed that they currently don't have much use outside of land blocking tests and cti. Perhaps this is a question for @sausagee and team? is it important to check if the docker build has not been broken in the PR? or are there some future tests that require the extra images? Might be helpful for compat network to use some in test. 

> 2. Can we make building of init and mint optional, hidden under some flag like `--build-mint` and `--build-init`? It does not feel right to burn resources on building them when we don't need them in majority of use cases

Definitely; I can do that now and we can add the extra images back into the build later if required.

**Comment by rustielin** [comment]
Fix for now: https://github.com/libra/libra/pull/4360

**Pull request closed without merging**
