### PR TITLE
Remove unused deps

### PR DESCRIPTION
**Pull request by metajack**
These were found with cargo-udeps and then some hand grepping to verify.

### CODE REVIEW

**Comment by davidiw** [comment]
This is great, are there more additions you would like to make?

**Comment by metajack** [comment]
I'm done unless it fails to build again :)

**Comment by metajack** [comment]
Note that I squashed this because otherwise I would have had to go through each commit doing builds to get the correct Cargo.lock changes to keep every commit separately buildable. It seemed more work than was worthwhile.

**Comment by davidiw** [comment]
Note the conflicts

**Pull request closed without merging**
