### PR TITLE
[functional_tests] Added a sorted linked list example

### PR DESCRIPTION
**Pull request by Goharshady**
## Motivation

The new files implement a distributed sorted linked list, i.e. a linked list whose every node is stored as a resource in a different account. They do not touch any of the core modules and just add new functional tests. The initial idea behind this data structure was to implement a DNS, but it can be used for many other use-cases where we need to store vast amounts of data and hence have to distribute them among accounts.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

The PR only adds functional tests

### CODE REVIEW

**Comment by vgao1996** [comment]
@sblackshear Two ways I can think of:
1) Put all tests into one file so to not duplicate the SortedLinkedList module. Caveat: some tests require a clean state to start with. It would be annoying to revert the changes made or create new accounts for each test.
2) Add `//! include: file path` to functional tests. This is useful to the "big library + many tests" pattern in general.

What do you guys think?

**Comment by tzakian** [comment]
I am in favor of the `//! include file path` to functional tests. I think this will be a good thing to have in general for testing out non-stdlib modules in multiple files.

**Comment by vgao1996** [comment]
Aright let's go with the `//! include` approach. Here's a more detailed proposal: we add a "preprocessing" phase that replaces each `//! include` with the content of the file specified. This happens before parsing all the configs & directives. Err If the file included contains any `//! include`. (We can always relax this rule in the future.)

I considered some alternatives with stricter rules, like stripping out certain or all comments in the included file, or requiring the content included to be a single transaction etc., but found them confusing due to the complexity they bring in. The C style include can be abused if not handled carefully, but I still think it's one of the easiest in terms of both implementation & usage, and shouldn't be a problem given our limited context (tests).

@sblackshear @Goharshady @tzakian Sounds good to you?

**Comment by Goharshady** [comment]
I think the problem is not really with including a library file, but with how the //! check directive works. I just wrote a post in Calibra Move Language about this.

**Comment by vgao1996** [comment]
Talked to @Goharshady offline and resolved the confusion. @Goharshady will merge all tests into one file. (Right now it seems like he's enumerating the O(2^n) success/failure states of n transactions.)

Nonetheless `//! include` is still worth considering. Let's continue the discussion off this PR.

**Comment by sblackshear** [comment]
Agreed that 
- merging the tests into a single file is the right way to go here
-`//! include` is independently useful and is worth discussing elsewhere

**Pull request closed without merging**
