### PR TITLE
29% size reduction of image assets using lossless compression from ImgBot

### PR DESCRIPTION
**Pull request by armujahid**
## Beep boop. Your images are optimized!

Your image file size has been reduced by **29%** 🎉

<details>
<summary>
Details
</summary>

| File | Before | After | Percent reduction |
|:--|:--|:--|:--|
| /libra.png | 14.20kb | 4.63kb | 67.38% |
| /.assets/libra.png | 14.20kb | 4.63kb | 67.38% |
| /storage/data.png | 574.90kb | 421.59kb | 26.67% |
| | | | |
| **Total :** | **603.29kb** | **430.86kb** | **28.58%** |
</details>

---

[📝docs](https://imgbot.net/docs) | [:octocat: repo](https://github.com/dabutvin/ImgBot) | [🙋issues](https://github.com/dabutvin/ImgBot/issues) | [🏅swag](https://goo.gl/forms/1GX7wlhGEX8nkhGO2) | [🏪marketplace](https://github.com/marketplace/imgbot)

## Motivation

This is an automatic image optimization commit from ImgBot

### Have you read the [Contributing Guidelines on pull requests](../CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

No testing is required since this is a signed commit from [ImgBot](https://github.com/ImgBotApp) related to lossless compression of images.

## Related PRs

N/A

### CODE REVIEW

**Comment by ericnakagawa** [comment]
Thanks for the PR @armujahid. We could definitely use better compression on our image binaries. Our team is reviewing your PR and will reply back soon. We're still sorting out CLAs and will reply back with an update.

**Comment by bmwill** [comment]
@huitseeker bors should be able to handle this, so as long as we can merge it we shouldn't need anything from the original contributor

**Comment by armujahid** [comment]
@huitseeker yes I have already seen CLA. This commit is from a bot so I am not its original author anyway. I will rebase it today to trigger CI hooks again.

**Comment by armujahid** [comment]
Rebased :) I have also sent my signed CLA

**Comment by ericnakagawa** [comment]
@armujahid Thanks for the contribution. Your CLA has been received.

**Pull request closed without merging**
