### PR TITLE
Subscribe to potential JSON-RPC api change PRs

### PR DESCRIPTION
**Pull request by thefallentree**

### CODE REVIEW

**Comment by davidiw** [comment]
:O how does this work!?

**Comment by thefallentree** [comment]
> :O how does this work!?

for now it just adds us to the PR, and the admin can also set PR not mergeable (even apply to boras) unless PR is approved by the owner

**Comment by davidiw** [comment]
I'm all for sending @phoenix-antigravity some extra emails

@bors-libra r+

**Comment by andll** [comment]
I am curious how would that restriction apply to bors? Don't it just push some different commit without touching PR itself(aside from mentioning it in comment)?

**Comment by thefallentree** [comment]
> I am curious how would that restriction apply to bors? Don't it just push some different commit without touching PR itself(aside from mentioning it in comment)?

If you in repo settings set the Merge restrictions, then if the PR is not approved (on github) then bors-libra 's final merge will fail .  bors-libra obviously doesn't understand PR approvals, so it will just try and fails.

**Comment by thefallentree** [comment]
> I am curious how would that restriction apply to bors? Don't it just push some different commit without touching PR itself(aside from mentioning it in comment)?

github is smart enough to know the if the same commit hash is being pushed, it is same as PR being merged.

**Comment by andll** [comment]
> github is smart enough to know the if the same commit hash is being pushed, it is same as PR being merged
But bors pushes different commit hash...

**Pull request closed without merging**
