### PR TITLE
sdk: release v0.0.2

### PR DESCRIPTION
**Pull request by bmwill**
This PR does the following:
* Adds a README to the sdk crate as well as a doc example for a simple p2p transfer on testnet
* Releases v0.0.2 of the sdk to crates.io

### CODE REVIEW

**Review by kchalkias — APPROVED** [review]
LGTM, just the clippy whitespace issue on readme.

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M diem-crypto 0.0.2 (workspace, path 'crypto/crypto')
    * version upgraded from 0.0.1
    * (unchanged features: default, fiat)
  M diem-types 0.0.2 (workspace, path 'types')
    * version upgraded from 0.0.1
    * (unchanged features: default)
  M move-core-types 0.0.2 (workspace, path 'language/move-core/types')
    * version upgraded from 0.0.1
    * (unchanged features: default)

host packages:
  M diem-crypto-derive 0.0.2 (workspace, path 'crypto/crypto-derive')
    * version upgraded from 0.0.1
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M diem-crypto 0.0.2 (workspace, path 'crypto/crypto')
    * version upgraded from 0.0.1
    * (unchanged features: default, fiat)
  M diem-types 0.0.2 (workspace, path 'types')
    * version upgraded from 0.0.1
    * (unchanged features: default)
  M move-core-types 0.0.2 (workspace, path 'language/move-core/types')
    * version upgraded from 0.0.1
    * (unchanged features: default)

host packages:
  M diem-crypto-derive 0.0.2 (workspace, path 'crypto/crypto-derive')
    * version upgraded from 0.0.1
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M diem-client 0.0.2 (workspace, path 'sdk/client')
    * version upgraded from 0.0.1
    * (unchanged features: blocking, ipnet, ureq)
  M diem-crypto 0.0.2 (workspace, path 'crypto/crypto')
    * version upgraded from 0.0.1
    * (unchanged features: default, fiat)
  M diem-json-rpc-types 0.0.2 (workspace, path 'json-rpc/types')
    * version upgraded from 0.0.1
    * (unchanged features: [none])
  M diem-transaction-builder 0.0.2 (workspace, path 'sdk/transaction-builder')
    * version upgraded from 0.0.1
    * (unchanged features: default)
  M diem-types 0.0.2 (workspace, path 'types')
    * version upgraded from 0.0.1
    * (unchanged features: default)
  M move-core-types 0.0.2 (workspace, path 'language/move-core/types')
    * version upgraded from 0.0.1
    * (unchanged features: default)

host packages:
  M diem-crypto-derive 0.0.2 (workspace, path 'crypto/crypto-derive')
    * version upgraded from 0.0.1
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M diem-crypto 0.0.2 (workspace, path 'crypto/crypto')
    * version upgraded from 0.0.1
    * (unchanged features: default, fiat)
  M diem-types 0.0.2 (workspace, path 'types')
    * version upgraded from 0.0.1
    * (unchanged features: default)
  M move-core-types 0.0.2 (workspace, path 'language/move-core/types')
    * version upgraded from 0.0.1
    * (unchanged features: default)

host packages:
  M diem-crypto-derive 0.0.2 (workspace, path 'crypto/crypto-derive')
    * version upgraded from 0.0.1
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M diem-client 0.0.2 (workspace, path 'sdk/client')
    * version upgraded from 0.0.1
    * (unchanged features: blocking, ipnet, ureq)
  M diem-crypto 0.0.2 (workspace, path 'crypto/crypto')
    * version upgraded from 0.0.1
    * (unchanged features: default, fiat)
  M diem-json-rpc-types 0.0.2 (workspace, path 'json-rpc/types')
    * version upgraded from 0.0.1
    * (unchanged features: [none])
  M diem-transaction-builder 0.0.2 (workspace, path 'sdk/transaction-builder')
    * version upgraded from 0.0.1
    * (unchanged features: default)
  M diem-types 0.0.2 (workspace, path 'types')
    * version upgraded from 0.0.1
    * (unchanged features: default)
  M move-core-types 0.0.2 (workspace, path 'language/move-core/types')
    * version upgraded from 0.0.1
    * (unchanged features: default)

host packages:
  M diem-crypto-derive 0.0.2 (workspace, path 'crypto/crypto-derive')
    * version upgraded from 0.0.1
    * (unchanged features: [none])
```

**Review by xli — APPROVED** [review]

**Pull request merged**
