### PR TITLE
[subscription-service] generalize ReconfigSubscription to generic subscription service crate in common

### PR DESCRIPTION
**Pull request by christinacelee**
## Summary
- Move out` ReconfigSubscription` from `types` to `common` to remove dependencies 
- Generalize `ReconfigSubscription` to generic `SubscriptionService` framework. More work should be done developing this framework once we have better specs for concrete use cases

### CODE REVIEW

**Comment by thefallentree** [comment]
Thanks for the quick turn-around!

**Comment by n4ss** [comment]
Thanks!

**Pull request closed without merging**
