### PR TITLE
lcs: move to github.com/libra/lcs

### PR DESCRIPTION
**Pull request by bmwill**
Move the lcs code from /common/lcs to be hosted in its own repository
located at github.com/libra/lcs and depend on the published version
v0.1.0 on crates.io.

### CODE REVIEW

**Comment by libra-action** [comment]
**LSR dependency change summary**:
```
target packages:
  M libra-canonical-serialization 0.1.0 (direct third-party, crates.io)
    * source changed from path 'common/lcs'
    * status changed from workspace
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**release binaries dependency change summary**:
```
target packages:
  M libra-canonical-serialization 0.1.0 (direct third-party, crates.io)
    * source changed from path 'common/lcs'
    * status changed from workspace
    * (unchanged features: [none])
```

**Comment by libra-action** [comment]
**LEC dependency change summary**:
```
target packages:
  M libra-canonical-serialization 0.1.0 (direct third-party, crates.io)
    * source changed from path 'common/lcs'
    * status changed from workspace
    * (unchanged features: [none])
```

**Review by matbd — APPROVED** [review]

**Comment by mimoo** [comment]
question: is this the only package we're going to do this with? And why LCS first?

**Pull request merged**
