### PR TITLE
[types] optimize AccountAddress serialization

### PR DESCRIPTION
**Pull request by bmwill**
AccountAddress is currently being serialized as a variable length byte
array despite it having a fixed length resulting in its LCS serialized form
taking an 4 extra bytes to represent a length prefix. This patch changes
AccountAddress's serialized form to drop that length prefix, shrinking
the length of a serialized AccountAddress by 4 bytes.

Ref: #1307

### CODE REVIEW

**Comment by bmwill** [comment]
@davidiw This does not break the LCS spec and there are huge wins with respect to size for eliminating these useless length prefixes.

**Comment by mimoo** [comment]
@davidiw do you mean that it's not clear looking at the code how LCS will serialize/deserialize a byte array? If so I can agree with you, but in the end it's the specification that matters right? 

Working on the consensus specification, I'm probably going to have to formalize an LCS language that will make the difference between variable-length arrays and fixed-length arrays clear.

**Comment by davidiw** [comment]
> @davidiw This does not break the LCS spec and there are huge wins with respect to size for eliminating these useless length prefixes.
> 
> A fixed length array can easily be viewed as a Tuple with all elements being the same type.

It seems that the originally agreed upon specification no longer matches the specification written in code. That should be resolved first.

**Comment by mimoo** [comment]
after discussion it seems like this should work, but we really need a specification to define how all these structures are serialized :)

@bors-libra r+

**Comment by bmwill** [comment]
> ```
> Proposal {
>   payload: []bytes,
>   author: [32]bytes,
>   signature: bytes,
> }
> ```

I'd probably like to stick to something that's more Rust like, e.g.
```
Proposal {
    payload: [u8],
    author: [u8; 32],
    signature: [u8],
```

**Comment by davidiw** [comment]
@mimoo I thought the decision was to hold off on this for now?

**Pull request closed without merging**
