### PR TITLE
docs: Update bug_report.md so bold markdown and comment works

### PR DESCRIPTION
**Pull request by ltfschoen**
## Motivation

Fix so use of bold and comments in markdown works

### Have you read the [Contributing Guidelines on pull requests](../CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

N/A

## Related PRs

https://github.com/libra/website/pull/21

### CODE REVIEW

**Comment by ericnakagawa** [comment]
Thanks for the PR @ltfschoen. Our team is reviewing your PR and will reply back soon. We're still sorting out CLAs and will reply back with an update.

**Comment by ltfschoen** [comment]
@huitseeker ok thanks, i pushed an empty commit to trigger the CI with `git commit --allow-empty -m "empty commit to make CI run"`

**Comment by huitseeker** [comment]
@ltfschoen it seems your PR is based on just the wrong commit unfortunately. Consider doing a `git rebase -i origin/master` after fetching the latest master, and just including your (first) relevant commit.

**Comment by huitseeker** [comment]
Merged as part of #974

**Pull request closed without merging**
