### PR TITLE
[common] rename tools to temppath

### PR DESCRIPTION
**Pull request by davidiw**
Tools was a misnomer since it only contained temppath. Also in the
interest in responsibilty and dependency separation, it makes sense to
move this into its own properly named crate.

Verified that code builds and lints pass.

### CODE REVIEW

**Comment by wqfish** [comment]
Curious why we have this and what is the benefit of using this instead of the [tempfile](https://crates.io/crates/tempfile) crate?

**Comment by davidiw** [comment]
> Curious why we have this and what is the benefit of using this instead of the [tempfile](https://crates.io/crates/tempfile) crate?

There is a substantial number of dependencies in that crate:
cfg-if ^0.1
libc ^0.2.27
rand ^0.7
redox_syscall ^0.1
remove_dir_all ^0.5
winapi ^0.3

**Comment by metajack** [comment]
> Curious why we have this and what is the benefit of using this instead of the [tempfile](https://crates.io/crates/tempfile) crate?

It's addressed in the comment, but I think we should reconsider this.

tempfile is used directly in consensus, and cfg-if and remove_dir_all are used elsewhere in our dependency graph. This isn't actually saving us anything currently.

**Comment by wqfish** [comment]
> > Curious why we have this and what is the benefit of using this instead of the [tempfile](https://crates.io/crates/tempfile) crate?
> 
> It's addressed in the comment, but I think we should reconsider this.
> 
> tempfile is used directly in consensus, and cfg-if and remove_dir_all are used elsewhere in our dependency graph. This isn't actually saving us anything currently.

Yeah, also I assume they should all be dev-dependency and are not in production code, so I'd consider not making our own code for this.

**Comment by metajack** [comment]
> cfg-if ^0.1

This is a pretty standard dependency in the community and is used by lots of packages in our dependency graph. For example the log crate as well as mio use this.

> libc ^0.2.27

I think there is no way to remove libc as a dependency in libra.

> rand ^0.7

The replacement code also uses rand.

> redox_syscall ^0.1
> winapi ^0.3

These aren't deps on linux as they are target specific.

> remove_dir_all ^0.5

This is the only real addition here unique to tempfile's dep graph, but we use tempfile elsewhere in libra. In the safety-rules dep graph specifically, it comes in via rusty-fork via executor. Other crates in libra directly depend on tempfile, such as consensus.

**Comment by metajack** [comment]
> Yeah, also I assume they should all be dev-dependency and are not in production code, so I'd consider not making our own code for this.

It looks like the only non-build/dev dependency that uses tempfile is rusty-fork which is a normal dependency of executor.

**Comment by bmwill** [comment]
Yeah I agree that we should probably use a tempfile crate instead of rolling our own, especially if it doesn't buy us anything

**Comment by davidiw** [comment]
I'll make a note of this conversation and we can evaluate the value of this once we have the full TCB in place.

**Comment by metajack** [comment]
> @bors-libra r+

Please use `@bors-libra r=metajack` instead of `r+` when you are not the reviewer.

**Comment by davidiw** [comment]
> > @bors-libra r+
> 
> Please use `@bors-libra r=metajack` instead of `r+` when you are not the reviewer.

Good call, I got into a bad habit of doing that and have been trying to fix that... is there anyway we can require that if PR owner == comment owner that r+ fails?

**Pull request closed without merging**
