### PR TITLE
[tf] Delete old ECS testnet implementation

### PR DESCRIPTION
**Pull request by mgorven**
This testnet implementation is no longer used or supported.

### CODE REVIEW

**Review by rustielin — APPROVED** [review]

**Comment by lightmark** [comment]
Just found this. Where the dashboards go and what templates are used?

**Comment by mgorven** [comment]
This is a bit messy currently.
The validator deployment dashboards: https://github.com/libra/partners/tree/master/validator/helm/files/dashboards
Testnet dashboards: https://github.com/libra/partners/tree/master/testnet/testnet/files/dashboards
Pre-mainnet central dashboards: https://github.com/novifinancial/libra-ops/tree/master/terraform/central-dashboard/templates/dashboards

**Comment by lightmark** [comment]
I think all the updates to testnet/devnet are gone from some date.

**Pull request closed without merging**
