### PR TITLE
[cherry-pick] add back developers.diem.com with recent changes

### PR DESCRIPTION
**Pull request by jsladerman**
Adds developers.diem.com back into the repo (per #8762) and includes the latest changes made to it re: community references

Also fixed ci-test as it wasn't running the developers-site-build test despite their being changes (ended up being a small fix but required some debugging as seen below)

### CODE REVIEW

**Comment by jsladerman** [comment]
/canary (should work now, needed to debug why `run-developer-site-build` kept skipping)

**Review by eugeneacn — APPROVED** [review]

**Review by KoushikGavini — APPROVED** [review]

**Comment by jsladerman** [comment]
/land (flaky unit test causing issues - unrelated to this PR)

**Pull request merged**
