### PR TITLE
[CircleCI] refactor CI/CD config

### PR DESCRIPTION
**Pull request by phra**
## Motivation

Improve CircleCI configuration to better suit a Rust project:

1. use parallel workflows
2. complete flow for Rust projects
3. avoid installing Debian deps

### Have you read the [Contributing Guidelines on pull requests](../CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

_Not applicable._

## Related PRs

_Not applicable._

### CODE REVIEW

**Comment by phra** [comment]
It seems I cannot start CircleCI builds, I hope it will build. :man_shrugging:

FYI, the config was adapted from https://github.com/phra/rustbuster/blob/master/.circleci/config.yml

**Comment by ericnakagawa** [comment]
Thanks for the PR @phra. This could be useful for speeding up our build times! Our team is reviewing your PR and will reply back soon. We're still sorting out CLAs and will reply back with an update.

**Comment by metajack** [comment]
Are you still interested in completing this work? I apologize for the delay in getting back to you on our side. Let me know if you're still game, and I'll help get you sorted, otherwise with your permission I can take over the work here.

**Comment by phra** [comment]
hi @metajack , I noticed now the conflicts.. should I simply resolve them or something else?

**Comment by bmwill** [comment]
Closing in favor of #908

**Pull request closed without merging**
