### PR TITLE
[language, vm_validation, admission_control, execution] Update the representation of VM statuses

### PR DESCRIPTION
**Pull request by tzakian**
Change the external and internal representation of VM statuses and
errors to be the same. At the same time, update the representation of
externally facing errors to be of the form
```
major_status, optional<sub_status>, optional<message>
```
The only required field being the major status. The sub_status and
message are optional (and may depend on the error type).

Note that verification errors from the VM are no longer a list of errors
-- we only return one now. If the submitter wants more information
they'll need to run it offline.

While large most parts of this PR are pretty straightforward. The only real places to focus inspection are:

* All files under `types/`
* The handling of error outputs from the prologue in `txn_executor.rs`
* Various places in the bytecode verifier.

### CODE REVIEW

**Comment by shazqadeer** [comment]
Looks good to me.

**Comment by dariorussi** [comment]
this looks good to me to. And following your guideline of what to look for is very helpful.
It would be good if others looked at this and shared feelings, if any

**Pull request closed without merging**
