### PR TITLE
fix typo in github workflow step

### PR DESCRIPTION
**Pull request by jnaulty**
**Before**
Screen Shot 2020-08-20 at 4 35 40 PM

**After**
Screen Shot 2020-08-20 at 4 36 30 PM

### CODE REVIEW

**Comment by bmwill** [comment]
I'm sitting here trying to figure out why bors didn't move this PR into the Queue, then I realized you moved it on the project board before calling `/land` 🙃

**Comment by rexhoffman** [comment]
OCD indeed to move the card first :D

I'll miss that typo, it always brought a smile to my face.

**Comment by jnaulty** [comment]
> I'm sitting here trying to figure out why bors didn't move this PR into the Queue, then I realized you moved it on the project board before calling `/land` upside_down_face

Yeah, I wasn't sure how to 'land' and was just testing things out with the PR interface. I looked in the repo and didn't see any reference to it (perhaps I missed it :thinking: )
I also saw this was using bors, but didn't see `/land` mentioned at all in https://bors.tech/documentation/

**Comment by mimoo** [comment]
/help

^ you can do this thing as well

**Pull request merged**
