### PR TITLE
[docker] update base image to debian:buster-20210902-(137)

### PR DESCRIPTION
**Pull request by vikalpacn**
## Motivation
_**[docker] update base image to debian**_
Update debian base image.  This lumps all 7 outstanding dependabot PRs #9083 ~ #9090.

## Test Plan
CI + canary

## Motivation
_**[docker] fix up base image for DLC**_
#9112 missed updating the validator's base image (#9084 was still open) and resulted DLC misses in build (ex https://github.com/diem/diem/runs/3551074624?check_suite_focus=true).  This PR includes the missed update.
 
Additionally, specify base image only once across all Dockerfiles following the facuet's example to reduce edits in future updates.

## Test Plan
CI + canary (https://github.com/diem/diem/runs/3551145597?check_suite_focus=true verified DLC miss is fixed.)

## Motivation
_**[Forge] Add forge LBT in ci-test**_
Related PR link- https://github.com/diem/diem/pull/9039

##  Test plan-
CI/CD tests are covered

### CODE REVIEW

**Review by dhaneshacn — APPROVED** [review]

**Comment by ankitkacn** [comment]
Closing this PR due to technical issue, raised new PR https://github.com/diem/diem/pull/10719

**Pull request closed without merging**
