### PR TITLE
[db-bootstrap] better error message

### PR DESCRIPTION
**Pull request by zekun000**
## Motivation

(Write your motivation for proposed changes here.)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

(Share your test plan here. If you changed code, please provide us with clear instructions for verifying that your changes work.)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/libra/developers.libra.org, and link to your PR here.)

### CODE REVIEW

**Comment by msmouse** [comment]
https://github.com/libra/libra/pull/6229/commits/81bbdabbdabf4d05e971404fa2c7bb4cb9cd7a32

the tree state should be logged in the db call, you don't see it?

**Comment by zekun000** [comment]
oh we only look at why genesis is skipped, I guess I can print waypoint only.

**Comment by msmouse** [comment]
how about using structured logging..

**Comment by zekun000** [comment]
you're so fancy

**Review by msmouse — APPROVED** [review]
I was born fancy.

**Review by davidiw — APPROVED** [review]

**Pull request closed without merging**
