### PR TITLE
[language] kill bytearray type

### PR DESCRIPTION
**Pull request by vgao1996**
## Summary
This gets the bytearray type removed from Move. 

Note: byte array values still exist in the file format & source compiler, with type `vector<u8>`. 

## Test Plan
cargo test

### CODE REVIEW

**Comment by vgao1996** [comment]
@wrwg @junkil-park I didn't remove bytearrays from bytecode-to-boogie -- they are just unreachable though. Let me know if this is fine for now! If not I can put up a followup PR to delete those.

**Comment by vgao1996** [comment]
Hmm... I did update the baseline files for Move prover. Could it be that I'm using a different version of boogie?

**Comment by wrwg** [comment]
> Hmm... I did update the baseline files for Move prover. Could it be that I'm using a different version of boogie?

Have you rebased since yesterday afternoon?

**Comment by junkil-park** [comment]
CI uses boogie 2.5.7.

**Comment by vgao1996** [comment]
@wrwg I might have not -- trying to rebase and run it again now.

**Comment by vgao1996** [comment]
Nope, it still doesn't output those on my machine, and I am using version 2.5.7.

**Comment by junkil-park** [comment]
Just to make sure. Did you do `UPBL=1 cargo test` in the `language/move-prover' directory to generate the baseline files?

**Comment by vgao1996** [comment]
Yes. That's exactly I did.

**Comment by wrwg** [comment]
I suggest to go ahead and just merge this even if the prover tests fail. We figure then out later.

@junkil-park @DavidLDill

**Comment by junkil-park** [comment]
@vgao1996, could you delete the line #4 in `language/move-prover/tests/sources/stdlib.move`, and retry? The line to delete is:
  `// dep: ../stdlib/modules/bytearray_util.move`.

**Comment by vgao1996** [comment]
Yeah I reverted that file by mistake. It should be good now.

**Comment by junkil-park** [comment]
Prover test passed on your latest commit! (log: https://github.com/mimoo/mirai-bot/runs/512012082?check_suite_focus=true)

**Comment by vgao1996** [comment]
@tnowacki I've fixed the test you mentioned. Thanks for catching this!

**Pull request closed without merging**
