### PR TITLE
[language][prover] Update translator_tests.rs

### PR DESCRIPTION
**Pull request by junkil-park**
Fixed the failed test "test_access_path"
- By adding the test flag "--native-stubs" to generate the native function declarations to properly feed Boogie

## Motivation

(Write your motivation for proposed changes here.)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

(Share your test plan here. If you changed code, please provide us with clear instructions for verifying that your changes work.)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by junkil-park** [comment]
I closed the last PR, and created this one for the same commit, with the proper CLA this time. Sorry for the inconvenience.

**Comment by wrwg** [comment]
PS. Please mark in the title of the PR the context. E.g. `[language][prover] Update translator_tests.rs`. It's convention for libra PRs.

**Pull request closed without merging**
