### PR TITLE
[move framework][move-prover] Changed spec_has_*_role to take addresses.

### PR DESCRIPTION
**Pull request by DavidLDill**
Changed Roles::spec_has_*_role and Roles::spec_has_*_privilege functions
to consistently take addresses instead of signers as arguments.  This
is more convenient for some specifications.

## Motivation

(Write your motivation for proposed changes here.)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

(Share your test plan here. If you changed code, please provide us with clear instructions for verifying that your changes work.)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by sblackshear** [comment]
> I also think that such spec functions taking `addr` as an argument would be very convenient because global properties often quantify over addresses rather than accounts. However, one little concern is that `Roles::spec_has_role` becomes inconsistent to `Roles::has_role` which takes an `account` as an argument. How about defining additional spec functions `Roles::spec_addr_has_role` or `Roles::spec_has_role_addr`?

Changing `Roles::has_role` to accept an address also makes sense to me.

**Comment by DavidLDill** [comment]
I changed spec_has...role to spec_has...role_addr everywhere.

I haven't needed a Move version.  It's good to keep the Move has...role functions checking signers, because the main (only?) purpose is to check authorization of the signer to perform some action.

**Pull request closed without merging**
