### PR TITLE
T78662332 - DesignatedDealer::add_tier(...) should be private

### PR DESCRIPTION
**Pull request by moeziniaf**
add_tier can only be called when the address has a TierInfo resource.  This resource can only be created in add_currency(...), which automatically sets 4 tiers. Since a DD can only have 4 tiers (checked against a constant), there is no case where add_tier will succeed if called from outside the module.

### CODE REVIEW

**Review by sblackshear — APPROVED** [review]
Thanks!

**Review by mickayz — APPROVED** [review]
LGTM

**Comment by moeziniaf** [comment]
Any idea why `execute_genesis_and_drop_other_transaction` is failing?

**Pull request closed without merging**
