### PR TITLE
split out core Move VM logic into separate crates

### PR DESCRIPTION
**Pull request by sunshowers**
One of the design goals for the Move VM is for it to be possible to use it
in other blockchains. This split is an important step towards achieving that
goal.

Introduce two crates:

* `move-vm-runtime`: core interpreter for the Move VM
* `move-vm-state`: an implementation of state management for the Move VM

There's still a lot more work to be done -- such as figuring out how
flexible things like account addresses can be.

### CODE REVIEW

**Comment by sunshowers** [comment]
Meant to be a draft PR but I didn't hit the right button so here we are... :(

**Comment by dariorussi** [comment]
this seems fine to me and a good way to start the break up.
`StateView` and `InterpreterContext` will change in time and I am not sure we want to do anything at this point, just pointing out for future reference

**Comment by sunshowers** [comment]
This is ready for review now :)

**Comment by sunshowers** [comment]
> this is great thanks!
> question: we talked offline about some split and this is creating a move-vm and leaving the old vm to the Libra layer, right?
> The move-core we talked about is not here yet? or was it there already?

Yes, that will come after this lands (working on it now!)

**Pull request closed without merging**
