### PR TITLE
[X] Refactoring to use IoC via CoI, it's not perfect (too verbose) but promising.

### PR DESCRIPTION
**Pull request by rexhoffman**
## Motivation

Introduce IoC as a single abstract factory/state management engine/caching layer and primary means of decoupling in to x (and if it proves promising potentially to libra).

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

yes

## Test Plan

Added a basic test that shows that managed singletons are started once in the container, regardless of order of reference to instances for a handful of instances.

## Related PRs

none

### CODE REVIEW

**Comment by rexhoffman** [comment]
Basic use of Coi in X.   Would like to get buy in from the team before proceeding.   There is some overhead in coi that I think can be improved but would be longer term.

**Comment by sunshowers** [comment]
Thanks for doing this!

So having looked at this code in more detail, I'm afraid I'm not really convinced of the additional value this provides over just passing down an `XContext` instance the way we do it now.

To be clear, I would be a huge fan of moving all of the stuff currently in `utils` to `XContext` so that we can control those parameters for test situations. That makes a lot of sense to me. My concern is specifically with using a framework like this to do so.

Looking at some of the docs here: https://docs.rs/coi/0.9.2/coi/index.html I'm really concerned about things like:

> The name of the field is important!

> // Reminder: Make sure you use the same key here as the field names of the structs that
> // require these impls.

I'm also concerned that this will make us less flexible as far as things like lifetimes go, since downcasting can only be done to types that are `'static` (i.e. hold no references to non-static elements).

**Comment by bmwill** [comment]
Thanks for taking a look into this. I share some of Rain's concerns, and one other thing that jumped out to me is the reliance on strings to pull data out of the `coi` data structure. It seems it would be easy to mistype a string and not notice till runtime that something is wrong (short of defining Const that you use instead).

It also seems like this is quite verbose and overly complicated to solve the same problem that passing a direct `XContext` struct around would solve as Rain pointed out.

**Comment by rexhoffman** [comment]
Yeah -- strings are needed due to the instances being just that, instances.   If we try to tie types to them we wouldn't be able to define instances cleanly.    As I said this isn't a perfect ioc container.  In java land I built compile time checking for the graph around the strings.   Seems the same would be doable here.   This crate currently has an analysis feature to verify the graph at test time and produce a dot file of the graph.

**Comment by rexhoffman** [comment]
A less flexible and perhaps less composable but stringless implementation for rust is here:   https://docs.rs/shaku/0.2.0/shaku/.  But I do want to point out that either implementation would prevent us from calling cargo command multiple times the way we are now by properly caching data once it's looked up the first time -- whenever that is, by whichever instance from the container needs it first.

**Comment by rexhoffman** [comment]
I'll start writing up some of the benefits of IoC as I look in to shaku to have a full compile time generated graph.  I'm not sure if shaku will have the composability of coi's dependency graphs - but that could be me missing something.

So let's look at the trade offs of:
1.  not having a context - the state of the current utils.rs file.
2.  having developer managed contexts - the case of the all the commands, and in linter
3.  IoC with coi, and soon shaku.

To not burry the lede, special attention we be paid to refactorability -- the cost of adding in/modifying behavior, as well as the ease of caching computed data.

Since I've only converted a small part of the graph let's look at the two pieces of data:

1) Determining if we are at the project root:
https://github.com/libra/libra/blob/master/devtools/x/src/utils.rs#L29-L34

2) The reading of the config data:
https://github.com/libra/libra/blob/master/devtools/x/src/config.rs#L72-L74

I'm going to write them up one at a time, so I can take breaks and collect my thoughts.

Lets start with not having a context:

Effectively we have a chain of function calling each other.   Which is elegant.

However, each of these functions call the function **project_root** https://github.com/libra/libra/blob/master/devtools/x/src/utils.rs#L12-L17.
Notice that **project_root**, executes a command, and calls out to the os.
Data that should be extracted from the environment once is instead wastefully called each time a function is executed, for lack of a place to store that data.

There is another major downside here:   the config.rs file must be aware of where the path is coming from:    https://github.com/libra/libra/blob/master/devtools/x/src/config.rs#L4
This direct function chaining means that all functions must be known and referencable at compile time.  (a.k.a not passing around lambdas as that requires a context as well - be it a function body, aka a block of context, a struct as a trait object, or an extensible map of names to lambdas - an IoC context).

So the trade off here is we are overly simple leading to:

**Benefits:**

1. Very easy to read code - the functions are super clear in what they do.
2. Moderately easy to refactor code.   Developers are likely to end up with import cycles pretty quickly.  Usually by the 3-4 file.  (This is hand wavy because it's more about how people tend to interact with these systems over time introducing new functions calling other functions, but the study of import _tangles_ exist for a reason).

**Costs:**

1. redundant identical computation
2. each rust file needing to import others to chain functions - not necessarily bad until we end up with cycles in the future.   Which is a good prelude to developer managed contexts....  which will be the next write-up

**Comment by rexhoffman** [comment]
@sunshowers while I dislike the 'static reference I believe it can be solved with a more powerful code generator, and am actually interested in solving that problem, but I will address those concerns when comparing the flexibility of an IoC container vs a developer manage object graph.

To not burry the lede and give you a preview, IoC containers, by virtue of having a map of ids (playing a similar role to a fields on a struct)  to functions that will build those instances, when requested (lazy and parallelizable with developers write that code), from a lambda function that references other fields (via ids) by defining a directed acyclic graph.   This is powerful because context freely composable as long as ids don't conflict.   There is no corresponding programming model to freely compose structs.   Also, you'll note in my example above the IoC definition is self contained.   None of the functions its using to construct the minimal structs its own are polluted data, or indeed know that the container exists, they are only passed the data they need.  While I'm not in love with the mechanisms Coi is currently making me employ (I think a better code generator could make the definitions far simpler) it is currently sufficient to decouple the application's data from it's functions, without making every function know about a global context, or requiring developers to make a projection of that data in imperative code that they will feel free to modify - and in effect couple the functional transformation of that data to the code that should only be making a projection.

Also, I solved 'static issue for myself in my current wiring by just using a Box<> in the structs I have to define.

Still need to write up the full comparison of developer managed contexts to IoC contexts though.

**Comment by rexhoffman** [comment]
Since the team seems opposed to IoC patterns at this time, closing this request.   Took a look at shaku in another pr, but it lacks any ability to invoke construction logic for a struct which would be fine if there was a mechanism for a managed instance if producers (manage components creating other components) could also exist in the same context, but unfortunately the can not.   Setting aside for now.   As the complexity increases in x, may revisit, but the ioc tools in rust are in pretty rough shape.

**Pull request closed without merging**
