### PR TITLE
.DS_Store banished

### PR DESCRIPTION
**Pull request by awsom82**
## Motivation

ignore trash files on OSX 

### Have you read the [Contributing Guidelines on pull requests](../CONTRIBUTING.md#pull-requests)?

YES

## Test Plan

(Share your test plan here. If you changed code, please provide us with clear instrutions for verifying that your changes work.)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/website, and link to your PR here.)

### CODE REVIEW

**Comment by awsom82** [comment]
I think it may be better to cover the most popular os trash files.
If so, please – write here, I will add 

```.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db
```

**Comment by marceloboeira** [comment]
It doesn't make sense, those should be in your global gitignore, not each repo's one.

https://help.github.com/en/articles/ignoring-files

**Comment by spartucus** [comment]
And `.vscode/`

**Comment by ericnakagawa** [comment]
Thanks for the PR @awsom82. Thanks for updating the ignore file. Our team is reviewing your PR and will reply back soon. We're still sorting out CLAs and will reply back with an update.

**Comment by huitseeker** [comment]
Thanks for the PR!
Platform-specific files should probably be dealt with using a local `.gitignore` rather than checked into the repo.

**Pull request closed without merging**
