### PR TITLE
[easy][consensus] Small rewrites of boolean match to if

### PR DESCRIPTION
**Pull request by huitseeker**
Non-stable (i.e. future) versions of clippy will actually complain in this case!

### CODE REVIEW

**Comment by huitseeker** [comment]
@davidiw You can `#[allow(match_bool)]` if need be.

**Comment by davidiw** [comment]
> @davidiw You can `#[allow(match_bool)]` if need be.

I'm no snowflake, I conform to the will of the clippy organization....

**Comment by bmwill** [comment]
If these are the last ones do you want to remove the whitelist for this lint from `x.toml`?

**Pull request closed without merging**
