### PR TITLE
[docker] Add validator-dynamic docker configs

### PR DESCRIPTION
**Pull request by opsguy**
## Motivation
Adds new docker directory for validator that also uses new config-builder

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes
## Test Plan
On-going work in progress, will be iterating

### CODE REVIEW

**Comment by sausagee** [comment]
@bors-libra r+
LGTM

**Comment by andll** [comment]
As we discussed in meeting - I wonder if it makes sense to name this with a more generic, like `validator-test` instead of `validator-dynamic`, so that later we can add more things related to test environment to this docker image, such as benchmarks, etc?

**Comment by opsguy** [comment]
sorry, i know we discussed that and i think it is worthwhile, but i have so much in flight right now just need to get this landed. once things are working we can go back and change if needed
@bors-libra retry

**Pull request closed without merging**
