### PR TITLE
[file-format][bytecode-verifier] new bytecodes for vector operations - (92)

### PR DESCRIPTION
**Pull request by ankitkacn**
### Motivation
Not all native functions are equal. Some native functions are more applicable in the Diem context while other are more generic and may be better supported at the language level. Vector is one example that may be promoted to have some support at the bytecode level.

Added the following new bytecodes to support basic vector operations:

```VecPack```(N) Create a vector of length N by consuming the last N elements from stack
```VecLen``` Get the length of a vector
```VecImmBorrow``` Acquire an immutable reference to the element at a given index of the vector
```VecMutBorrorw``` Acquire a mutable reference to the element at a given index of the vector.
```VecPushBack``` Add an element to the end of the vector
```VecPopBack``` Pop an element from the end of vector
```VecUnpack```(N) Destroy a vector of length N and unpack its elements onto the stack.
```VecSwap``` Swaps the elements at two indices in the vector
Several related bytecode verifiers are updated too, including

- Bounds checker: the signature index in the bytecode is within bounds
- Signature: the signature index in the bytecode corresponds to a single-token, non-reference signature
- Stack usage: the vector operations consumes and also produces the correct number of values on the stack
- Type safety: vector and the argument types are correct. For ```VecPack```(N) the last N elements on the stack must have the element type.

Reference safety: vector are in a correct imm/mut state when related operations happen
Other misc but related updates include

- Added new bytecodes to the zero-cost gas schedule table
- Added new bytecodes to the initial gas schedule table, copying values from the native op table
- Proptest fuzzers are updated to produce valid and invalid inputs regarding these bytecode

A larger context that is considered is the separation of Move stdlib and Diem framework. Promoting native vector operations into bytecode will ease the separation.

As a small side benefit, this will also improve the user experience of using Vector in Move. At least we don’t have to write use 0x1::Vector all the time for basic vector operations. And also shrink Vector.move from stdlib.

Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/master/CONTRIBUTING.md#pull-requests)?
Yes

### Test Plan
- cargo test --package bytecode-verifier-tests --lib -- unit_tests::bounds_tests::empty_module_no_errors --exact --nocapture 
- CI/CD test are covered

### CODE REVIEW

**Review by dhaneshacn — APPROVED** [review]

**Comment by ankitkacn** [comment]
Closing this PR due to technical problem, raised new PR under the same name https://github.com/diem/diem/pull/10636

**Pull request closed without merging**
