### PR TITLE
[dep] cargo update

### PR DESCRIPTION
**Pull request by rexhoffman**
## Motivation

tidying up.  test tokio upgrade with transitive deps.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

yes

## Test Plan

ci

### CODE REVIEW

**Comment by rexhoffman** [comment]
@sunshowers @metajack shall we see if tokio 2.18 is happier in e2e tests with updated deps?

**Comment by rexhoffman** [comment]
I suspect a good number are transitive deps that wouldn't have been seen by dependabot -- though it does make me question some of the value of dependabot in a rust project to see so many out of date deps.

**Comment by sausagee** [comment]
@bors-libra delegate+

The version bump added quite a few 3rd party deps. Will defer to @metajack. Added the delegate above to unblock so the PR can run LBT/CT through CI/GHA.

**Comment by rexhoffman** [comment]
closing this as tokio will need special handling

**Pull request closed without merging**
