### PR TITLE
[storage] Fix a lint error due to missing test attribute.

### PR DESCRIPTION
**Pull request by changyonghu**
Since nobody is fixing this.

### CODE REVIEW

**Comment by andll** [comment]
Thanks @changyonghu 

@changyonghu @metajack do we want to catch those problems in CI, so that we don't have to manually fix unrelated files?

**Comment by snakech** [comment]
> @bors-libra /land

...

**Comment by metajack** [comment]
Bors understood the original command and queued the build. It will land the code when this PR is up in the queue.

**Comment by metajack** [comment]
> > @bors-libra /land
> 
> ...

Don't prefix your command with `@bors-libra`. The new system does not require that.

**Comment by metajack** [comment]
> Bors understood the original command and queued the build. It will land the code when this PR is up in the queue.

FYI, you can tell it did this because of the rocket ship emoji bors put on the original `/land` command.

**Comment by snakech** [comment]
> Bors understood the original command and queued the build. It will land the code when this PR is up in the queue.

ahaha, Acked, Bors is running reinforcement learning

**Comment by snakech** [comment]
> > Bors understood the original command and queued the build. It will land the code when this PR is up in the queue.
> 
> FYI, you can tell it did this because of the rocket ship emoji bors put on the original `/land` command.

thx for the new feature, just replaced a new laptop without slack during shipment, lost some context about bors change

**Comment by changyonghu** [comment]
@metajack Seems ValidatorSet is auto imported, so we don't need to import twice.

**Pull request closed without merging**
