### PR TITLE
[language] Remove error_specializer in preparation for a logger arg

### PR DESCRIPTION
**Pull request by dariorussi**
This is mostly because we are adding another arguments to all the
runtime functions and it's getting a bit too many...
So it is an attempt to see how the code looks removing the error specializer

### CODE REVIEW

**Review by tnowacki — APPROVED** [review]
This looks fine

**Comment by dariorussi** [comment]
Todd accepted it already in draft form, so before he changes his mind I am going to get this in.... lol....

**Review by tnowacki — APPROVED** [review]

**Pull request closed without merging**
