### PR TITLE
[RFC][Proof] No bitmaps?

### PR DESCRIPTION
**Pull request by wqfish**
## Motivation

The bitmaps seem kind of complex. If we simply use an empty byte array to represent the placeholder nodes, the proof size should stay roughly the same and the parsing can be simplified a lot? Putting this up to see if people like this approach or something similar.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

No.

## Test Plan

CI.

## Related PRs

None.

### CODE REVIEW

**Comment by zamsden** [comment]
This does make everything a lot simpler - I think the cognitive overhead in understanding this was quite a lot.

@bors-libra delegate

**Comment by davidiw** [comment]
This is such an awesome PR! Thanks for doing this!!!!

**Comment by msmouse** [comment]
Beautiful.

More symmetric to `AccumulatorRangeProof`, can we actually remove placeholders entirely? Since with address of the element to be proven, we know exactly where the placeholders should be?

**Comment by lightmark** [comment]
Looks much better. Nits: As @msmouse suggested, the accumulator proof format should include `num_leaves` which eliminates the needs of empty byte array.

**Pull request closed without merging**
