### PR TITLE
Add sliding nonce resource to LR

### PR DESCRIPTION
**Pull request by moeziniaf**
## Motivation

We need SR in LR for AOS transactions.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Existing SR tests.

## Other

I ran cargo run which has included some other markdown changes, which should be fine.

### CODE REVIEW

**Comment by valerini** [comment]
Nice!

**Comment by sblackshear** [comment]
Would you mind adding a test for this? A tx that checks `exists<SlidingNonce>(0xa550c18)` should be enough.

**Comment by tzakian** [comment]
@bors-libra r- 

Seems as though cancel doesn't work :(

**Comment by moeziniaf** [comment]
> Would you mind adding a test for this? A tx that checks `exists<SlidingNonce>(0xa550c18)` would be good. @tzakian has recently made it possible to call tx scripts from the functional tests, so we can also test that some of the scripts that require a sliding nonce can now be sent from LR.

Covered in https://github.com/libra/libra/pull/5284 and https://github.com/libra/libra/pull/5321

**Pull request closed without merging**
