### PR TITLE
[move source language] Check for overlapping targets/deps

### PR DESCRIPTION
**Pull request by tnowacki**
- Added check for something that bit me a lot in the CLI
- Deps and Targets cannot overlap

## Motivation

- I got very confused and want to prevent others from being confused

## Test Plan

- A bit hard to test currently, as none of the move testing infra uses specified files
- Might add a CLI test

### CODE REVIEW

**Review by bob-wilson — APPROVED** [review]
Seems like a good idea to check this. A test would certainly be nice if you think of a way to do that in the future.

**Comment by sblackshear** [comment]
I think it should be pretty easy to write a move CLI expected value test for this

**Comment by tnowacki** [comment]
> I think it should be pretty easy to write a move CLI expected value test for this

I can't do it yet because the setup for check/build is a bit off in the CLI. If I get around to fixing that, I'll add a test

**Pull request closed without merging**
